import { useState, useMemo } from "react";
import { Users, UserCheck, Calendar, DollarSign, TrendingUp, Target, Phone, Settings, X, Check, AlertTriangle, Zap, Plus, Trash2, Eye, EyeOff, Award, Loader2, Search, ArrowRightLeft, Sun, Moon } from "lucide-react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, CartesianGrid, Area, AreaChart } from "recharts";
import { supabase } from "../lib/supabase";
import { GOLD, BG, TEXT1, GOLD_HEX, EASE, TEAM_COLORS, fmt, pct, GOLD_LIGHT, GOLD_DIM, GOLD_BG, GOLD_BG2, BG2, BG3, BORDER, BORDER2, TEXT2, TEXT3 } from "../lib/constants";
import { Card, Spinner, MC, LeadCard, AddLeadModal } from "../components/ui";

function DashboardPage({leads,config,adsTotals,stages,qualStages,agendStages}){
const total=leads.length;const qual=leads.filter(l=>qualStages.includes(l.stage)).length;const agend=leads.filter(l=>agendStages.includes(l.stage)).length;const vendas=leads.filter(l=>l.stage==="fechado");const rec=vendas.reduce((s,l)=>s+(l.valor_venda||0),0);const cc=vendas.reduce((s,l)=>s+(l.cash_collect||0),0);const tm=vendas.length>0?Math.round(rec/vendas.length):0;const gasto=adsTotals?.spend||config?.gasto_ads_mensal||0;const meta=config?.meta_mensal||0;
const forecast=useMemo(()=>{const tQ=total>0?qual/total:0,tA=qual>0?agend/qual:0,tV=agend>0?vendas.length/agend:0;const eA=leads.filter(l=>["reuniao_agendada","reuniao_realizada","proposta_enviada"].includes(l.stage)).length;const eQ=leads.filter(l=>l.stage==="qualificado").length;return Math.round((eA*tV*tm)+(eQ*tA*tV*tm));},[leads]);
const funnel=[{label:"Leads",value:total,color:GOLD,rate:100},{label:"Qualificados",value:qual,color:"#34D399",rate:pct(qual,total)},{label:"Agendados",value:agend,color:"#A78BFA",rate:pct(agend,total)},{label:"Fechados",value:vendas.length,color:"#4ADE80",rate:pct(vendas.length,total)}];
const daily=useMemo(()=>{const m={};leads.forEach(l=>{const d=new Date(l.created_at).toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"});if(!m[d])m[d]={dia:d,leads:0};m[d].leads++;});return Object.values(m).slice(-14);},[leads]);
const FB=({label,value,maxVal,color,rate})=>{const w=maxVal>0?(value/maxVal)*100:0;return<div className="flex items-center gap-3" style={{padding:"4px 0"}}><div style={{width:90,textAlign:"right",flexShrink:0,fontSize:11,color:TEXT2}}>{label}</div><div className="flex-1 overflow-hidden" style={{height:24,borderRadius:5,background:"rgba(255,255,255,0.03)"}}><div className="flex items-center" style={{height:"100%",width:`${Math.max(w,4)}%`,borderRadius:5,background:color,opacity:.85,paddingLeft:6}}><span style={{fontSize:10,fontWeight:600,color:"#fff"}}>{value}</span></div></div><div style={{width:36,textAlign:"right",flexShrink:0,fontSize:10,color:TEXT3}}>{rate}%</div></div>;};
return<div style={{display:"flex",flexDirection:"column",gap:14}}>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10}}><MC icon={Users} label="Leads" value={total} accent/><MC icon={UserCheck} label="Qualificados" value={qual} sub={`${pct(qual,total)}%`}/><MC icon={Calendar} label="Agendados" value={agend}/><MC icon={DollarSign} label="Fechados" value={vendas.length} sub={`${pct(vendas.length,total)}%`}/></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10}}><MC icon={DollarSign} label="Receita" value={fmt(rec)} accent/><MC icon={DollarSign} label="Cash Collect" value={fmt(cc)} sub="recebido"/><MC icon={Zap} label="Forecast" value={fmt(forecast)} sub="pipeline"/><MC icon={TrendingUp} label="Leads/venda" value={vendas.length>0?Math.round(total/vendas.length):"—"}/></div>
{gasto>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10}}><MC icon={DollarSign} label="CPL" value={total>0?fmt(Math.round(gasto/total)):"—"}/><MC icon={Target} label="CPL Qualif." value={qual>0?fmt(Math.round(gasto/qual)):"—"}/><MC icon={Calendar} label="Custo/Agend." value={agend>0?fmt(Math.round(gasto/agend)):"—"}/><MC icon={DollarSign} label="CAC" value={vendas.length>0?fmt(Math.round(gasto/vendas.length)):"—"}/></div>}
{meta>0&&<Card style={{padding:14}}><div className="flex items-center justify-between" style={{marginBottom:6}}><span style={{fontSize:10,color:TEXT3,textTransform:"uppercase"}}>Meta mensal</span><span style={{fontSize:10,color:TEXT2}}>{fmt(cc)} / {fmt(meta)}</span></div><div style={{height:7,borderRadius:3,background:"rgba(255,255,255,0.04)",overflow:"hidden"}}><div style={{height:"100%",borderRadius:3,background:cc>=meta?"linear-gradient(90deg,#4ADE80,#22c55e)":`linear-gradient(90deg,${GOLD},${GOLD_LIGHT})`,width:`${Math.min((cc/meta)*100,100)}%`}}/></div><div style={{fontSize:18,fontWeight:600,color:cc>=meta?"#4ADE80":GOLD_LIGHT,marginTop:6}}>{meta>0?Math.round((cc/meta)*100):0}%</div></Card>}
<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:10}}>Funil</h3>{funnel.map(f=><FB key={f.label} {...f} maxVal={total}/>)}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6,marginTop:12,paddingTop:12,borderTop:`1px solid ${BORDER}`}}>{[{v:vendas.length>0?Math.round(total/vendas.length):"—",l:"Leads/venda"},{v:vendas.length>0?Math.round(qual/vendas.length):"—",l:"Qualif./venda"},{v:vendas.length>0?Math.round(agend/vendas.length):"—",l:"Agend./venda"}].map(m=><div key={m.l} style={{textAlign:"center"}}><div style={{fontSize:18,fontWeight:600,color:GOLD_LIGHT}}>{m.v}</div><div style={{fontSize:8,color:TEXT3,marginTop:2}}>{m.l}</div></div>)}</div></Card>
{daily.length>0&&<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:10}}>Leads/dia</h3><ResponsiveContainer width="100%" height={180}><AreaChart data={daily}><defs><linearGradient id="gL" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={GOLD_HEX} stopOpacity={.25}/><stop offset="95%" stopColor={GOLD_HEX} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)"/><XAxis dataKey="dia" tick={{fill:"var(--text3)",fontSize:9}} axisLine={false} tickLine={false}/><YAxis tick={{fill:"var(--text3)",fontSize:9}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:8,color:TEXT1,fontSize:10}}/><Area type="monotone" dataKey="leads" stroke={GOLD_HEX} fill="url(#gL)" strokeWidth={2}/></AreaChart></ResponsiveContainer></Card>}
</div>;}

function PipelinesModal({pipeHook,activePipelineId,onSelectPipeline,onClose,showPrompt,showConfirm,showToast}){
const[newLabel,sNewLabel]=useState("");const[newColor,sNewColor]=useState("#60A5FA");
const COLORS=["#0D9488","#60A5FA","#38BDF8","#34D399","#A78BFA","#818CF8","#FBBF24","#FB923C","#22D3EE","#94A3B8","#4ADE80","#F87171","#F472B6","#E879F9"];
const stages=pipeHook.stages;const pipelines=pipeHook.pipelines;const act=pipelines.find(p=>p.id===activePipelineId);
const move=(i,dir)=>{const j=i+dir;if(j<0||j>=stages.length)return;pipeHook.reorderStages(i,j);};
const IB={width:28,height:28,borderRadius:6,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT2,cursor:"pointer",fontSize:12,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0};
const SB={padding:"5px 10px",borderRadius:6,border:`1px solid ${BORDER}`,background:BG2,color:TEXT2,fontSize:10.5,fontWeight:600,cursor:"pointer"};
return<div style={{position:"fixed",inset:0,zIndex:120,display:"flex",alignItems:"center",justifyContent:"center",padding:16,background:"var(--overlay)",backdropFilter:"blur(8px)",WebkitBackdropFilter:"blur(8px)"}} onClick={onClose}>
<div onClick={e=>e.stopPropagation()} style={{width:"100%",maxWidth:820,maxHeight:"85vh",display:"flex",flexDirection:"column",background:BG2,border:`1px solid ${BORDER2}`,borderRadius:16,overflow:"hidden",boxShadow:"0 12px 48px rgba(0,0,0,0.3)",animation:`modalIn 250ms ${EASE}`}}>
<div className="flex items-center justify-between" style={{padding:"16px 20px",borderBottom:`1px solid ${BORDER}`}}><h3 style={{fontSize:15,fontWeight:700,color:TEXT1,margin:0}}>Gerenciar Pipelines</h3><button onClick={onClose} style={{padding:8,borderRadius:8,border:"none",background:"var(--bg-hover)",cursor:"pointer",color:TEXT2}}><X size={16}/></button></div>
<div style={{display:"grid",gridTemplateColumns:"250px 1fr",flex:1,minHeight:0}}>
<div style={{borderRight:`1px solid ${BORDER}`,padding:14,overflowY:"auto"}}>
<button onClick={async()=>{const name=await showPrompt("Nome do novo pipeline");if(name){const pip=await pipeHook.addPipeline(name);if(pip){onSelectPipeline(pip.id);showToast("Pipeline criado","success");}}}} style={{width:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:6,padding:"10px 0",borderRadius:8,border:"none",background:"linear-gradient(135deg,#14B8A6,#0D9488)",color:"#fff",fontSize:12,fontWeight:700,cursor:"pointer",marginBottom:12}}><Plus size={14}/>Novo Pipeline</button>
{pipelines.map(p=>{const on=p.id===activePipelineId;return<div key={p.id} onClick={()=>onSelectPipeline(p.id)} style={{padding:"10px 12px",borderRadius:9,border:`1.5px solid ${on?"var(--gold-border)":BORDER}`,background:on?GOLD_BG:"transparent",marginBottom:6,cursor:"pointer"}}>
<div style={{fontSize:13,fontWeight:on?700:500,color:on?GOLD:TEXT1}}>{p.nome}</div>
{on&&<div className="flex gap-1 flex-wrap" style={{marginTop:8}}>
<button onClick={async e=>{e.stopPropagation();const name=await showPrompt("Novo nome",p.nome);if(name){await pipeHook.renamePipeline(p.id,name);showToast("Renomeado","success");}}} style={SB}>✏️ Renomear</button>
<button onClick={async e=>{e.stopPropagation();const pip=await pipeHook.duplicatePipeline(p.id,p.nome+" (cópia)");if(pip){onSelectPipeline(pip.id);showToast("Pipeline duplicado","success");}}} style={SB}>⧉ Duplicar</button>
{pipelines.length>1&&<button onClick={async e=>{e.stopPropagation();const ok=await showConfirm("Excluir pipeline","As etapas deste pipeline serão removidas. Os leads não são apagados.",true);if(ok){await pipeHook.deletePipeline(p.id);showToast("Pipeline excluído");}}} style={{...SB,color:"#DC2626"}}>🗑 Excluir</button>}
</div>}
</div>;})}
</div>
<div style={{padding:16,overflowY:"auto"}}>
<div style={{fontSize:13,fontWeight:700,color:TEXT1,marginBottom:2}}>Etapas de "{act?.nome||"—"}"</div>
<p style={{fontSize:10.5,color:TEXT3,margin:"0 0 12px"}}>A 1ª etapa recebe os leads novos. Reordene com ▲▼, clique no quadradinho para trocar a cor e edite o nome direto no campo.</p>
{stages.map((s,i)=><div key={s.id||s.key} className="flex items-center gap-2" style={{padding:"7px 10px",borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:5,background:BG3}}>
<span style={{fontSize:10,fontWeight:700,color:TEXT3,width:18,textAlign:"center",flexShrink:0}}>{i+1}º</span>
<div title="Clique para trocar a cor" onClick={()=>{const idx=COLORS.indexOf(s.color);pipeHook.updateStage(s.id,{color:COLORS[(idx+1)%COLORS.length]});}} style={{width:18,height:18,borderRadius:5,background:s.color,cursor:"pointer",flexShrink:0}}/>
<input value={s.label} onChange={e=>pipeHook.updateStage(s.id,{label:e.target.value})} style={{flex:1,minWidth:60,padding:"4px 8px",borderRadius:5,border:"none",background:"transparent",color:TEXT1,fontSize:12.5,fontWeight:500,outline:"none"}}/>
<button title="Subir" disabled={i===0} onClick={()=>move(i,-1)} style={{...IB,opacity:i===0?0.3:1}}>▲</button>
<button title="Descer" disabled={i===stages.length-1} onClick={()=>move(i,1)} style={{...IB,opacity:i===stages.length-1?0.3:1}}>▼</button>
<button title="Excluir etapa" onClick={async()=>{const ok=await showConfirm("Excluir etapa",`Excluir "${s.label}"? Leads dessa etapa passam a aparecer na 1ª coluna.`,true);if(ok)pipeHook.deleteStage(s.id);}} style={{...IB,color:"#DC2626"}}>✕</button>
</div>)}
<div className="flex items-center gap-2" style={{marginTop:12,padding:10,borderRadius:8,border:`1px dashed ${BORDER2}`}}>
<div title="Cor da nova etapa" onClick={()=>{const idx=COLORS.indexOf(newColor);sNewColor(COLORS[(idx+1)%COLORS.length]);}} style={{width:18,height:18,borderRadius:5,background:newColor,cursor:"pointer",flexShrink:0}}/>
<input value={newLabel} onChange={e=>sNewLabel(e.target.value)} placeholder="Nome da nova etapa..." onKeyDown={e=>{if(e.key==="Enter"&&newLabel.trim()){pipeHook.addStage(activePipelineId,newLabel.trim(),newColor);sNewLabel("");}}} style={{flex:1,padding:"8px 10px",borderRadius:6,border:`1px solid ${BORDER}`,background:BG2,color:TEXT1,fontSize:12,outline:"none"}}/>
<button onClick={()=>{if(!newLabel.trim())return;pipeHook.addStage(activePipelineId,newLabel.trim(),newColor);sNewLabel("");}} style={{padding:"8px 14px",borderRadius:6,border:"none",background:GOLD_BG2,color:GOLD,fontSize:11,fontWeight:700,cursor:"pointer",flexShrink:0}}>+ Adicionar</button>
</div>
</div>
</div></div></div>;}

function CRMPage({leads,onLeadClick,onUpdate,equipe,onAdd,stages,pipelines,activePipelineId,onSelectPipeline,pipeHook,showPrompt,showConfirm,showToast,config,qualStages,etiquetas,isClinica,unread}){const mqlThreshold=config?.mql_threshold||0;const[search,sSearch]=useState("");const[filterSdr,sFilter]=useState("");const[filterTag,sFilterTag]=useState("");const[showAdd,sShowAdd]=useState(false);const[dragOver,sDragOver]=useState(null);const[showPipeEdit,sShowPipeEdit]=useState(false);
const filtered=useMemo(()=>{let f=leads;if(activePipelineId)f=f.filter(l=>l.pipeline_id?l.pipeline_id===activePipelineId:activePipelineId===pipelines?.[0]?.id);if(search){const s=search.toLowerCase();f=f.filter(l=>(l.nome||"").toLowerCase().includes(s)||(l.telefone||"").includes(s)||(l.instagram||"").toLowerCase().includes(s)||(l.utm_campaign||"").toLowerCase().includes(s));}if(filterSdr)f=f.filter(l=>l.sdr_nome===filterSdr);if(filterTag)f=f.filter(l=>(l.etiqueta_ids||[]).includes(filterTag));return f;},[leads,search,filterSdr,filterTag,activePipelineId,pipelines]);
const grouped=useMemo(()=>{const g={};stages.forEach(s=>{g[s.key]=[];});const firstKey=stages[0]?.key;filtered.forEach(l=>{if(g[l.stage])g[l.stage].push(l);else if(firstKey)g[firstKey].push(l);});return g;},[filtered,stages]);
const sdrs=[...new Set(leads.map(l=>l.sdr_nome).filter(Boolean))];
const handleDrop=async(sk,e)=>{e.preventDefault();sDragOver(null);const id=e.dataTransfer.getData("leadId");if(!id)return;const lead=filtered.find(l=>l.id===id);if(!lead||lead.stage===sk)return;const prevStage=lead.stage;const u={stage:sk};if(sk==="contato_iniciado")u.contatado_at=new Date().toISOString();if(sk==="qualificado")u.qualificado_at=new Date().toISOString();if(sk==="reuniao_agendada")u.agendado_at=new Date().toISOString();if(sk==="fechado")u.venda_at=new Date().toISOString();const ok=await onUpdate(id,u);if(!ok){showToast("Falha ao mover o lead — verifique a conexão","error");return;}const lbl=stages.find(s=>s.key===sk)?.label||sk;showToast(`Lead movido para "${lbl}"`,"success",{label:"Desfazer",fn:()=>onUpdate(id,{stage:prevStage})});};
return<div><div className="flex flex-wrap items-center gap-2" style={{marginBottom:14}}><div style={{position:"relative",flex:"1 1 180px"}}><Search size={13} style={{position:"absolute",left:9,top:"50%",transform:"translateY(-50%)",color:TEXT3}}/><input value={search} onChange={e=>sSearch(e.target.value)} placeholder="Buscar..." style={{width:"100%",padding:"8px 8px 8px 30px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG2,color:TEXT1,fontSize:12,outline:"none"}}/></div><select value={filterSdr} onChange={e=>sFilter(e.target.value)} style={{padding:"8px 10px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG2,color:TEXT1,fontSize:12,outline:"none"}}><option value="">Todos SDRs</option>{sdrs.map(s=><option key={s} value={s}>{s}</option>)}</select>{etiquetas&&etiquetas.length>0&&<select value={filterTag} onChange={e=>sFilterTag(e.target.value)} style={{padding:"8px 10px",borderRadius:8,border:`1px solid ${filterTag?"var(--gold-border)":BORDER}`,background:BG2,color:TEXT1,fontSize:12,outline:"none"}}><option value="">Todas etiquetas</option>{etiquetas.map(t=><option key={t.id} value={t.id}>{t.nome}</option>)}</select>}<button onClick={()=>sShowAdd(true)} style={{display:"flex",alignItems:"center",gap:5,padding:"7px 14px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:11,fontWeight:500,cursor:"pointer"}}><Plus size={13}/>Novo lead</button><button onClick={()=>sShowPipeEdit(true)} style={{padding:"7px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT2,cursor:"pointer",display:"flex",alignItems:"center",gap:5,fontSize:11,fontWeight:600}}><Settings size={13}/>Pipelines</button></div>

{showPipeEdit&&<PipelinesModal pipeHook={pipeHook} activePipelineId={activePipelineId} onSelectPipeline={onSelectPipeline} onClose={()=>sShowPipeEdit(false)} showPrompt={showPrompt} showConfirm={showConfirm} showToast={showToast}/>}
<div className="flex gap-2 overflow-x-auto pb-4 kb-scroll" style={{minHeight:500}}>{stages.map(stage=>{const sl=grouped[stage.key]||[];const sv=sl.reduce((s,l)=>s+(l.cash_collect||0),0);const vv=sl.reduce((s,l)=>s+(l.valor_venda||0),0);return<div key={stage.key} className="kb-col" onDragOver={e=>{e.preventDefault();sDragOver(stage.key);}} onDragLeave={()=>sDragOver(null)} onDrop={e=>handleDrop(stage.key,e)} style={{width:230,minWidth:230,flexShrink:0,background:dragOver===stage.key?"var(--gold-bg)":"var(--bg3)",border:`1px solid ${dragOver===stage.key?GOLD_DIM:BORDER}`,borderRadius:12,padding:10,transition:"all 0.2s"}}><div className="flex items-center justify-between" style={{marginBottom:8,padding:"2px 4px"}}><div className="flex items-center gap-2"><div style={{width:8,height:8,borderRadius:"50%",background:stage.color,flexShrink:0}}/><span style={{fontSize:11,fontWeight:700,color:TEXT1,letterSpacing:"0.01em"}}>{stage.label}</span></div><span style={{fontSize:10,fontWeight:600,padding:"2px 8px",borderRadius:10,background:"var(--bg-hover)",color:TEXT2}}>{sl.length}</span></div>{(vv>0||sv>0)&&<div style={{fontSize:9,color:TEXT3,marginBottom:6,paddingLeft:3}}>{vv>0&&<span>Venda: {fmt(vv)} </span>}{sv>0&&<span style={{color:GOLD_DIM}}>Cash: {fmt(sv)}</span>}</div>}{sl.map(lead=><LeadCard key={lead.id} lead={lead} onClick={onLeadClick} equipe={equipe} mqlThreshold={mqlThreshold} qualStages={qualStages} etiquetas={etiquetas} isClinica={isClinica} unreadCount={unread?unread[lead.id]||0:0}/>)}</div>;})}
</div>{showAdd&&<AddLeadModal onClose={()=>sShowAdd(false)} onAdd={onAdd} equipe={equipe} activePipelineId={activePipelineId} stages={stages}/>}</div>;}

function AnalyticsPage({leads,config,adsTotals,stages,qualStages,agendStages}){const[tab,sTab]=useState("campanha");const[compare,sCompare]=useState(false);const gasto=adsTotals?.spend||config?.gasto_ads_mensal||0;
const[drillCamp,sDrillCamp]=useState(null);const[drillAdset,sDrillAdset]=useState(null);
const[sortCol,sSortCol]=useState("spend");const[sortDir,sSortDir]=useState("desc");
const toggleSort=col=>{if(sortCol===col)sSortDir(d=>d==="desc"?"asc":"desc");else{sSortCol(col);sSortDir("desc");}};
const sortIcon=col=>sortCol===col?(sortDir==="desc"?"▼":"▲"):"";

const currentLevel=drillAdset?"criativo":drillCamp?"conjunto":"campanha";
const breadcrumb=[];
breadcrumb.push({label:"Campanhas",action:()=>{sDrillCamp(null);sDrillAdset(null);}});
if(drillCamp)breadcrumb.push({label:drillCamp,action:()=>{sDrillAdset(null);}});
if(drillAdset)breadcrumb.push({label:drillAdset,action:null});

const normK=s=>String(s||"—").normalize("NFKC").replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{FE0F}]/gu,"").replace(/[​-‍﻿]/g,"").toLowerCase().replace(/[–—−]/g,"-").replace(/\s+/g," ").trim();
function aggDrill(adsData,leadsData){const m={};const mqlT=config?.mql_threshold||0;
const utmField=!drillCamp?"utm_campaign":!drillAdset?"utm_term":"utm_content";
const mk=(k,name)=>{if(!m[k])m[k]={name:name||"—",leads:0,mql:0,sql:0,qualificados:0,agendados:0,vendas:0,receita:0,cash:0,spend:0,impressions:0,clicks:0,leads_meta:0};return m[k];};
let lds=leadsData;
if(drillCamp)lds=lds.filter(l=>normK(l.utm_campaign)===normK(drillCamp));
if(drillAdset)lds=lds.filter(l=>normK(l.utm_term)===normK(drillAdset));
lds.forEach(l=>{const rawName=l[utmField]||"—";const r=mk(normK(rawName),rawName);r.leads++;if(mqlT>0&&l.lead_score>=mqlT)r.mql++;if(qualStages.includes(l.stage)){r.sql++;r.qualificados++;}if(agendStages.includes(l.stage))r.agendados++;if(l.stage==="fechado"){r.vendas++;r.receita+=l.valor_venda||0;r.cash+=l.cash_collect||0;}});
let rows=adsData?.raw||[];
if(drillCamp)rows=rows.filter(x=>normK(x.campaign_name)===normK(drillCamp));
if(drillAdset)rows=rows.filter(x=>normK(x.adset_name)===normK(drillAdset));
const adField=!drillCamp?"campaign_name":!drillAdset?"adset_name":"ad_name";
rows.forEach(x=>{const rawName=x[adField]||"—";const r=mk(normK(rawName),rawName);r.name=rawName;r.spend+=x.spend||0;r.impressions+=x.impressions||0;r.clicks+=x.clicks||0;r.leads_meta+=x.leads_meta||0;});
return m;}

const ad=useMemo(()=>{const m=aggDrill(adsTotals,leads);const arr=Object.values(m);arr.sort((a,b)=>{const av=a[sortCol]??0,bv=b[sortCol]??0;if(typeof av==="string")return sortDir==="asc"?av.localeCompare(bv):bv.localeCompare(av);return sortDir==="asc"?av-bv:bv-av;});return arr;},[drillCamp,drillAdset,adsTotals,leads,sortCol,sortDir]);

const handleRowClick=name=>{if(!drillCamp)sDrillCamp(name);else if(!drillAdset)sDrillAdset(name);};

const sdrs=useMemo(()=>{const m={};const mqlT=config?.mql_threshold||0;leads.filter(l=>l.sdr_nome).forEach(l=>{if(!m[l.sdr_nome])m[l.sdr_nome]={name:l.sdr_nome,leads:0,mql:0,sql:0,qualificados:0,agendados:0};m[l.sdr_nome].leads++;if(mqlT>0&&l.lead_score>=mqlT)m[l.sdr_nome].mql++;if(qualStages.includes(l.stage)){m[l.sdr_nome].sql++;m[l.sdr_nome].qualificados++;}if(agendStages.includes(l.stage))m[l.sdr_nome].agendados++;});return Object.values(m);},[leads]);
const closers=useMemo(()=>{const m={};leads.filter(l=>l.closer_nome).forEach(l=>{if(!m[l.closer_nome])m[l.closer_nome]={name:l.closer_nome,reunioes:0,vendas:0,receita:0,cash:0};if(["reuniao_realizada","proposta_enviada","fechado","manter_contato"].includes(l.stage))m[l.closer_nome].reunioes++;if(l.stage==="fechado"){m[l.closer_nome].vendas++;m[l.closer_nome].receita+=l.valor_venda||0;m[l.closer_nome].cash+=l.cash_collect||0;}});return Object.values(m).sort((a,b)=>b.cash-a.cash);},[leads]);
const now=new Date();const thisM=leads.filter(l=>{const d=new Date(l.created_at);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();});const lastM=leads.filter(l=>{const d=new Date(l.created_at);const lm=new Date(now.getFullYear(),now.getMonth()-1);return d.getMonth()===lm.getMonth()&&d.getFullYear()===lm.getFullYear();});
const tmV=thisM.filter(l=>l.stage==="fechado"),lmV=lastM.filter(l=>l.stage==="fechado");

const thStyle={textAlign:"left",padding:"6px 6px",fontWeight:500,color:TEXT3,fontSize:9,textTransform:"uppercase",cursor:"pointer",userSelect:"none",whiteSpace:"nowrap"};
const cols=[{key:"name",label:currentLevel.charAt(0).toUpperCase()+currentLevel.slice(1)},{key:"leads",label:"Leads"},{key:"mql",label:"MQL"},{key:"sql",label:"SQL"},{key:"qualificados",label:"Qualif."},{key:"vendas",label:"Vendas"},{key:"leads_meta",label:"Leads Meta"},{key:"spend",label:"Spend"},{key:"cash",label:"Cash Collect"},{key:"roas",label:"ROAS"},{key:"cpl",label:"CPL"},{key:"pctMql",label:"% MQL"},{key:"pctQual",label:"% Qual."}];

return<div style={{display:"flex",flexDirection:"column",gap:14}}>
{compare&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Card style={{padding:14}}><div style={{fontSize:9,color:TEXT3,textTransform:"uppercase",marginBottom:6}}>Este mês</div><div style={{fontSize:18,fontWeight:600,color:GOLD_LIGHT}}>{fmt(tmV.reduce((s,l)=>s+(l.cash_collect||0),0))}</div><div style={{fontSize:10,color:TEXT2,marginTop:3}}>{thisM.length} leads • {tmV.length} vendas</div></Card><Card style={{padding:14}}><div style={{fontSize:9,color:TEXT3,textTransform:"uppercase",marginBottom:6}}>Mês passado</div><div style={{fontSize:18,fontWeight:600,color:TEXT2}}>{fmt(lmV.reduce((s,l)=>s+(l.cash_collect||0),0))}</div><div style={{fontSize:10,color:TEXT3,marginTop:3}}>{lastM.length} leads • {lmV.length} vendas</div></Card></div>}

<Card style={{padding:18}}>
<div className="flex items-center justify-between" style={{marginBottom:14}}><div className="flex items-center gap-3"><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,margin:0}}>Ads</h3><button onClick={()=>sCompare(!compare)} style={{display:"flex",alignItems:"center",gap:3,padding:"3px 8px",borderRadius:5,border:"none",background:compare?GOLD_BG2:"rgba(255,255,255,0.03)",color:compare?GOLD:TEXT3,fontSize:9,cursor:"pointer"}}><ArrowRightLeft size={9}/>Comparar</button></div></div>

<div className="flex items-center gap-1" style={{marginBottom:12,fontSize:10}}>{breadcrumb.map((b,i)=><span key={i} className="flex items-center gap-1">{i>0&&<span style={{color:TEXT3,margin:"0 2px"}}>›</span>}{b.action?<button onClick={b.action} style={{background:"none",border:"none",color:GOLD,cursor:"pointer",fontSize:10,fontWeight:500,padding:0,textDecoration:"underline"}}>{b.label}</button>:<span style={{color:TEXT1,fontWeight:500}}>{b.label}</span>}</span>)}</div>

<div style={{overflowX:"auto"}}><table style={{width:"100%",fontSize:11,borderCollapse:"collapse"}}>
<thead>
<tr>{[["",1],["Funil (CRM)",5],["Meta Ads",2],["Resultado",5]].map((g,i)=><th key={i} colSpan={g[1]} style={{padding:"5px 6px 3px",textAlign:i===0?"left":"center",fontSize:9,fontWeight:800,letterSpacing:"0.08em",textTransform:"uppercase",color:i===1?"#1D4ED8":i===2?"#B45309":i===3?"#0F766E":TEXT3,borderLeft:i>0?`2px solid ${BORDER2}`:"none"}}>{g[0]}</th>)}</tr>
<tr style={{borderBottom:`2px solid ${BORDER2}`}}>{cols.map(c=><th key={c.key} onClick={()=>c.key!=="roas"&&c.key!=="cpl"&&c.key!=="pctQual"&&toggleSort(c.key)} style={{...thStyle,color:sortCol===c.key?TEXT1:TEXT3,borderLeft:(c.key==="leads_meta"||c.key==="cash")?`2px solid ${BORDER2}`:"none"}}>{c.label} {sortIcon(c.key)}</th>)}</tr>
</thead>
<tbody>{(()=>{
const comG=ad.filter(r=>r.spend>0);const semG=ad.filter(r=>!(r.spend>0));
const zero=<span style={{color:"var(--text3)",opacity:.35}}>0</span>;
const gSep={borderLeft:`2px solid ${BORDER}`};
const secHead=(label,color,n)=><tr key={label}><td colSpan={cols.length} style={{padding:"13px 8px 5px",fontSize:9,fontWeight:800,letterSpacing:"0.08em",color,textTransform:"uppercase",borderBottom:`1px solid ${BORDER}`}}>{label} ({n})</td></tr>;
const rowFor=(r,i)=>{const roas=r.spend>0?(r.cash/r.spend).toFixed(1):"—";const cpl=r.spend>0&&r.leads_meta>0?fmt(Math.round(r.spend/r.leads_meta)):"—";const canDrill=!drillAdset;const zb=i%2===1?"var(--row-hover)":"transparent";return<tr key={r.name+i} onClick={canDrill?()=>handleRowClick(r.name):undefined} style={{borderBottom:`1px solid ${BORDER}`,cursor:canDrill?"pointer":"default",transition:"background 0.15s",background:zb}} onMouseEnter={e=>{if(canDrill)e.currentTarget.style.background="var(--gold-bg)";}} onMouseLeave={e=>{e.currentTarget.style.background=zb;}}><td style={{padding:"11px 8px",color:TEXT1,fontWeight:600,maxWidth:240,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{canDrill&&<span style={{display:"inline-block",width:8,height:8,borderRadius:"50%",background:r.spend>500?"#22C55E":r.spend>0?GOLD_HEX:"var(--border2)",marginRight:7,flexShrink:0}}/>}{r.name}{canDrill&&<span style={{fontSize:9,color:TEXT3,marginLeft:6,opacity:0.7}}>›</span>}</td><td style={{padding:"11px 8px",color:TEXT1,fontWeight:600}}>{r.leads>0?r.leads:zero}</td><td style={{padding:"11px 8px",color:"#047857",fontWeight:700}}>{r.mql>0?r.mql:zero}</td><td style={{padding:"11px 8px",color:"#1D4ED8",fontWeight:700}}>{r.sql>0?r.sql:zero}</td><td style={{padding:"11px 8px",color:TEXT2}}>{r.qualificados>0?r.qualificados:zero}</td><td style={{padding:"11px 8px",color:"#15803D",fontWeight:700}}>{r.vendas>0?r.vendas:zero}</td><td style={{padding:"11px 8px",color:TEXT2,...gSep}}>{r.leads_meta>0?r.leads_meta:zero}</td><td style={{padding:"11px 8px",color:TEXT1,fontWeight:700,fontFamily:"'JetBrains Mono',monospace",fontSize:10.5}}>{r.spend>0?fmt(Math.round(r.spend)):zero}</td><td style={{padding:"11px 8px",color:r.cash>0?"#15803D":TEXT3,fontWeight:700,...gSep}}>{r.cash>0?fmt(r.cash):zero}</td><td style={{padding:"11px 8px"}}>{r.spend>0?<span style={{padding:"3px 8px",borderRadius:5,fontSize:9,fontWeight:700,background:parseFloat(roas)>=2?"rgba(34,197,94,0.12)":parseFloat(roas)<1?"rgba(239,68,68,0.1)":"var(--bg-hover)",color:parseFloat(roas)>=2?"#15803D":parseFloat(roas)<1?"#DC2626":TEXT2}}>{roas}x</span>:<span style={{color:"var(--text3)",opacity:.35}}>—</span>}</td><td style={{padding:"11px 8px",color:TEXT2,fontSize:10}}>{cpl!=="—"?cpl:<span style={{opacity:.35}}>—</span>}</td><td style={{padding:"11px 8px"}}>{r.leads>0?<span style={{fontSize:10,fontWeight:600,color:pct(r.mql,r.leads)>=30?"#047857":TEXT2}}>{pct(r.mql,r.leads)}%</span>:<span style={{color:"var(--text3)",opacity:.35}}>—</span>}</td><td style={{padding:"11px 8px"}}>{r.leads>0?<span style={{fontSize:10,fontWeight:600,color:pct(r.qualificados,r.leads)>=30?"#15803D":TEXT2}}>{pct(r.qualificados,r.leads)}%</span>:<span style={{color:"var(--text3)",opacity:.35}}>—</span>}</td></tr>;};
return<>
{comG.length>0&&secHead("● Com investimento no período","#0F766E",comG.length)}
{comG.map(rowFor)}
{semG.length>0&&secHead("○ Sem gasto no período — orgânico, links antigos ou UTM sem correspondência","var(--text3)",semG.length)}
{semG.map(rowFor)}
</>;})()}</tbody></table></div>
{ad.length===0&&<div style={{textAlign:"center",padding:20,color:TEXT3,fontSize:11}}>Sem dados de spend nesse período</div>}
</Card>

<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:14}}>Cash Collect/{currentLevel}</h3><ResponsiveContainer width="100%" height={Math.max(ad.filter(r=>r.cash>0).length*36+40,120)}><BarChart data={ad.filter(r=>r.cash>0)} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)"/><XAxis type="number" tick={{fill:"var(--text3)",fontSize:9}} axisLine={false} tickLine={false} tickFormatter={v=>`R$${Math.round(v/1000)}k`}/><YAxis type="category" dataKey="name" tick={{fill:"var(--text2)",fontSize:9}} axisLine={false} tickLine={false} width={120}/><Tooltip contentStyle={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:8,color:TEXT1,fontSize:10}} formatter={(v)=>String(fmt(v))}/><Bar dataKey="cash" fill={GOLD_HEX} radius={[0,4,4,0]} barSize={16} name="Cash Collect"/></BarChart></ResponsiveContainer></Card>

<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:14}}>SDRs</h3><table style={{width:"100%",fontSize:11,borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${BORDER}`}}>{["SDR","Leads","Qualif.","% Qual."].map(h=><th key={h} style={{textAlign:"left",padding:"6px",fontWeight:500,color:TEXT3,fontSize:9,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{sdrs.map(s=><tr key={s.name} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"8px 6px",color:TEXT1,fontWeight:500}}>{s.name}</td><td style={{padding:"8px 6px",color:TEXT2}}>{s.leads}</td><td style={{padding:"8px 6px",color:TEXT2}}>{s.qualificados}</td><td style={{padding:"8px 6px"}}><span style={{padding:"2px 6px",borderRadius:4,fontSize:9,fontWeight:600,background:pct(s.qualificados,s.leads)>=35?"rgba(74,222,128,0.1)":GOLD_BG,color:pct(s.qualificados,s.leads)>=35?"#4ADE80":GOLD}}>{pct(s.qualificados,s.leads)}%</span></td></tr>)}</tbody></table></Card>
<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:14}}>Closers</h3><table style={{width:"100%",fontSize:11,borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${BORDER}`}}>{["Closer","Reuniões","Vendas","Cash","Fech."].map(h=><th key={h} style={{textAlign:"left",padding:"6px",fontWeight:500,color:TEXT3,fontSize:9,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{closers.map(c=><tr key={c.name} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"8px 6px",color:TEXT1,fontWeight:500}}>{c.name}</td><td style={{padding:"8px 6px",color:TEXT2}}>{c.reunioes}</td><td style={{padding:"8px 6px",color:"#4ADE80",fontWeight:500}}>{c.vendas}</td><td style={{padding:"8px 6px",color:"#4ADE80"}}>{fmt(c.cash)}</td><td style={{padding:"8px 6px"}}><span style={{padding:"2px 6px",borderRadius:4,fontSize:9,fontWeight:600,background:pct(c.vendas,c.reunioes)>=30?"rgba(74,222,128,0.1)":GOLD_BG,color:pct(c.vendas,c.reunioes)>=30?"#4ADE80":GOLD}}>{pct(c.vendas,c.reunioes)}%</span></td></tr>)}</tbody></table></Card>
</div></div>;}

function TrackingPage({eventos}){const t=eventos.length,s=eventos.filter(e=>e.sucesso).length,er=eventos.filter(e=>!e.sucesso).length;const bt=useMemo(()=>{const m={};eventos.forEach(e=>{m[e.evento]=(m[e.evento]||0)+1;});return Object.entries(m).map(([k,v])=>({name:k,value:v}));},[eventos]);const cl={Lead:GOLD,QualifiedLead:"#34D399",Schedule:"#A78BFA",Purchase:"#4ADE80"};
return<div style={{display:"flex",flexDirection:"column",gap:14}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10}}><MC icon={Zap} label="Eventos" value={t} accent/><MC icon={Check} label="Sucesso" value={`${pct(s,t)}%`}/><MC icon={AlertTriangle} label="Erros" value={er}/></div>
<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:14}}>Por tipo</h3><ResponsiveContainer width="100%" height={150}><BarChart data={bt}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)"/><XAxis dataKey="name" tick={{fill:"var(--text2)",fontSize:9}} axisLine={false} tickLine={false}/><YAxis tick={{fill:"var(--text3)",fontSize:9}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:8,color:TEXT1,fontSize:10}}/><Bar dataKey="value" radius={[4,4,0,0]} barSize={32}>{bt.map((e,i)=><Cell key={i} fill={cl[e.name]||GOLD_HEX}/>)}</Bar></BarChart></ResponsiveContainer></Card>
<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:14}}>Log</h3><table style={{width:"100%",fontSize:11,borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${BORDER}`}}>{["Evento","Plataforma","Status","Data"].map(h=><th key={h} style={{textAlign:"left",padding:"6px",fontWeight:500,color:TEXT3,fontSize:9,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{eventos.map(e=><tr key={e.id} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"8px 6px"}}><span style={{padding:"2px 8px",borderRadius:16,fontSize:9,fontWeight:500,background:`${cl[e.evento]||GOLD_HEX}15`,color:cl[e.evento]||GOLD_HEX}}>{e.evento}</span></td><td style={{padding:"8px 6px",color:TEXT2,textTransform:"capitalize"}}>{e.plataforma}</td><td style={{padding:"8px 6px"}}>{e.sucesso?<span className="flex items-center gap-1" style={{color:"#4ADE80"}}><Check size={11}/>OK</span>:<span className="flex items-center gap-1" style={{color:"#F87171"}}><X size={11}/>{e.erro}</span>}</td><td style={{padding:"8px 6px",color:TEXT3}}>{new Date(e.created_at).toLocaleString("pt-BR")}</td></tr>)}</tbody></table></Card></div>;}

function TemplatesPage({templates,loading,addTemplate,removeTemplate}){const[show,sShow]=useState(false);const[ti,sTi]=useState("");const[ms,sMs]=useState("");const[ca,sCa]=useState("outro");const cats={primeira_abordagem:"1ª abordagem",followup:"Follow-up",agendamento:"Agendamento",recontato:"Recontato",no_show:"No-show",outro:"Outro"};const IS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
const add=async()=>{if(!ti.trim()||!ms.trim())return;await addTemplate({titulo:ti,mensagem:ms,categoria:ca,ativo:true});sTi("");sMs("");sShow(false);};
return<div style={{display:"flex",flexDirection:"column",gap:14}}><div className="flex items-center justify-between"><h3 style={{fontSize:12,fontWeight:500,color:TEXT2}}>Use <code style={{color:GOLD}}>{"{{nome}}"}</code> pra nome do lead</h3><button onClick={()=>sShow(!show)} style={{display:"flex",alignItems:"center",gap:5,padding:"7px 14px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:11,fontWeight:500,cursor:"pointer"}}><Plus size={13}/>Novo</button></div>
{show&&<Card style={{padding:14}}><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:8,marginBottom:8}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Título</label><input value={ti} onChange={e=>sTi(e.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Categoria</label><select value={ca} onChange={e=>sCa(e.target.value)} style={IS}>{Object.entries(cats).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div></div><div style={{marginBottom:8}}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Mensagem</label><textarea value={ms} onChange={e=>sMs(e.target.value)} rows={3} style={{...IS,resize:"vertical"}}/></div><div className="flex gap-2"><button onClick={add} style={{padding:"8px 16px",borderRadius:8,border:"none",background:"linear-gradient(135deg,#14B8A6,#0D9488)",color:"var(--btn-text)",fontSize:12,fontWeight:600,cursor:"pointer"}}>Salvar</button><button onClick={()=>sShow(false)} style={{padding:"8px 16px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:12,cursor:"pointer"}}>Cancelar</button></div></Card>}
{loading?<Spinner/>:templates.map(t=><Card key={t.id} style={{padding:14}}><div className="flex items-center justify-between" style={{marginBottom:6}}><div className="flex items-center gap-2"><span style={{fontSize:12,fontWeight:500,color:GOLD}}>{t.titulo}</span><span style={{fontSize:8,padding:"2px 6px",borderRadius:8,background:"rgba(255,255,255,0.04)",color:TEXT3}}>{cats[t.categoria]||t.categoria}</span></div><button onClick={()=>removeTemplate(t.id)} style={{padding:5,borderRadius:5,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:"#F87171"}}><Trash2 size={11}/></button></div><div style={{fontSize:11,color:TEXT2,lineHeight:1.5}}>{t.mensagem}</div></Card>)}</div>;}

function HStep({n,title,children}){return<Card style={{padding:"18px 20px"}}><div className="flex gap-3"><div style={{width:28,height:28,borderRadius:"50%",background:"linear-gradient(135deg,#14B8A6,#0D9488)",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:800,flexShrink:0}}>{n}</div><div style={{flex:1,minWidth:0}}><h3 style={{fontSize:14,fontWeight:700,color:TEXT1,margin:"3px 0 8px"}}>{title}</h3><div style={{fontSize:12.5,color:TEXT2,lineHeight:1.7}}>{children}</div></div></div></Card>;}
function HMock({children,label}){return<div style={{margin:"10px 0",padding:14,borderRadius:10,background:BG3,border:`1px dashed ${BORDER2}`}}><div className="flex items-center gap-3 flex-wrap">{children}{label&&<span style={{fontSize:11,color:GOLD,fontWeight:700}}>👈 {label}</span>}</div></div>;}
function HKey({children}){return<span style={{padding:"1px 7px",borderRadius:5,background:"var(--bg-hover)",border:`1px solid ${BORDER}`,fontSize:11.5,fontWeight:600,color:TEXT1}}>{children}</span>;}
function HelpPage({isClinica}){
const btnNovoLead=<span style={{display:"inline-flex",alignItems:"center",gap:5,padding:"7px 14px",borderRadius:8,background:GOLD_BG2,color:GOLD,fontSize:11,fontWeight:600}}><Plus size={13}/>Novo lead</span>;
const btnZap=<span style={{display:"inline-flex",alignItems:"center",gap:5,height:30,padding:"0 12px",borderRadius:15,background:"rgba(20,184,166,0.12)",border:"1px solid rgba(45,212,191,0.35)",color:"#0D9488",fontSize:11,fontWeight:600}}><Zap size={12}/>Áudios & Rápidas</span>;
const cardMock=<span style={{display:"inline-block",padding:"9px 12px",borderRadius:9,background:BG2,border:`1px solid ${BORDER}`,boxShadow:"0 1px 3px rgba(13,60,55,0.08)",minWidth:150}}><span style={{display:"block",fontSize:12,fontWeight:600,color:TEXT1}}>Maria Souza</span><span style={{display:"block",fontSize:10,color:TEXT3,marginTop:2}}>📞 5511999998888</span></span>;
const tagMock=<span style={{padding:"4px 12px",borderRadius:12,background:"rgba(37,99,235,0.12)",border:"1px solid rgba(37,99,235,0.4)",color:"#1D4ED8",fontSize:11,fontWeight:700}}>Quer agendar</span>;
return<div style={{display:"flex",flexDirection:"column",gap:12,maxWidth:860}}>
<Card style={{padding:"18px 20px",borderColor:"var(--gold-border)"}}><h2 style={{fontSize:16,fontWeight:800,color:TEXT1,margin:0}}>Como usar o CRM {isClinica?"— Guia da Clínica":"— Guia da Mentoria"}</h2><p style={{fontSize:12,color:TEXT3,margin:"6px 0 0",lineHeight:1.6}}>Siga os passos abaixo na ordem. O mais importante de tudo está no passo {isClinica?"4":"4"}: <b style={{color:GOLD}}>mover os leads corretamente no funil</b> — é isso que alimenta o Facebook com os dados certos.</p></Card>

<HStep n={1} title="Conheça as abas do menu lateral">
<b>Dashboard</b> — resumo do dia: leads, agendamentos, receita.<br/><b>Pipeline</b> — o funil em colunas, onde você trabalha os leads (sua tela principal).<br/><b>Analytics</b> — desempenho por campanha e por atendente.<br/><b>Templates</b> — mensagens prontas para copiar.<br/><b>Config</b> — equipe, WhatsApp, etiquetas e preferências.
</HStep>

<HStep n={2} title={isClinica?"De onde vêm os leads (e como cadastrar um manualmente)":"Cadastrar um lead manualmente"}>
{isClinica?<span>Os leads dos anúncios chegam <b>sozinhos</b>: quando a pessoa clica no anúncio do Facebook e manda mensagem no WhatsApp da clínica, o lead aparece automaticamente na coluna <HKey>Novo</HKey> do Pipeline. Para pacientes que chegam por indicação ou telefone, cadastre manualmente:</span>:<span>Os leads do formulário entram sozinhos no Pipeline. Para cadastrar alguém manualmente (indicação, contato direto):</span>}
<HMock label="clique aqui, no topo do Pipeline">{btnNovoLead}</HMock>
Primeiro <b>abra o pipeline certo</b> no menu lateral (clique em Pipeline e escolha na lista). Depois clique no botão acima, preencha nome e WhatsApp (Instagram e email são opcionais) e pronto — o lead cai na coluna <HKey>Novo</HKey>.
</HStep>

<HStep n={3} title="Atender o lead pelo WhatsApp (sem sair do CRM)">
Clique em qualquer cartão do funil para abrir a ficha do lead:
<HMock label="clique no cartão">{cardMock}</HMock>
Dentro da ficha, vá na aba <HKey>Chat</HKey>. Ali você digita mensagens, grava áudio segurando o microfone, e envia mensagens e áudios prontos pelo botão:
<HMock label="mensagens e áudios prontos">{btnZap}</HMock>
<b>Responda rápido:</b> cartões com <span style={{color:"#DC2626",fontWeight:700}}>⚠ Sem contato</span> são leads novos há mais de 2h sem atendimento — eles esfriam muito rápido.
</HStep>

<HStep n={4} title="⭐ Mover o lead no funil — o passo mais importante">
Arraste o cartão de uma coluna para outra conforme a conversa evolui (segure e solte na coluna nova). Isso não é só organização: <b style={{color:GOLD}}>cada mudança de etapa envia um evento para o Facebook</b> (via Pixel/API de Conversões).<br/><br/>
O Facebook usa esses eventos para aprender <b>quem vira {isClinica?"paciente":"cliente"} de verdade</b> e mostrar os anúncios para pessoas parecidas. Na prática:<br/>
• Mover corretamente = anúncios cada vez mais baratos e leads cada vez melhores.<br/>
• Esquecer de mover (ou mover errado) = o Facebook otimiza para curiosos, e o custo por lead sobe.<br/><br/>
As etapas que disparam eventos são: <HKey>Qualificado</HKey> → <HKey>{isClinica?"Consulta Agendada":"Reunião Agendada"}</HKey> → <HKey>Fechado</HKey>. <b>Mova no momento em que acontecer de verdade</b> — e leads sem perfil vão para <HKey>Desqualificado</HKey> (isso também ensina o Facebook a evitá-los).
</HStep>

{isClinica?<HStep n={5} title="Etiquetas — classifique cada lead manualmente">
Como os leads chegam direto do WhatsApp (sem formulário), quem classifica é a atendente, usando etiquetas:
<HMock label="exemplo de etiqueta no cartão">{tagMock}</HMock>
<b>Criar etiquetas:</b> vá em <HKey>Config</HKey> → seção <b>Etiquetas de Lead</b> → escolha uma cor, digite o nome (ex.: "Quer agendar", "Urgente", "Sem perfil", "Plano de saúde") e clique em Adicionar.<br/>
<b>Marcar no lead:</b> abra a ficha do lead → aba <HKey>Dados</HKey> → clique nas etiquetas desejadas (pode marcar várias; salva sozinho).<br/>
<b>Filtrar:</b> no topo do Pipeline, use o seletor <HKey>Todas etiquetas</HKey> para ver só os leads de uma etiqueta.
</HStep>
:<HStep n={5} title="Pontuação, MQL e SQL — como o CRM qualifica sozinho">
Cada lead que preenche o formulário recebe uma <b>pontuação automática</b> (aparece como <HKey>6k</HKey>, <HKey>12k</HKey>... no cartão).<br/>
• <b style={{color:"#047857"}}>MQL</b> — pontuação acima do mínimo definido em <HKey>Config</HKey> → Pontuação MQL. Automático.<br/>
• <b style={{color:"#1D4ED8"}}>SQL</b> — você arrastou o lead para <HKey>Qualificado</HKey> ou além. Manual.<br/>
Dentro da ficha, use a aba <HKey>BANT</HKey> para registrar Budget, Autoridade, Necessidade e Urgência na conversa de qualificação — e a aba <HKey>Respostas</HKey> mostra tudo que o lead preencheu no formulário. Você também pode usar <b>etiquetas</b> (Config → Etiquetas de Lead) para marcações extras.
</HStep>}

<HStep n={6} title={isClinica?"Registrar fechamento (valor do tratamento)":"Registrar a venda"}>
Quando {isClinica?"o paciente fechar o tratamento":"a venda acontecer"}: abra a ficha → aba <HKey>Dados</HKey> → preencha <HKey>Valor</HKey> e <HKey>Cash Collect</HKey> (quanto entrou de fato) → arraste o cartão para <HKey>Fechado</HKey>. Esses valores alimentam o Dashboard, o Analytics e o evento de compra enviado ao Facebook.
</HStep>

<HStep n={7} title="Conectar o WhatsApp da equipe">
Em <HKey>Config</HKey> → seção <b>WhatsApp da Equipe</b> → clique em <HKey>Conectar</HKey> ao lado do atendente → abra o WhatsApp no celular dele → <b>Aparelhos conectados</b> → <b>Conectar aparelho</b> → escaneie o QR code que aparece na tela. Depois disso, todas as conversas aparecem dentro do CRM.
</HStep>

<Card style={{padding:"16px 20px",background:"var(--gold-bg)",borderColor:"var(--gold-border)"}}><div style={{fontSize:12.5,color:TEXT2,lineHeight:1.7}}><b style={{color:GOLD}}>Resumo de ouro:</b> responda em minutos, converse pelo Chat do CRM, {isClinica?"etiquete cada lead":"acompanhe a pontuação"} e <b>mova o cartão na hora certa</b>. Funil atualizado = Facebook aprendendo com dados reais = mais {isClinica?"pacientes":"clientes"} pagando menos por lead.</div></Card>
</div>;}

function AdminNovoCliente({showToast}){
const[nome,sNome]=useState("");const[tipo,sTipo]=useState("clinica");const[userId,sUserId]=useState("");const[adAcc,sAdAcc]=useState("");const[pixel,sPixel]=useState("");const[token,sToken]=useState("");const[saving,sSaving]=useState(false);const[done,sDone]=useState(null);
const criar=async()=>{if(!nome.trim()||saving)return;sSaving(true);sDone(null);
const slug=nome.trim().toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g,"").replace(/\s+/g,"-").replace(/[^a-z0-9-]/g,"");
const{data:cli,error}=await supabase.from("crm_clientes").insert({nome:nome.trim(),slug,tipo}).select();
if(error||!cli?.[0]){showToast("Erro ao criar cliente: "+(error?.message||"?"),"error");sSaving(false);return;}
const ncid=cli[0].id;
await supabase.from("crm_config").insert({cliente_id:ncid,nome_negocio:nome.trim(),ativo:true,meta_ad_account_id:adAcc.trim().replace(/^act_/,"")||null,meta_pixel_id:pixel.trim()||null,meta_access_token:token.trim()||null});
const{data:pip}=await supabase.from("crm_pipelines").insert({nome:tipo==="clinica"?"Atendimento":"Vendas",cliente_id:ncid}).select();
if(pip?.[0]){const st=tipo==="clinica"
?[["novo","Novo","#0D9488"],["contato_iniciado","Em Conversa","#60A5FA"],["qualificado","Qualificado","#34D399"],["reuniao_agendada","Consulta Agendada","#A78BFA"],["reuniao_realizada","Consulta Realizada","#818CF8"],["no_show","No Show","#FBBF24"],["proposta_enviada","Orçamento Enviado","#22D3EE"],["fechado","Fechado","#4ADE80"],["desqualificado","Desqualificado","#F87171"]]
:[["novo","Novo","#0D9488"],["contato_iniciado","Contato Iniciado","#60A5FA"],["conversando","Conversando","#38BDF8"],["qualificado","Qualificado","#34D399"],["reuniao_agendada","Reunião Agendada","#A78BFA"],["reuniao_realizada","Reunião Realizada","#818CF8"],["no_show","No Show","#FBBF24"],["proposta_enviada","Proposta Enviada","#22D3EE"],["fechado","Fechado","#4ADE80"],["desqualificado","Desqualificado","#F87171"]];
await supabase.from("crm_pipeline_stages").insert(st.map((s,i)=>({pipeline_id:pip[0].id,key:s[0],label:s[1],color:s[2],ordem:i})));}
if(tipo==="clinica")await supabase.from("crm_etiquetas").insert([{cliente_id:ncid,nome:"Quer agendar",cor:"#2563EB"},{cliente_id:ncid,nome:"Urgente",cor:"#DC2626"},{cliente_id:ncid,nome:"Sem perfil",cor:"#64748B"}]);
if(userId.trim()){const{error:ue}=await supabase.from("crm_usuarios").insert({user_id:userId.trim(),cliente_id:ncid});if(ue)showToast("Cliente criado, mas falhou ao vincular usuário: "+ue.message,"error");}
sSaving(false);sDone(nome.trim());sNome("");sUserId("");sAdAcc("");sPixel("");sToken("");showToast("Cliente criado com sucesso!","success");};
const IS2={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
return<Card style={{padding:20,borderColor:"var(--gold-border)",maxWidth:640}}><h3 style={{fontSize:13,fontWeight:700,color:GOLD,margin:0}}>⚙ Novo Cliente</h3><p style={{fontSize:10,color:TEXT3,margin:"3px 0 16px"}}>Cria o cliente completo: config com integração Meta, pipeline com etapas prontas e etiquetas padrão (clínica).</p>
<div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:10,marginBottom:10}}>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Nome do cliente</label><input value={nome} onChange={e=>sNome(e.target.value)} placeholder="Clínica Sorriso" style={IS2}/></div>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Tipo</label><select value={tipo} onChange={e=>sTipo(e.target.value)} style={IS2}><option value="clinica">Clínica</option><option value="mentoria">Mentoria</option></select></div>
</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:10}}>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>ID da conta de anúncios</label><input value={adAcc} onChange={e=>sAdAcc(e.target.value)} placeholder="act_1234567890 ou só números" style={IS2}/></div>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Pixel ID</label><input value={pixel} onChange={e=>sPixel(e.target.value)} placeholder="793889205448418" style={IS2}/></div>
</div>
<div style={{marginBottom:10}}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Token de acesso Meta</label><input value={token} onChange={e=>sToken(e.target.value)} placeholder="EAAN... (token de sistema com acesso à conta de anúncios e ao pixel)" style={IS2}/></div>
<div style={{marginBottom:12}}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>User ID do login (opcional)</label><input value={userId} onChange={e=>sUserId(e.target.value)} placeholder="Crie o usuário em Supabase → Authentication → Add user e cole o UUID aqui" style={IS2}/></div>
<button onClick={criar} disabled={saving||!nome.trim()} style={{padding:"9px 20px",borderRadius:8,border:"none",background:"linear-gradient(135deg,#14B8A6,#0D9488)",color:"#fff",fontSize:12,fontWeight:700,cursor:"pointer",opacity:saving||!nome.trim()?0.5:1}}>{saving?"Criando...":"Criar cliente"}</button>
{done&&<div style={{marginTop:10,fontSize:11,color:TEXT2,lineHeight:1.6}}>✅ <b>{done}</b> criado. Próximos passos: {!userId&&<span>criar o login em <b>Supabase → Authentication → Add user</b> e vincular o UUID aqui; </span>}logar como o cliente e conectar o WhatsApp em Config → WhatsApp da Equipe.</div>}
</Card>;}

function ConfigPage({equipe,eqLoading,addMember,removeMember,toggleActive,updateDist,config,theme,toggleTheme,pipeHook,etiquetasHook,isClinica,showConfirm,showToast,isAdmin}){const[tagName,sTagName]=useState("");const[tagColor,sTagColor]=useState("#0D9488");const[show,sShow]=useState(false);const[fn,sFn]=useState("");const[fp,sFp]=useState("sdr");const[ft,sFt]=useState("");const[fe,sFe]=useState("");const[fc,sFc]=useState(TEAM_COLORS[0]);const[connectingId,sConnectingId]=useState(null);const[qrImg,sQrImg]=useState(null);const[qrLoading,sQrLoading]=useState(false);const IS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
const wahaManage=async(action,session)=>{const r=await fetch("https://n8n-production-2afe.up.railway.app/webhook/waha-manage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,session})});return r.json();};
const connectWha=async(member)=>{const session=member.nome.toLowerCase().replace(/\s+/g,"-").replace(/[^a-z0-9-]/g,"");sConnectingId(member.id);sQrLoading(true);sQrImg(null);
try{await wahaManage("stop",session);}catch{}
await wahaManage("start",session);
await supabase.from("crm_equipe").update({waha_session:session}).eq("id",member.id);
let attempts=0;const waitQr=async()=>{while(attempts<10){await new Promise(r=>setTimeout(r,2000));attempts++;const st=await wahaManage("status",session);if(st?.status==="SCAN_QR_CODE"){sQrImg(`https://waha-production-f856.up.railway.app/api/${session}/auth/qr?x-api-key=crmx-waha-2026&t=${Date.now()}`);sQrLoading(false);break;}if(st?.status==="WORKING"){sQrLoading(false);sConnectingId(null);const phone=st.me?.id?.replace("@c.us","")||"";await supabase.from("crm_equipe").update({waha_connected:true,waha_phone:phone}).eq("id",member.id);window.location.reload();return;}}if(attempts>=10){sQrLoading(false);sConnectingId(null);}};await waitQr();
const poll=setInterval(async()=>{const st=await wahaManage("status",session);if(st?.status==="WORKING"&&st?.me?.id){const phone=st.me.id.replace("@c.us","");await supabase.from("crm_equipe").update({waha_connected:true,waha_phone:phone}).eq("id",member.id);clearInterval(poll);sConnectingId(null);sQrImg(null);window.location.reload();}if(st?.status==="FAILED"){sQrImg(null);sConnectingId(null);sQrLoading(false);clearInterval(poll);}},4000);setTimeout(()=>{clearInterval(poll);sConnectingId(null);sQrImg(null);sQrLoading(false);},120000);};
const disconnectWha=async(member)=>{if(!member.waha_session)return;await wahaManage("stop",member.waha_session);await supabase.from("crm_equipe").update({waha_session:null,waha_connected:false,waha_phone:null}).eq("id",member.id);window.location.reload();};
const add=async()=>{if(!fn.trim())return;await addMember({nome:fn,papel:fp,telefone:ft,email:fe,cor:fc,ativo:true});sFn("");sFt("");sFe("");sShow(false);};
return<div style={{display:"flex",flexDirection:"column",gap:14}}>
<Card style={{padding:20}}><div className="flex items-center justify-between"><div><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,margin:0}}>Tema</h3><p style={{fontSize:10,color:TEXT3,marginTop:3}}>Aparência da interface</p></div><button onClick={toggleTheme} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 16px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:12,fontWeight:500,cursor:"pointer"}}>{theme==="dark"?<><Sun size={14} style={{color:"#FBBF24"}}/>Modo Claro</>:<><Moon size={14} style={{color:"#818CF8"}}/>Modo Escuro</>}</button></div></Card>
<Card style={{padding:20}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:16}}>Pixel & Meta</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,maxWidth:560}}>{[{l:"Pixel ID",v:config?.meta_pixel_id||"—"},{l:"Token",v:config?.meta_access_token?"••••••••":"—"},{l:"Test Code",v:config?.meta_test_event_code||"Produção"},{l:"Domínio",v:config?.dominio||"—"},{l:"Meta Mensal",v:config?.meta_mensal?fmt(config.meta_mensal):"—"},{l:"Gasto Ads",v:config?.gasto_ads_mensal?fmt(config.gasto_ads_mensal):"—"}].map(f=><div key={f.l}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>{f.l}</label><div style={{padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,fontSize:12,color:TEXT2}}>{f.v}</div></div>)}</div></Card>
<Card style={{padding:20}}><div className="flex items-center justify-between" style={{marginBottom:16}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,margin:0}}>Equipe</h3><button onClick={()=>sShow(!show)} style={{display:"flex",alignItems:"center",gap:5,padding:"7px 14px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:11,fontWeight:500,cursor:"pointer"}}><Plus size={13}/>Adicionar</button></div>
{show&&<div style={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:10,padding:14,marginBottom:14}}><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:8,marginBottom:8}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Nome</label><input value={fn} onChange={e=>sFn(e.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Papel</label><select value={fp} onChange={e=>sFp(e.target.value)} style={IS}><option value="sdr">SDR</option><option value="closer">Closer</option></select></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:8}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Telefone</label><input value={ft} onChange={e=>sFt(e.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Email</label><input value={fe} onChange={e=>sFe(e.target.value)} style={IS}/></div></div><div style={{marginBottom:10}}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Cor</label><div className="flex gap-2">{TEAM_COLORS.map(c=><div key={c} onClick={()=>sFc(c)} style={{width:24,height:24,borderRadius:5,background:c,cursor:"pointer",border:fc===c?`2px solid ${TEXT1}`:"2px solid transparent"}}/>)}</div></div><div className="flex gap-2"><button onClick={add} style={{padding:"7px 16px",borderRadius:8,border:"none",background:"linear-gradient(135deg,#14B8A6,#0D9488)",color:"var(--btn-text)",fontSize:12,fontWeight:600,cursor:"pointer"}}>Salvar</button><button onClick={()=>sShow(false)} style={{padding:"7px 16px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:12,cursor:"pointer"}}>Cancelar</button></div></div>}
{eqLoading?<Spinner/>:["sdr","closer"].map(papel=>{const members=equipe.filter(m=>m.papel===papel);return<div key={papel} style={{marginBottom:16}}><div className="flex items-center gap-2" style={{marginBottom:8}}>{papel==="sdr"?<Phone size={13} style={{color:GOLD}}/>:<Award size={13} style={{color:GOLD}}/>}<span style={{fontSize:11,fontWeight:600,color:GOLD,textTransform:"uppercase"}}>{papel==="sdr"?"SDRs":"Closers"}</span><span style={{fontSize:9,color:TEXT3}}>({members.length})</span></div>{members.length===0&&<div style={{fontSize:11,color:TEXT3,padding:"8px 0"}}>Nenhum</div>}{members.map(m=><div key={m.id} className="flex items-center justify-between" style={{padding:"8px 10px",borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:5,opacity:m.ativo?1:.5}}><div className="flex items-center gap-3"><div style={{width:30,height:30,borderRadius:"50%",background:`${m.cor||GOLD_HEX}22`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:600,color:m.cor||GOLD_HEX,border:`2px solid ${m.cor||GOLD_HEX}`}}>{m.nome.split(" ").map(n=>n[0]).join("").slice(0,2)}</div><div><div style={{fontSize:12,fontWeight:500,color:TEXT1}}>{m.nome}</div><div style={{fontSize:9,color:TEXT3}}>{m.telefone||""}{m.email?` • ${m.email}`:""}</div></div></div><div className="flex items-center gap-1"><button onClick={()=>toggleActive(m.id,m.ativo)} style={{padding:5,borderRadius:5,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:m.ativo?"#4ADE80":TEXT3}}>{m.ativo?<Eye size={13}/>:<EyeOff size={13}/>}</button><button onClick={()=>removeMember(m.id)} style={{padding:5,borderRadius:5,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:"#F87171"}}><Trash2 size={13}/></button></div></div>)}</div>;})}
</Card>
<Card style={{padding:20}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,margin:0}}>Etiquetas de Lead</h3><p style={{fontSize:10,color:TEXT3,margin:"3px 0 14px"}}>Classificação manual dos leads — aparecem no card e no filtro do pipeline</p>
<div className="flex items-center gap-2 flex-wrap" style={{marginBottom:12}}><div className="flex gap-1.5">{["#0D9488","#2563EB","#7C3AED","#DB2777","#DC2626","#EA580C","#CA8A04","#16A34A","#64748B"].map(c=><div key={c} onClick={()=>sTagColor(c)} style={{width:22,height:22,borderRadius:6,background:c,cursor:"pointer",border:tagColor===c?`2px solid ${TEXT1}`:"2px solid transparent"}}/>)}</div><input value={tagName} onChange={e=>sTagName(e.target.value)} placeholder="Nova etiqueta..." onKeyDown={async e=>{if(e.key==="Enter"&&tagName.trim()){await etiquetasHook.addTag(tagName.trim(),tagColor);sTagName("");}}} style={{flex:"1 1 160px",maxWidth:240,padding:"7px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:12,outline:"none"}}/><button onClick={async()=>{if(!tagName.trim())return;await etiquetasHook.addTag(tagName.trim(),tagColor);sTagName("");}} style={{padding:"7px 14px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:11,fontWeight:600,cursor:"pointer"}}>Adicionar</button></div>
<div className="flex gap-2 flex-wrap">{etiquetasHook.tags.length===0&&<span style={{fontSize:11,color:TEXT3}}>Nenhuma etiqueta criada ainda.</span>}{etiquetasHook.tags.map(t=><span key={t.id} className="flex items-center gap-2" style={{padding:"6px 8px 6px 14px",borderRadius:16,border:`1.5px solid ${t.cor}66`,background:`${t.cor}18`,color:t.cor,fontSize:12,fontWeight:600}}>{t.nome}<button onClick={async()=>{const ok=await showConfirm("Remover etiqueta",`A etiqueta "${t.nome}" será removida de todos os leads e filtros.`,true);if(ok)etiquetasHook.removeTag(t.id);}} style={{border:"none",background:"transparent",color:t.cor,cursor:"pointer",fontSize:11,padding:0,opacity:.7}}>✕</button></span>)}</div></Card>
{!isClinica&&<Card style={{padding:20}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:16}}>Pontuação MQL</h3>
<div className="flex items-center gap-3" style={{padding:"10px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3}}>
<div style={{flex:1}}><div style={{fontSize:12,fontWeight:500,color:TEXT1}}>Score mínimo para MQL</div><div style={{fontSize:9,color:TEXT3}}>Leads com score do Respondi acima desse valor são classificados automaticamente como MQL</div></div>
<div className="flex items-center gap-2"><input type="number" value={config?.mql_threshold||0} onChange={async e=>{const v=parseInt(e.target.value)||0;await supabase.from("crm_config").update({mql_threshold:v}).eq("cliente_id",config?.cliente_id);}} style={{width:80,padding:"6px 10px",borderRadius:6,border:`1px solid ${BORDER}`,background:BG,color:GOLD_HEX,fontSize:14,fontWeight:600,textAlign:"center",outline:"none",fontFamily:"'JetBrains Mono',monospace"}}/></div>
</div>
<div style={{marginTop:8,fontSize:9,color:TEXT3}}>🟢 MQL = score ≥ threshold (automático) &nbsp;•&nbsp; 🔵 SQL = arrastou pra "Qualificado" (manual)</div>
</Card>}

<Card style={{padding:20}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:16}}>WhatsApp da Equipe</h3>
{equipe.filter(m=>m.ativo).map(m=><div key={m.id} className="flex items-center gap-3" style={{padding:"10px 12px",borderRadius:8,border:`1px solid ${m.waha_connected?"rgba(52,211,153,0.2)":BORDER}`,marginBottom:6,background:BG3}}>
<div style={{width:28,height:28,borderRadius:"50%",background:`${m.cor||GOLD_HEX}22`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:600,color:m.cor||GOLD_HEX,border:`2px solid ${m.cor||GOLD_HEX}`,flexShrink:0}}>{m.nome.split(" ").map(n=>n[0]).join("").slice(0,2)}</div>
<div style={{flex:1}}><div style={{fontSize:12,fontWeight:500,color:TEXT1}}>{m.nome}</div><div style={{fontSize:9,color:m.waha_connected?"#34D399":TEXT3}}>{m.waha_connected?`Conectado • ${m.waha_phone||""}`:"Desconectado"}</div></div>
{m.waha_connected?<button onClick={()=>disconnectWha(m)} style={{padding:"5px 10px",borderRadius:6,border:`1px solid ${BORDER}`,background:"transparent",color:"#F87171",fontSize:10,cursor:"pointer"}}>Desconectar</button>
:connectingId===m.id?<span style={{fontSize:9,color:GOLD}}>Aguardando QR...</span>
:<button onClick={()=>connectWha(m)} style={{padding:"5px 10px",borderRadius:6,border:"none",background:GOLD_BG2,color:GOLD,fontSize:10,fontWeight:500,cursor:"pointer"}}>Conectar</button>}
</div>)}
{connectingId&&qrImg&&<div style={{marginTop:10,textAlign:"center",padding:16,borderRadius:10,background:BG3,border:`1px solid ${BORDER}`}}>
<p style={{fontSize:11,color:TEXT2,marginBottom:10}}>Escaneie o QR Code com o WhatsApp do SDR</p>
<img src={qrImg} alt="QR Code" style={{width:220,height:220,borderRadius:8,background:"#fff",padding:8}}/>
<p style={{fontSize:9,color:TEXT3,marginTop:8}}>O QR expira em 2 minutos</p>
</div>}
{connectingId&&qrLoading&&!qrImg&&<div style={{marginTop:10,textAlign:"center",padding:20}}><Loader2 size={18} style={{color:GOLD_HEX,animation:"spin 1s linear infinite"}}/><p style={{fontSize:10,color:TEXT3,marginTop:6}}>Gerando QR Code...</p></div>}
</Card>

<Card style={{padding:20}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:16}}>Distribuição de Leads</h3>{(()=>{const sdrsAtivos=equipe.filter(m=>m.papel==="sdr"&&m.ativo);const totalPct=sdrsAtivos.reduce((s,m)=>s+(m.distribuicao_pct||0),0);if(sdrsAtivos.length===0)return<div style={{fontSize:12,color:TEXT3,textAlign:"center",padding:16}}>Nenhum SDR ativo</div>;return<div><div style={{marginBottom:12}}>{sdrsAtivos.map(m=><div key={m.id} className="flex items-center gap-3" style={{padding:"10px 12px",borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:6,background:BG3}}><div style={{width:28,height:28,borderRadius:"50%",background:`${m.cor||GOLD_HEX}22`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:600,color:m.cor||GOLD_HEX,border:`2px solid ${m.cor||GOLD_HEX}`,flexShrink:0}}>{m.nome.split(" ").map(n=>n[0]).join("").slice(0,2)}</div><div style={{flex:1,fontSize:12,fontWeight:500,color:TEXT1}}>{m.nome}</div><div className="flex items-center gap-2"><input type="range" min="0" max="100" step="5" value={m.distribuicao_pct||0} onChange={e=>updateDist(m.id,parseInt(e.target.value))} style={{width:100,accentColor:GOLD_HEX}}/><div style={{width:40,textAlign:"right",fontSize:13,fontWeight:600,color:GOLD_HEX}}>{m.distribuicao_pct||0}%</div></div></div>)}</div><div className="flex items-center justify-between" style={{padding:"10px 12px",borderRadius:8,background:totalPct===100?"rgba(52,211,153,0.08)":"rgba(248,113,113,0.08)",border:`1px solid ${totalPct===100?"rgba(52,211,153,0.2)":"rgba(248,113,113,0.2)"}`}}><span style={{fontSize:11,fontWeight:500,color:totalPct===100?"#34D399":"#F87171"}}>Total: {totalPct}%</span><span style={{fontSize:10,color:TEXT3}}>{totalPct===100?"Distribuição válida":"Ajuste para totalizar 100%"}</span></div></div>;})()}</Card>
</div>;}



export { DashboardPage, PipelinesModal, CRMPage, AnalyticsPage, TrackingPage, TemplatesPage, HStep, HMock, HKey, HelpPage, AdminNovoCliente, ConfigPage };
