import { useState, useEffect, useCallback } from "react";
import { Phone, X, Check, Zap, Plus, Trash2, Loader2, Clock, Copy, Mic } from "lucide-react";
import { supabase } from "../lib/supabase";
import { GOLD, TEXT1, GOLD_HEX, EASE, THEME_CSS, BANT_ITEMS, fmt, timeAgo, isInactive, bantBadge, WA, GOLD_LIGHT, GOLD_BG, GOLD_BG2, BG2, BG3, BORDER, BORDER2, TEXT2, TEXT3 } from "../lib/constants";
import { useAtividades, useMessages } from "../lib/hooks";

// ===== UI =====
function CrmDialog({dialog,setDialog}){if(!dialog)return null;const[val,sVal]=useState(dialog.value||"");
return<div style={{position:"fixed",inset:0,zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:16,background:"var(--overlay)",backdropFilter:"blur(12px)",WebkitBackdropFilter:"blur(12px)",animation:`fadeIn 150ms ${EASE}`}} onClick={()=>{dialog.onCancel?.();setDialog(null);}}>
<div onClick={e=>e.stopPropagation()} style={{width:"100%",maxWidth:380,background:BG2,border:`1px solid ${BORDER2}`,borderRadius:16,padding:24,boxShadow:"0 8px 40px rgba(0,0,0,0.4)",animation:`modalIn 250ms ${EASE}`}}>
<h3 style={{fontSize:14,fontWeight:600,color:TEXT1,margin:"0 0 16px"}}>{dialog.title}</h3>
{dialog.type==="prompt"&&<input autoFocus value={val} onChange={e=>sVal(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&val.trim()){dialog.onOk?.(val.trim());setDialog(null);}if(e.key==="Escape"){dialog.onCancel?.();setDialog(null);}}} style={{width:"100%",padding:"12px 14px",borderRadius:10,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none",boxSizing:"border-box",marginBottom:16,transition:`border-color 200ms ${EASE}`}} onFocus={e=>e.target.style.borderColor="rgba(13,148,136,0.4)"} onBlur={e=>e.target.style.borderColor="rgba(113,132,127,0.12)"}/>}
{dialog.type==="confirm"&&<p style={{fontSize:12,color:TEXT2,margin:"0 0 20px",lineHeight:1.5}}>{dialog.message||"Essa ação não pode ser desfeita."}</p>}
<div className="flex gap-2" style={{justifyContent:"flex-end"}}><button onClick={()=>{dialog.onCancel?.();setDialog(null);}} className="btn-ghost" style={{padding:"9px 18px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:12,fontWeight:500,cursor:"pointer"}}>Cancelar</button>
<button onClick={()=>{dialog.onOk?.(dialog.type==="prompt"?val.trim():true);setDialog(null);}} className="btn-primary" style={{padding:"9px 18px",borderRadius:8,border:"none",background:dialog.type==="confirm"&&dialog.danger?"linear-gradient(135deg,#F87171,#DC2626)":"linear-gradient(135deg,#14B8A6,#0D9488)",color:dialog.type==="confirm"&&dialog.danger?"#fff":"#FFFFFF",fontSize:12,fontWeight:600,cursor:"pointer"}}>{dialog.okLabel||"Confirmar"}</button></div>
</div></div>;}

function Toast({toasts}){return<div style={{position:"fixed",bottom:20,right:20,zIndex:300,display:"flex",flexDirection:"column",gap:8}}>{toasts.map(t=><div key={t.id} style={{padding:"12px 18px",borderRadius:12,background:t.type==="error"?"rgba(248,113,113,0.12)":t.type==="success"?"rgba(52,211,153,0.12)":"rgba(13,148,136,0.12)",border:`1px solid ${t.type==="error"?"rgba(248,113,113,0.25)":t.type==="success"?"rgba(52,211,153,0.25)":"rgba(13,148,136,0.25)"}`,color:t.type==="error"?"#F87171":t.type==="success"?"#34D399":GOLD_HEX,fontSize:12,fontWeight:500,backdropFilter:"blur(12px)",WebkitBackdropFilter:"blur(12px)",boxShadow:"0 4px 20px rgba(0,0,0,0.2)",animation:`toastIn 300ms ${EASE}`,maxWidth:340,display:"flex",alignItems:"center",gap:10}}>{t.message}{t.action&&<button onClick={t.action.fn} style={{padding:"5px 12px",borderRadius:6,border:"none",background:BG2,color:TEXT1,fontSize:11,fontWeight:800,cursor:"pointer",flexShrink:0,boxShadow:"0 1px 4px rgba(0,0,0,0.15)"}}>{t.action.label}</button>}</div>)}</div>;}
function LoginPage({onLogin}){const[email,setEmail]=useState("");const[pw,setPw]=useState("");const[err,setErr]=useState(null);const[loading,setLoading]=useState(false);
const handle=async(e)=>{e.preventDefault();setLoading(true);setErr(null);const error=await onLogin(email,pw);if(error)setErr(error.message==="Invalid login credentials"?"Email ou senha incorretos":error.message);setLoading(false);};
return<div data-theme="light" style={{minHeight:"100vh",background:"radial-gradient(ellipse at 50% 40%, #DCEEEB 0%, #F4F8F7 70%)",display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Inter',system-ui,sans-serif"}}><style>{THEME_CSS}{`@keyframes spin{to{transform:rotate(360deg)}}@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}@keyframes logoGlow{0%,100%{filter:drop-shadow(0 0 8px rgba(13,148,136,0.15))}50%{filter:drop-shadow(0 0 20px rgba(13,148,136,0.3))}}`}</style><div style={{width:"100%",maxWidth:380,padding:32,background:"rgba(255,255,255,0.8)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",borderRadius:20,border:"1px solid rgba(13,60,55,0.1)",boxShadow:"0 8px 40px rgba(13,60,55,0.12)",animation:"fadeIn 500ms cubic-bezier(0.16,1,0.3,1)"}}>
<div style={{textAlign:"center",marginBottom:32}}><div style={{display:"inline-flex",alignItems:"center",gap:1,animation:"logoGlow 3s ease-in-out infinite"}}><span style={{fontWeight:800,fontSize:36,background:"linear-gradient(135deg,#122A27,#3E5551)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>CRM</span><span style={{fontWeight:800,fontSize:36,background:"linear-gradient(135deg,#14B8A6,#0D9488)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>X</span></div></div>
<form onSubmit={handle}><div style={{marginBottom:12}}><label style={{fontSize:9,color:"#71847F",textTransform:"uppercase",display:"block",marginBottom:4,letterSpacing:"0.05em"}}>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required style={{width:"100%",padding:"12px 14px",borderRadius:10,border:"1px solid rgba(13,60,55,0.14)",background:"#FFFFFF",color:"#122A27",fontSize:13,outline:"none",boxSizing:"border-box",transition:`border-color 200ms ${EASE}`}} onFocus={e=>e.target.style.borderColor="rgba(13,148,136,0.5)"} onBlur={e=>e.target.style.borderColor="rgba(13,60,55,0.14)"}/></div>
<div style={{marginBottom:16}}><label style={{fontSize:9,color:"#71847F",textTransform:"uppercase",display:"block",marginBottom:4,letterSpacing:"0.05em"}}>Senha</label><input type="password" value={pw} onChange={e=>setPw(e.target.value)} required style={{width:"100%",padding:"12px 14px",borderRadius:10,border:"1px solid rgba(13,60,55,0.14)",background:"#FFFFFF",color:"#122A27",fontSize:13,outline:"none",boxSizing:"border-box",transition:`border-color 200ms ${EASE}`}} onFocus={e=>e.target.style.borderColor="rgba(13,148,136,0.5)"} onBlur={e=>e.target.style.borderColor="rgba(13,60,55,0.14)"}/></div>
{err&&<div style={{padding:10,borderRadius:10,background:"rgba(220,38,38,0.06)",border:"1px solid rgba(220,38,38,0.2)",color:"#DC2626",fontSize:12,marginBottom:12,animation:`fadeIn 200ms ${EASE}`}}>{err}</div>}
<button type="submit" disabled={loading} className="btn-primary" style={{width:"100%",padding:13,borderRadius:10,border:"none",background:"linear-gradient(135deg,#14B8A6,#0D9488)",color:"#FFFFFF",fontSize:14,fontWeight:700,cursor:"pointer",opacity:loading?0.6:1,letterSpacing:"0.02em"}}>{loading?"Entrando...":"Entrar"}</button></form></div></div>;}

function Card({children,style={},glow}){return<div className="card-hover" style={{background:BG2,border:`1px solid ${BORDER}`,borderRadius:16,transition:`all 250ms ${EASE}`,...(glow?{borderColor:"var(--gold-border)",boxShadow:"0 0 12px rgba(13,148,136,0.08)"}:{}),...style}}>{children}</div>;}
function Spinner(){return<div className="flex items-center justify-center p-12 fade-in"><Loader2 size={24} style={{color:GOLD_HEX,animation:"spin 1s linear infinite"}}/></div>;}
function Skeleton({w,h,r}){return<div className="skeleton" style={{width:w||"100%",height:h||16,borderRadius:r||8}}/>;}
function Logo(){return<div style={{display:"flex",alignItems:"center",gap:1,userSelect:"none"}}><span style={{fontWeight:800,fontSize:22,background:"linear-gradient(135deg,var(--text1),var(--text2))",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>CRM</span><span style={{fontWeight:800,fontSize:22,background:"linear-gradient(135deg,var(--gold-light),var(--gold))",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>X</span></div>;}
function MC({icon:I,label,value,sub,accent}){return<Card style={{padding:14}} glow={accent}><div className="flex items-center gap-2" style={{marginBottom:6}}><div className="flex items-center justify-center" style={{width:30,height:30,borderRadius:10,background:accent?"rgba(13,148,136,0.12)":"rgba(113,132,127,0.06)",transition:`all 250ms ${EASE}`}}><I size={14} style={{color:accent?GOLD_HEX:"var(--text3)"}}/></div><span style={{fontSize:10,color:TEXT3,letterSpacing:"0.04em",textTransform:"uppercase"}}>{label}</span></div><div style={{fontSize:20,fontWeight:700,color:accent?GOLD_HEX:TEXT1,fontFamily:typeof value==="string"&&value.includes("R$")?"'JetBrains Mono',monospace":"inherit"}}>{value}</div>{sub&&<div style={{fontSize:10,color:TEXT3,marginTop:3}}>{sub}</div>}</Card>;}

function LeadCard({lead,onClick,equipe,mqlThreshold,qualStages,etiquetas,isClinica,unreadCount}){
const isMql=mqlThreshold>0&&lead.lead_score>=mqlThreshold;const isSql=qualStages&&qualStages.includes(lead.stage);
const sdr=equipe.find(m=>m.nome===lead.sdr_nome);const closer=equipe.find(m=>m.nome===lead.closer_nome);const ina=isInactive(lead);
return<div draggable onDragStart={e=>e.dataTransfer.setData("leadId",lead.id)} onClick={()=>onClick?.(lead)} style={{background:BG2,border:`1px solid ${ina?"rgba(239,68,68,0.45)":BORDER}`,borderRadius:10,padding:"11px 12px",marginBottom:8,cursor:"grab",boxShadow:"0 1px 3px rgba(13,60,55,0.07)",transition:`all 250ms ${EASE}`,animation:ina?"pulse 2s infinite":"none"}} onMouseEnter={e=>{e.currentTarget.style.borderColor=ina?"rgba(239,68,68,0.45)":"var(--gold-border)";e.currentTarget.style.transform="translateY(-2px)";e.currentTarget.style.boxShadow="0 5px 16px rgba(13,60,55,0.14)";}} onMouseLeave={e=>{e.currentTarget.style.borderColor=ina?"rgba(239,68,68,0.45)":"var(--border)";e.currentTarget.style.transform="translateY(0)";e.currentTarget.style.boxShadow="0 1px 3px rgba(13,60,55,0.07)";}}>
<div className="flex items-start justify-between gap-2" style={{marginBottom:7}}><span style={{fontSize:13,fontWeight:600,color:TEXT1,lineHeight:1.3,overflow:"hidden",textOverflow:"ellipsis",display:"-webkit-box",WebkitLineClamp:1,WebkitBoxOrient:"vertical"}}>{lead.nome}</span>
<div className="flex items-center gap-1" style={{flexShrink:0}}>{!isClinica&&lead.lead_score>=1000&&<span style={{fontSize:9,fontWeight:700,padding:"2px 6px",borderRadius:5,background:lead.lead_score>=10000?"rgba(22,163,74,0.12)":"rgba(13,148,136,0.12)",color:lead.lead_score>=10000?"#15803D":"#0F766E"}}>{Math.round(lead.lead_score/1000)}k</span>}{isSql?<span style={{fontSize:8,fontWeight:800,padding:"2px 6px",borderRadius:5,background:"rgba(37,99,235,0.12)",color:"#1D4ED8",letterSpacing:"0.05em"}}>SQL</span>:(isMql&&!isClinica)?<span style={{fontSize:8,fontWeight:800,padding:"2px 6px",borderRadius:5,background:"rgba(5,150,105,0.12)",color:"#047857",letterSpacing:"0.05em"}}>MQL</span>:null}{lead.utm_source==="meta"&&<span style={{width:15,height:15,borderRadius:4,background:"rgba(37,99,235,0.12)",display:"inline-flex",alignItems:"center",justifyContent:"center",fontSize:8,fontWeight:800,color:"#1D4ED8"}}>M</span>}{lead.utm_source==="google"&&<span style={{width:15,height:15,borderRadius:4,background:"rgba(5,150,105,0.12)",display:"inline-flex",alignItems:"center",justifyContent:"center",fontSize:8,fontWeight:800,color:"#047857"}}>G</span>}</div></div>
<div className="flex items-center justify-between"><div className="flex items-center gap-1.5" style={{fontSize:11,color:TEXT2,fontFamily:"'JetBrains Mono',monospace"}}><Phone size={10} style={{color:"var(--text3)"}}/>{lead.telefone||"—"}</div><div className="flex items-center gap-1.5" style={{flexShrink:0}}>{unreadCount>0&&<span title={`${unreadCount} mensagem(ns) não lida(s)`} style={{minWidth:19,height:19,borderRadius:10,background:"#22C55E",color:"#fff",fontSize:10,fontWeight:800,display:"inline-flex",alignItems:"center",justifyContent:"center",padding:"0 5px",boxShadow:"0 1px 4px rgba(34,197,94,0.4)"}}>{unreadCount>99?"99+":unreadCount}</span>}<a href={`https://wa.me/${lead.telefone}`} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()} title="Abrir WhatsApp" style={{width:24,height:24,borderRadius:6,background:"rgba(37,211,102,0.14)",display:"flex",alignItems:"center",justifyContent:"center",textDecoration:"none",flexShrink:0}}>{WA}</a></div></div>
{etiquetas&&(lead.etiqueta_ids||[]).length>0&&<div className="flex gap-1 flex-wrap" style={{marginTop:7}}>{(lead.etiqueta_ids||[]).map(id=>{const t=etiquetas.find(e=>e.id===id);return t?<span key={id} style={{fontSize:9,fontWeight:700,padding:"3px 9px",borderRadius:10,background:`${t.cor}1E`,color:t.cor,border:`1px solid ${t.cor}66`}}>{t.nome}</span>:null;})}</div>}
{lead.quali_score>0&&<div className="flex items-center gap-2" style={{marginTop:6}}><div className="flex gap-0.5">{[1,2,3,4].map(i=><div key={i} style={{height:3,width:16,borderRadius:2,background:i<=lead.quali_score?GOLD:"var(--border)"}}/>)}</div><span className={`text-[9px] px-1 py-0.5 rounded font-semibold ${bantBadge(lead.quali_score)}`}>{lead.quali_score}/4</span></div>}
{(lead.valor_venda||lead.cash_collect)?<div className="flex items-center gap-2 flex-wrap" style={{marginTop:6}}>
{lead.valor_venda?<span style={{fontSize:11,fontWeight:600,color:TEXT2}}>Venda: {fmt(lead.valor_venda)}</span>:null}
{lead.cash_collect?<span style={{fontSize:11,fontWeight:700,color:"#15803D"}}>Cash: {fmt(lead.cash_collect)}</span>:null}
</div>:null}
<div className="flex items-center justify-between" style={{marginTop:8,paddingTop:7,borderTop:`1px solid ${BORDER}`}}>
<div className="flex items-center gap-2 flex-wrap">{sdr&&<span className="flex items-center gap-1" style={{fontSize:10,fontWeight:600,color:TEXT2}}><span style={{width:7,height:7,borderRadius:"50%",background:sdr.cor||GOLD_HEX,flexShrink:0}}/>{sdr.nome.split(" ")[0]}</span>}{closer&&<span className="flex items-center gap-1" style={{fontSize:10,fontWeight:600,color:TEXT2}}><span style={{width:7,height:7,borderRadius:"50%",background:closer.cor||"#A78BFA",flexShrink:0}}/>{closer.nome.split(" ")[0]}</span>}</div>
<span className="flex items-center gap-1" style={{fontSize:10,color:TEXT3}}><Clock size={9}/>{timeAgo(lead.created_at)}</span></div>
{ina&&<div style={{marginTop:6,fontSize:10,color:"#DC2626",fontWeight:700}}>⚠ Sem contato</div>}
</div>;}

function AddLeadModal({onClose,onAdd,equipe,activePipelineId,stages}){const[n,sn]=useState("");const[t,st]=useState("");const[e,se]=useState("");const[ig,sIg]=useState("");const[s,ss]=useState("");const[sav,sSav]=useState(false);const[err,sErr]=useState(null);const sdrs=equipe.filter(m=>m.papel==="sdr"&&m.ativo);
const save=async()=>{if(!n.trim()||!t.trim())return;sSav(true);sErr(null);let tel=t.replace(/\D/g,"");if(tel.length===11)tel="55"+tel;if(tel.length===10)tel="55"+tel;const{data:dup}=await supabase.from("crm_leads").select("id,nome,stage").eq("telefone",tel).limit(1);if(dup?.length){sErr(`Lead já existe: ${dup[0].nome} (${dup[0].stage})`);sSav(false);return;}
let asgn=s;if(!asgn&&sdrs.length>0){const ct={};sdrs.forEach(x=>{ct[x.nome]=0;});const{data:all}=await supabase.from("crm_leads").select("sdr_nome").not("sdr_nome","is",null);if(all)all.forEach(l=>{if(ct[l.sdr_nome]!==undefined)ct[l.sdr_nome]++;});let min=Infinity,pk=sdrs[0].nome;Object.entries(ct).forEach(([nm,c])=>{if(c<min){min=c;pk=nm;}});asgn=pk;}
const insta=ig.trim().replace(/^https?:\/\/(www\.)?instagram\.com\//i,"").replace(/^@+/,"").replace(/[/?].*$/,"")||null;
const res=await onAdd({nome:n.trim(),telefone:tel,email:e.trim()||null,instagram:insta,stage:(stages?.find(s=>s.key==="novo")||stages?.[0])?.key||"novo",pipeline_id:activePipelineId||null,origem:"manual",sdr_nome:asgn||null});sSav(false);if(res?.error){sErr(res.error);return;}onClose();};
const IS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
return<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:16,background:"rgba(0,0,0,0.8)"}}><div style={{width:"100%",maxWidth:440,background:BG2,border:`1px solid ${BORDER2}`,borderRadius:16,padding:24}}>
<div className="flex items-center justify-between" style={{marginBottom:20}}><h3 style={{fontSize:16,fontWeight:600,color:TEXT1,margin:0}}>Novo lead</h3><button onClick={onClose} style={{padding:8,borderRadius:8,border:"none",background:"var(--bg-hover)",cursor:"pointer",color:TEXT2}}><X size={16}/></button></div>
{err&&<div style={{padding:10,borderRadius:8,background:"rgba(248,113,113,0.1)",border:"1px solid rgba(248,113,113,0.2)",color:"#F87171",fontSize:12,marginBottom:12}}>{err}</div>}
<div style={{display:"flex",flexDirection:"column",gap:10}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Nome *</label><input value={n} onChange={ev=>sn(ev.target.value)} placeholder="Nome completo" style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>WhatsApp *</label><input value={t} onChange={ev=>st(ev.target.value)} placeholder="11999998888" style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Email</label><input value={e} onChange={ev=>se(ev.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Instagram</label><input value={ig} onChange={ev=>sIg(ev.target.value)} placeholder="@usuario" style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>SDR (vazio = round-robin)</label><select value={s} onChange={ev=>ss(ev.target.value)} style={IS}><option value="">Automático</option>{sdrs.map(x=><option key={x.id} value={x.nome}>{x.nome}</option>)}</select></div></div>
<div className="flex gap-2" style={{marginTop:16}}><button onClick={save} disabled={sav} style={{flex:1,padding:10,borderRadius:8,border:"none",background:"linear-gradient(135deg,#14B8A6,#0D9488)",color:"var(--btn-text)",fontSize:13,fontWeight:600,cursor:"pointer",opacity:sav?0.6:1}}>{sav?"Salvando...":"Adicionar"}</button><button onClick={onClose} style={{padding:"10px 20px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:13,cursor:"pointer"}}>Cancelar</button></div></div></div>;}

function LeadModal({lead,onClose,onUpdate,onDelete,equipe,templates,clienteId,stages,showConfirm,showToast,audioLib,funisHook,etiquetas,isClinica,markRead}){
const[tagIds,sTagIds]=useState(lead.etiqueta_ids||[]);
const[stage,setStage]=useState(lead.stage);const[qb,sQb]=useState(lead.quali_budget||false);const[qa,sQa]=useState(lead.quali_authority||false);const[qn,sQn]=useState(lead.quali_need||false);const[qt,sQt]=useState(lead.quali_timeline||false);const[val,sVal]=useState(lead.valor_venda||"");const[cash,sCash]=useState(lead.cash_collect||"");const[sdr,sSdr]=useState(lead.sdr_nome||"");const[closer,sCloser]=useState(lead.closer_nome||"");const[nota,sNota]=useState("");const[sav,sSav]=useState(false);const[tab,sTab]=useState("info");const[copied,sCopied]=useState(null);
useEffect(()=>{if(tab==="chat"&&markRead)markRead(lead.id);},[tab,lead.id]);
const{atividades,addAtividade}=useAtividades(lead.id,clienteId);const connectedSdrs=equipe.filter(m=>m.waha_session&&m.waha_connected);const defaultSession=connectedSdrs.find(s=>s.nome===lead.sdr_nome)?.waha_session||connectedSdrs[0]?.waha_session||"pedro-oliveira";
const[selSession,sSelSession]=useState(defaultSession);
const{msgs,loading:msgsLoading,send:sendMsg,uploadMedia}=useMessages(lead.id,selSession);const[chatText,sChatText]=useState("");const[recording,setRecording]=useState(false);const[recorder,setRecorder]=useState(null);const[recTime,setRecTime]=useState(0);const[sending,setSending]=useState(false);const[showZap,sShowZap]=useState(false);const[zapCat,sZapCat]=useState("");const[zapAdd,sZapAdd]=useState(false);const[zapNewName,sZapNewName]=useState("");const[zapNewCat,sZapNewCat]=useState("geral");const[zapNewType,sZapNewType]=useState("texto");const[zapNewContent,sZapNewContent]=useState("");const[zapTab,sZapTab]=useState("msgs");const[editFunil,sEditFunil]=useState(null);const[newFunilName,sNewFunilName]=useState("");const[sendingFunil,sSendingFunil]=useState(false);const chatRef=useCallback(node=>{if(node)node.scrollTop=node.scrollHeight;},[msgs]);const score=[qb,qa,qn,qt].filter(Boolean).length;
const startRec=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mr=new MediaRecorder(stream,{mimeType:"audio/webm;codecs=opus"});const chunks=[];mr.ondataavailable=e=>chunks.push(e.data);mr.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setSending(true);const blob=new Blob(chunks,{type:"audio/ogg"});const file=new File([blob],`audio_${Date.now()}.ogg`,{type:"audio/ogg"});const url=await uploadMedia(file);if(url)await sendMsg(lead.telefone,"🎤 Áudio",clienteId,selSession,lead.waha_jid,"audio",url);setSending(false);setRecording(false);setRecTime(0);};mr.start();setRecorder(mr);setRecording(true);const t0=Date.now();const iv=setInterval(()=>{if(!mr||mr.state!=="recording"){clearInterval(iv);return;}setRecTime(Math.floor((Date.now()-t0)/1000));},1000);mr._iv=iv;}catch{showToast?.("Permita o acesso ao microfone","error");}};
const stopRec=()=>{if(recorder&&recorder.state==="recording"){clearInterval(recorder._iv);recorder.stop();setRecorder(null);}};
const sendFunil=async(funil)=>{sSendingFunil(true);sShowZap(false);const etapas=funil.crm_funil_etapas||[];for(let i=0;i<etapas.length;i++){const e=etapas[i];if(i>0)await new Promise(r=>setTimeout(r,(e.delay_seconds||5)*1000));setSending(true);if(e.tipo==="texto"&&e.conteudo){await sendMsg(lead.telefone,e.conteudo,clienteId,selSession,lead.waha_jid);}else if(e.tipo==="audio"&&e.media_url){await sendMsg(lead.telefone,"🎤 Áudio",clienteId,selSession,lead.waha_jid,"audio",e.media_url);}else if(e.tipo==="video"&&e.media_url){await sendMsg(lead.telefone,"🎥 Vídeo",clienteId,selSession,lead.waha_jid,"video",e.media_url);}else if(e.tipo==="imagem"&&e.media_url){await sendMsg(lead.telefone,"📷 Imagem",clienteId,selSession,lead.waha_jid,"image",e.media_url);}setSending(false);}sSendingFunil(false);showToast?.(`Funil "${funil.nome}" enviado`,"success");};
const sdrs=equipe.filter(m=>m.papel==="sdr"&&m.ativo);const closers=equipe.filter(m=>m.papel==="closer"&&m.ativo);
const save=async()=>{sSav(true);const u={stage,quali_score:score,quali_budget:qb,quali_authority:qa,quali_need:qn,quali_timeline:qt,valor_venda:val?parseFloat(val):null,cash_collect:cash?parseFloat(cash):null,sdr_nome:sdr||null,closer_nome:closer||null};if(stage!==lead.stage){await addAtividade(lead.id,"stage_change",`${lead.stage} → ${stage}`);if(stage==="contato_iniciado"&&!lead.contatado_at)u.contatado_at=new Date().toISOString();if(stage==="qualificado")u.qualificado_at=new Date().toISOString();if(stage==="reuniao_agendada")u.agendado_at=new Date().toISOString();if(stage==="fechado")u.venda_at=new Date().toISOString();}const ok=await onUpdate(lead.id,u);sSav(false);if(!ok){showToast?.("Falha ao salvar — verifique a conexão e tente de novo","error");return;}showToast?.("Lead salvo com sucesso","success");onClose();};
const addNota=async()=>{if(!nota.trim())return;await addAtividade(lead.id,"nota",nota.trim());sNota("");};
const copyTpl=t=>{const msg=t.mensagem.replace(/\{\{nome\}\}/g,lead.nome?.split(" ")[0]||"");navigator.clipboard.writeText(msg);sCopied(t.id);setTimeout(()=>sCopied(null),2000);};
const si=stages.find(x=>x.key===lead.stage);const SS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
return<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:16,background:"var(--overlay)",backdropFilter:"blur(12px)",WebkitBackdropFilter:"blur(12px)",animation:`fadeIn 200ms ${EASE}`}}><div className="modal-card" style={{width:"100%",maxWidth:720,background:BG2,border:`1px solid ${BORDER2}`,borderRadius:20,padding:24,maxHeight:"95vh",overflowY:"auto",animation:`modalIn 300ms ${EASE}`,boxShadow:"0 8px 40px rgba(0,0,0,0.3)"}}>
<div className="flex items-center justify-between" style={{marginBottom:16}}><div><h3 style={{fontSize:18,fontWeight:600,color:TEXT1,margin:0}}>{lead.nome}</h3><div className="flex items-center gap-2" style={{marginTop:6}}><span style={{fontSize:11,padding:"3px 10px",borderRadius:20,background:`${si?.color}18`,color:si?.color,fontWeight:500}}>{si?.label}</span><span style={{fontSize:10,color:TEXT3}}>{timeAgo(lead.created_at)}</span></div></div>
<div className="flex items-center gap-2"><button onClick={async()=>{const ok=await showConfirm("Excluir lead","Tem certeza que deseja excluir este lead?",true);if(ok){onDelete(lead.id);onClose();}}} style={{padding:8,borderRadius:8,border:"none",background:"rgba(248,113,113,0.1)",cursor:"pointer",color:"#F87171",transition:`all 200ms ${EASE}`}} onMouseEnter={e=>e.currentTarget.style.background="rgba(248,113,113,0.2)"} onMouseLeave={e=>e.currentTarget.style.background="rgba(248,113,113,0.1)"}><Trash2 size={14}/></button><a href={`https://wa.me/${lead.telefone}`} target="_blank" rel="noreferrer" style={{padding:8,borderRadius:8,background:"rgba(37,211,102,0.12)",display:"flex",alignItems:"center",justifyContent:"center"}}>{WA}</a><button onClick={onClose} style={{padding:8,borderRadius:8,border:"none",background:"var(--bg-hover)",cursor:"pointer",color:TEXT2}}><X size={16}/></button></div></div>

<div className="flex gap-1" style={{marginBottom:16,background:"rgba(255,255,255,0.03)",borderRadius:8,padding:3}}>{[{k:"info",l:"Dados"},{k:"chat",l:"Chat"},{k:"respostas",l:"Respostas"},{k:"bant",l:"BANT"},{k:"notas",l:"Notas"},{k:"msgs",l:"Templates"}].filter(t=>!(isClinica&&t.k==="respostas")).map(t=><button key={t.k} onClick={()=>sTab(t.k)} style={{flex:1,padding:"7px 0",borderRadius:6,border:"none",fontSize:11,fontWeight:500,cursor:"pointer",background:tab===t.k?GOLD_BG2:"transparent",color:tab===t.k?GOLD:TEXT3}}>{t.l}</button>)}</div>

{tab==="info"&&<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:14}}>{[{l:"Email",v:lead.email||"—"},{l:"Telefone",v:lead.telefone||"—"},{l:"Instagram",v:lead.instagram?"@"+lead.instagram:"—",href:lead.instagram?`https://instagram.com/${lead.instagram}`:null},{l:"Campanha",v:lead.utm_campaign||"—"},{l:"Conjunto",v:lead.utm_term||"—"},{l:"Criativo",v:lead.utm_content||"—"},{l:"Fonte",v:lead.utm_source||"—"}].map(f=><div key={f.l} style={{background:BG3,border:`1px solid ${BORDER}`,borderRadius:8,padding:8}}><div style={{fontSize:9,color:TEXT3,textTransform:"uppercase",marginBottom:3}}>{f.l}</div><div style={{fontSize:12,color:TEXT1}}>{f.href?<a href={f.href} target="_blank" rel="noreferrer" style={{color:GOLD,textDecoration:"none"}}>{f.v}</a>:f.v}</div></div>)}</div>
{etiquetas&&etiquetas.length>0&&<div style={{marginBottom:14}}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:6}}>Etiquetas</label><div className="flex gap-1.5 flex-wrap">{etiquetas.map(t=>{const on=tagIds.includes(t.id);return<button key={t.id} onClick={async()=>{const next=on?tagIds.filter(x=>x!==t.id):[...tagIds,t.id];sTagIds(next);await onUpdate(lead.id,{etiqueta_ids:next});}} style={{padding:"6px 14px",borderRadius:16,border:`1.5px solid ${on?t.cor:BORDER}`,background:on?`${t.cor}22`:"transparent",color:on?t.cor:TEXT3,fontSize:12,fontWeight:600,cursor:"pointer",transition:`all 150ms ${EASE}`}}>{on?"✓ ":""}{t.nome}</button>;})}</div></div>}
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:14}}>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Etapa</label><select value={stage} onChange={e=>setStage(e.target.value)} style={SS}>{stages.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></div>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>SDR</label><select value={sdr} onChange={e=>sSdr(e.target.value)} style={SS}><option value="">—</option>{sdrs.map(s=><option key={s.id} value={s.nome}>{s.nome}</option>)}</select></div>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Closer</label><select value={closer} onChange={e=>sCloser(e.target.value)} style={SS}><option value="">—</option>{closers.map(c=><option key={c.id} value={c.nome}>{c.nome}</option>)}</select></div>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Valor da Venda (R$)</label><input type="number" value={val} onChange={e=>sVal(e.target.value)} placeholder="50000" style={SS}/></div>
<div style={{gridColumn:"1/-1"}}><label style={{fontSize:9,color:GOLD,textTransform:"uppercase",display:"block",marginBottom:3,fontWeight:600}}>Cash Collect (R$) — enviado ao Meta</label><input type="number" value={cash} onChange={e=>sCash(e.target.value)} placeholder="10000" style={{...SS,borderColor:"var(--gold-border)"}}/></div>
</div></>}

{tab==="chat"&&<div style={{marginBottom:14,display:"flex",flexDirection:"column",height:500}}>
{connectedSdrs.length>1&&<div style={{background:"#1F2C33",borderRadius:"10px 10px 0 0",padding:"6px 10px",display:"flex",alignItems:"center",gap:6,borderBottom:"1px solid rgba(255,255,255,0.06)"}}><span style={{fontSize:9,color:"rgba(255,255,255,0.4)"}}>WhatsApp:</span><select value={selSession} onChange={e=>sSelSession(e.target.value)} style={{padding:"4px 8px",borderRadius:6,border:"1px solid rgba(255,255,255,0.08)",background:"#2A3942",color:"#E9EDEF",fontSize:10,outline:"none"}}>{connectedSdrs.map(s=><option key={s.id} value={s.waha_session}>{s.nome} ({s.waha_phone?.slice(-4)||"..."})</option>)}</select></div>}
<div ref={chatRef} style={{flex:1,overflowY:"auto",background:"#0B141A",borderRadius:connectedSdrs.length>1?"0":"10px 10px 0 0",padding:"12px 16px",display:"flex",flexDirection:"column",gap:2,backgroundImage:"url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.015'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\")"}}>
{msgsLoading?<div style={{textAlign:"center",padding:30}}><Loader2 size={18} style={{color:"rgba(255,255,255,0.3)",animation:"spin 1s linear infinite"}}/></div>:msgs.length===0?<div style={{textAlign:"center",padding:30}}><div style={{fontSize:12,color:"rgba(255,255,255,0.35)",background:"rgba(255,255,255,0.06)",display:"inline-block",padding:"6px 14px",borderRadius:8}}>Nenhuma mensagem</div></div>:(()=>{let lastDate="";return msgs.map((m,i)=>{const d=new Date(m.created_at);const dateStr=d.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric"});const today=new Date().toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric"});const yesterday=new Date(Date.now()-86400000).toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric"});const showDate=dateStr!==lastDate;if(showDate)lastDate=dateStr;const dateLabel=dateStr===today?"Hoje":dateStr===yesterday?"Ontem":dateStr;const isOut=m.direction==="outbound";
return<div key={m.id}>{showDate&&<div style={{textAlign:"center",margin:"8px 0"}}><span style={{fontSize:10,color:"rgba(255,255,255,0.45)",background:"rgba(255,255,255,0.06)",padding:"4px 12px",borderRadius:6,fontWeight:500}}>{dateLabel}</span></div>}
<div style={{display:"flex",justifyContent:isOut?"flex-end":"flex-start",marginBottom:1}}><div style={{maxWidth:"78%",padding:"6px 8px 4px",borderRadius:isOut?"8px 2px 8px 8px":"2px 8px 8px 8px",background:isOut?"#005C4B":"#1F2C33",position:"relative",minWidth:60}}>
{m.content_type==="image"&&m.media_url?<div><img src={m.media_url} alt="" style={{maxWidth:240,maxHeight:180,borderRadius:4,cursor:"pointer",display:"block",objectFit:"cover"}} onClick={()=>window.open(m.media_url,"_blank")}/>{m.content&&m.content!=="📷 Imagem"&&<div style={{fontSize:13,color:"#E9EDEF",marginTop:4}}>{m.content}</div>}</div>
:m.content_type==="video"&&m.media_url?<div><video src={m.media_url} controls style={{maxWidth:240,maxHeight:180,borderRadius:4,display:"block"}}/>{m.content&&m.content!=="🎥 Vídeo"&&<div style={{fontSize:13,color:"#E9EDEF",marginTop:4}}>{m.content}</div>}</div>
:m.content_type==="audio"&&m.media_url?<div style={{display:"flex",alignItems:"center",gap:8,minWidth:200}}><div style={{width:28,height:28,borderRadius:"50%",background:"rgba(255,255,255,0.1)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>▶</div><audio src={m.media_url} controls style={{flex:1,height:32,opacity:0.85}}/></div>
:m.content_type==="document"&&m.media_url?<a href={m.media_url} target="_blank" rel="noreferrer" style={{fontSize:13,color:"#53BDEB",textDecoration:"none",display:"flex",alignItems:"center",gap:6}}>📎 {m.content||"Documento"}</a>
:<div style={{fontSize:13,color:"#E9EDEF",lineHeight:1.35,wordBreak:"break-word"}}>{m.content}</div>}
<div style={{display:"flex",justifyContent:"flex-end",alignItems:"center",gap:3,marginTop:1}}><span style={{fontSize:10,color:"rgba(255,255,255,0.45)"}}>{d.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</span>{isOut&&<span style={{fontSize:10,color:m.status==="read"?"#53BDEB":"rgba(255,255,255,0.45)"}}>✓✓</span>}</div>
</div></div></div>;});})()}
</div>

{showZap&&<div style={{background:"#1a2730",borderTop:"2px solid rgba(20,184,166,0.35)",padding:12,maxHeight:300,overflowY:"auto"}}>
<div className="flex items-center justify-between" style={{marginBottom:10}}><div className="flex items-center gap-3"><span style={{display:"flex",alignItems:"center",gap:6,fontSize:12,fontWeight:700,color:"#2DD4BF"}}><Zap size={14}/>Respostas rápidas</span><div className="flex gap-1">{[{k:"msgs",l:"Mensagens & Áudios"},{k:"funis",l:"Funis"}].map(t=><button key={t.k} onClick={()=>sZapTab(t.k)} style={{padding:"5px 12px",borderRadius:14,border:"none",background:zapTab===t.k?"rgba(20,184,166,0.2)":"rgba(255,255,255,0.05)",color:zapTab===t.k?"#2DD4BF":"rgba(255,255,255,0.55)",fontSize:11,fontWeight:600,cursor:"pointer"}}>{t.l}</button>)}</div></div><button onClick={()=>sShowZap(false)} style={{fontSize:14,padding:"2px 8px",border:"none",background:"transparent",color:"rgba(255,255,255,0.45)",cursor:"pointer"}}>✕</button></div>

{zapTab==="msgs"&&<>{/* Botão adicionar */}
<div className="flex justify-end" style={{marginBottom:6}}><button onClick={()=>sZapAdd(p=>!p)} style={{fontSize:11,fontWeight:600,padding:"5px 12px",borderRadius:6,border:"none",background:zapAdd?"rgba(20,184,166,0.2)":"rgba(255,255,255,0.07)",color:zapAdd?"#2DD4BF":"rgba(255,255,255,0.6)",cursor:"pointer"}}>{zapAdd?"Fechar":"+ Adicionar novo"}</button></div>
{zapAdd&&<div style={{marginBottom:10,padding:8,borderRadius:6,background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.06)"}}><div className="flex gap-2" style={{marginBottom:6}}><input value={zapNewName} onChange={e=>sZapNewName(e.target.value)} placeholder="Nome..." style={{flex:1,padding:"5px 8px",borderRadius:4,border:"1px solid rgba(255,255,255,0.08)",background:"transparent",color:"#E9EDEF",fontSize:11,outline:"none"}}/><select value={zapNewCat} onChange={e=>sZapNewCat(e.target.value)} style={{padding:"5px 6px",borderRadius:4,border:"1px solid rgba(255,255,255,0.08)",background:"#2A3942",color:"#E9EDEF",fontSize:10,outline:"none"}}><option value="geral">Geral</option><option value="boas-vindas">Boas-vindas</option><option value="qualificacao">Qualificação</option><option value="agendamento">Agendamento</option><option value="follow-up">Follow-up</option><option value="objecao">Objeção</option></select><select value={zapNewType} onChange={e=>sZapNewType(e.target.value)} style={{padding:"5px 6px",borderRadius:4,border:"1px solid rgba(255,255,255,0.08)",background:"#2A3942",color:"#E9EDEF",fontSize:10,outline:"none"}}><option value="texto">Texto</option><option value="audio">Áudio</option></select></div>
{zapNewType==="texto"?<div className="flex gap-2"><textarea value={zapNewContent} onChange={e=>sZapNewContent(e.target.value)} placeholder="Mensagem pronta..." rows={2} style={{flex:1,padding:"5px 8px",borderRadius:4,border:"1px solid rgba(255,255,255,0.08)",background:"transparent",color:"#E9EDEF",fontSize:11,outline:"none",resize:"none"}}/><button onClick={async()=>{if(!zapNewName.trim()||!zapNewContent.trim())return;await audioLib.addItem({nome:zapNewName.trim(),categoria:zapNewCat,tipo:"texto",conteudo:zapNewContent.trim()});sZapNewName("");sZapNewContent("");sZapAdd(false);}} style={{padding:"5px 10px",borderRadius:4,border:"none",background:"#00A884",color:"#fff",fontSize:10,fontWeight:600,cursor:"pointer",alignSelf:"flex-end"}}>Salvar</button></div>
:<div className="flex gap-2 items-center"><label style={{flex:1,padding:"8px 12px",borderRadius:4,border:"1px dashed rgba(255,255,255,0.15)",background:"transparent",color:"rgba(255,255,255,0.5)",fontSize:10,textAlign:"center",cursor:"pointer"}}><span>📎 Selecionar áudio</span><input type="file" accept="audio/*" style={{display:"none"}} onChange={async e=>{const file=e.target.files?.[0];if(!file||!zapNewName.trim())return;const url=await uploadMedia(file);if(url){await audioLib.addItem({nome:zapNewName.trim(),categoria:zapNewCat,tipo:"audio",media_url:url});sZapNewName("");sZapAdd(false);}e.target.value="";}}/></label></div>}
</div>}
{audioLib.categories.length>0&&<div className="flex gap-1" style={{marginBottom:8,overflowX:"auto"}}><button onClick={()=>sZapCat("")} style={{padding:"5px 13px",borderRadius:14,border:"none",background:zapCat===""?"rgba(20,184,166,0.2)":"rgba(255,255,255,0.05)",color:zapCat===""?"#2DD4BF":"rgba(255,255,255,0.55)",fontSize:10,fontWeight:600,cursor:"pointer",whiteSpace:"nowrap",flexShrink:0}}>Todos</button>{audioLib.categories.map(c=><button key={c} onClick={()=>sZapCat(c)} style={{padding:"5px 13px",borderRadius:14,border:"none",background:zapCat===c?"rgba(20,184,166,0.2)":"rgba(255,255,255,0.05)",color:zapCat===c?"#2DD4BF":"rgba(255,255,255,0.55)",fontSize:10,fontWeight:600,cursor:"pointer",whiteSpace:"nowrap",flexShrink:0,textTransform:"capitalize"}}>{c}</button>)}</div>}
{audioLib.items.filter(x=>!zapCat||x.categoria===zapCat).length===0?<div style={{textAlign:"center",padding:12,fontSize:10,color:"rgba(255,255,255,0.3)"}}>Nenhum item. Clique em "+ Adicionar".</div>
:audioLib.items.filter(x=>!zapCat||x.categoria===zapCat).map(item=><div key={item.id} className="flex items-center gap-2" style={{padding:"9px 10px",borderRadius:8,background:"rgba(255,255,255,0.04)",marginBottom:5,border:"1px solid rgba(255,255,255,0.06)"}}><span style={{fontSize:15,flexShrink:0}}>{item.tipo==="audio"?"🎤":"💬"}</span><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,fontWeight:600,color:"#E9EDEF",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{item.nome}</div><div style={{fontSize:9,color:"rgba(255,255,255,0.4)",textTransform:"capitalize"}}>{item.categoria}{item.tipo==="texto"&&item.conteudo?` • ${item.conteudo.slice(0,50)}`:""}</div></div>
{item.tipo==="audio"&&item.media_url&&<button onClick={()=>{const a=new Audio(item.media_url);a.play();}} title="Ouvir" style={{width:28,height:28,borderRadius:"50%",border:"none",background:"rgba(20,184,166,0.15)",cursor:"pointer",color:"#2DD4BF",fontSize:11,flexShrink:0}}>▶</button>}
<button onClick={async()=>{setSending(true);if(item.tipo==="texto"){await sendMsg(lead.telefone,item.conteudo,clienteId,selSession,lead.waha_jid);}else if(item.tipo==="audio"&&item.media_url){await sendMsg(lead.telefone,"🎤 Áudio",clienteId,selSession,lead.waha_jid,"audio",item.media_url);}setSending(false);sShowZap(false);}} style={{padding:"7px 16px",borderRadius:6,border:"none",background:"#00A884",color:"#fff",fontSize:11,fontWeight:700,cursor:"pointer",flexShrink:0}}>Enviar</button>
<button onClick={()=>audioLib.removeItem(item.id)} style={{padding:4,border:"none",background:"transparent",cursor:"pointer",color:"rgba(248,113,113,0.5)",fontSize:10}}>✕</button>
</div>)}</>}

{zapTab==="funis"&&<>{/* Criar funil */}
<div className="flex gap-2" style={{marginBottom:8}}><input value={newFunilName} onChange={e=>sNewFunilName(e.target.value)} placeholder="Nome do funil..." style={{flex:1,padding:"5px 8px",borderRadius:4,border:"1px solid rgba(255,255,255,0.08)",background:"transparent",color:"#E9EDEF",fontSize:11,outline:"none"}} onKeyDown={async e=>{if(e.key==="Enter"&&newFunilName.trim()){await funisHook.addFunil(newFunilName.trim());sNewFunilName("");}}}/><button onClick={async()=>{if(!newFunilName.trim())return;await funisHook.addFunil(newFunilName.trim());sNewFunilName("");}} style={{padding:"5px 10px",borderRadius:4,border:"none",background:GOLD_BG2,color:GOLD,fontSize:9,fontWeight:600,cursor:"pointer"}}>Criar</button></div>
{funisHook.funis.length===0?<div style={{textAlign:"center",padding:12,fontSize:10,color:"rgba(255,255,255,0.3)"}}>Nenhum funil criado.</div>
:funisHook.funis.map(funil=><div key={funil.id} style={{marginBottom:6,borderRadius:6,border:`1px solid ${editFunil===funil.id?"rgba(13,148,136,0.2)":"rgba(255,255,255,0.04)"}`,background:"rgba(255,255,255,0.02)",overflow:"hidden"}}>
<div className="flex items-center gap-2" style={{padding:"6px 8px",cursor:"pointer"}} onClick={()=>sEditFunil(editFunil===funil.id?null:funil.id)}>
<span style={{fontSize:10,fontWeight:600,color:"#E9EDEF",flex:1}}>{funil.nome}</span>
<span style={{fontSize:8,color:"rgba(255,255,255,0.35)"}}>{funil.crm_funil_etapas?.length||0} etapas</span>
{!sendingFunil&&<button onClick={e=>{e.stopPropagation();sendFunil(funil);}} style={{padding:"3px 8px",borderRadius:4,border:"none",background:"#00A884",color:"#fff",fontSize:8,fontWeight:600,cursor:"pointer"}}>▶ Enviar</button>}
{sendingFunil&&<span style={{fontSize:8,color:"#14B8A6"}}>Enviando...</span>}
<button onClick={e=>{e.stopPropagation();funisHook.removeFunil(funil.id);}} style={{padding:2,border:"none",background:"transparent",cursor:"pointer",color:"rgba(248,113,113,0.5)",fontSize:9}}>✕</button>
</div>
{editFunil===funil.id&&<div style={{padding:"6px 8px",borderTop:"1px solid rgba(255,255,255,0.04)"}}>
{(funil.crm_funil_etapas||[]).map((e,i)=><div key={e.id} className="flex items-center gap-2" style={{padding:"4px 6px",borderRadius:4,background:"rgba(255,255,255,0.02)",marginBottom:3,border:"1px solid rgba(255,255,255,0.04)"}}>
<span style={{fontSize:8,color:"rgba(255,255,255,0.3)",width:14,textAlign:"center"}}>{i+1}</span>
<span style={{fontSize:9,padding:"2px 6px",borderRadius:3,background:e.tipo==="texto"?"rgba(96,165,250,0.1)":e.tipo==="audio"?"rgba(13,148,136,0.1)":e.tipo==="video"?"rgba(168,85,247,0.1)":"rgba(52,211,153,0.1)",color:e.tipo==="texto"?"#60A5FA":e.tipo==="audio"?"#14B8A6":e.tipo==="video"?"#A855F7":"#34D399",fontWeight:500}}>{e.tipo}</span>
<div style={{flex:1,fontSize:9,color:"#E9EDEF",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{e.conteudo||e.media_url?.split("/").pop()||"—"}</div>
<div className="flex items-center gap-1"><Clock size={8} style={{color:"rgba(255,255,255,0.3)"}}/><input type="number" value={e.delay_seconds||5} onChange={ev=>funisHook.updateEtapa(funil.id,e.id,{delay_seconds:parseInt(ev.target.value)||0})} style={{width:30,padding:"2px 4px",borderRadius:3,border:"1px solid rgba(255,255,255,0.08)",background:"transparent",color:"#E9EDEF",fontSize:9,outline:"none",textAlign:"center"}}/><span style={{fontSize:7,color:"rgba(255,255,255,0.3)"}}>s</span></div>
<button onClick={()=>funisHook.removeEtapa(funil.id,e.id)} style={{padding:1,border:"none",background:"transparent",cursor:"pointer",color:"rgba(248,113,113,0.5)",fontSize:8}}>✕</button>
</div>)}
<div className="flex gap-2" style={{marginTop:4}}>
<button onClick={async()=>{await funisHook.addEtapa(funil.id,{tipo:"texto",conteudo:"",delay_seconds:5});}} style={{padding:"3px 8px",borderRadius:3,border:"1px solid rgba(255,255,255,0.06)",background:"transparent",color:"rgba(255,255,255,0.5)",fontSize:8,cursor:"pointer"}}>+ Texto</button>
<label style={{padding:"3px 8px",borderRadius:3,border:"1px solid rgba(255,255,255,0.06)",background:"transparent",color:"rgba(255,255,255,0.5)",fontSize:8,cursor:"pointer"}}><span>+ Áudio</span><input type="file" accept="audio/*" style={{display:"none"}} onChange={async ev=>{const file=ev.target.files?.[0];if(!file)return;const url=await uploadMedia(file);if(url)await funisHook.addEtapa(funil.id,{tipo:"audio",media_url:url,delay_seconds:5});ev.target.value="";}}/></label>
<label style={{padding:"3px 8px",borderRadius:3,border:"1px solid rgba(255,255,255,0.06)",background:"transparent",color:"rgba(255,255,255,0.5)",fontSize:8,cursor:"pointer"}}><span>+ Vídeo</span><input type="file" accept="video/*" style={{display:"none"}} onChange={async ev=>{const file=ev.target.files?.[0];if(!file)return;const url=await uploadMedia(file);if(url)await funisHook.addEtapa(funil.id,{tipo:"video",media_url:url,delay_seconds:5});ev.target.value="";}}/></label>
<label style={{padding:"3px 8px",borderRadius:3,border:"1px solid rgba(255,255,255,0.06)",background:"transparent",color:"rgba(255,255,255,0.5)",fontSize:8,cursor:"pointer"}}><span>+ Imagem</span><input type="file" accept="image/*" style={{display:"none"}} onChange={async ev=>{const file=ev.target.files?.[0];if(!file)return;const url=await uploadMedia(file);if(url)await funisHook.addEtapa(funil.id,{tipo:"imagem",media_url:url,delay_seconds:5});ev.target.value="";}}/></label>
</div>
{(funil.crm_funil_etapas||[]).filter(e=>e.tipo==="texto"&&!e.conteudo).map(e=><div key={e.id+"edit"} className="flex gap-2" style={{marginTop:4}}><input placeholder="Digite o texto..." onChange={ev=>funisHook.updateEtapa(funil.id,e.id,{conteudo:ev.target.value})} style={{flex:1,padding:"5px 8px",borderRadius:4,border:"1px solid rgba(255,255,255,0.08)",background:"transparent",color:"#E9EDEF",fontSize:10,outline:"none"}}/></div>)}
</div>}
</div>)}</>}
</div>}

<div style={{background:"#1F2C33",borderRadius:showZap?"0":"0 0 10px 10px",padding:"6px 8px",display:"flex",alignItems:"center",gap:6}}>
{sending?<div className="flex items-center gap-3" style={{flex:1,padding:"8px 12px",borderRadius:20,background:"#2A3942"}}><Loader2 size={14} style={{color:"rgba(255,255,255,0.5)",animation:"spin 1s linear infinite"}}/><span style={{fontSize:13,color:"rgba(255,255,255,0.5)"}}>Enviando...</span></div>
:recording?<div className="flex items-center gap-3" style={{flex:1,padding:"8px 12px",borderRadius:20,background:"#2A3942"}}><div style={{width:8,height:8,borderRadius:"50%",background:"#F87171",animation:"pulse 1s infinite"}}/><span style={{fontSize:13,color:"#F87171",fontWeight:500}}>Gravando {recTime}s</span><button onClick={stopRec} style={{marginLeft:"auto",padding:"4px 12px",borderRadius:12,border:"none",background:"rgba(248,113,113,0.15)",color:"#F87171",fontSize:11,fontWeight:600,cursor:"pointer"}}>Parar</button></div>
:<><label style={{width:34,height:34,borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",flexShrink:0}}><Plus size={18} style={{color:"rgba(255,255,255,0.55)"}}/><input type="file" accept="image/*,video/*,audio/*,.pdf,.doc,.docx" style={{display:"none"}} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setSending(true);const url=await uploadMedia(file);if(url){let ct="document";if(file.type.startsWith("image/"))ct="image";else if(file.type.startsWith("video/"))ct="video";else if(file.type.startsWith("audio/"))ct="audio";await sendMsg(lead.telefone,"",clienteId,selSession,lead.waha_jid,ct,url);}setSending(false);e.target.value="";}}/></label>
<button onClick={()=>sShowZap(p=>!p)} style={{display:"flex",alignItems:"center",gap:5,height:34,padding:"0 12px",borderRadius:17,border:showZap?"none":"1px solid rgba(45,212,191,0.35)",background:showZap?"#14B8A6":"rgba(20,184,166,0.12)",color:showZap?"#06201D":"#2DD4BF",fontSize:11,fontWeight:600,cursor:"pointer",flexShrink:0,whiteSpace:"nowrap"}}><Zap size={13}/>Áudios & Rápidas</button>
<div style={{flex:1,display:"flex",alignItems:"center",background:"#2A3942",borderRadius:20,padding:"6px 12px"}}><input value={chatText} onChange={e=>sChatText(e.target.value)} placeholder="Mensagem" onKeyDown={async e=>{if(e.key==="Enter"&&chatText.trim()&&!sending){setSending(true);const ok=await sendMsg(lead.telefone,chatText.trim(),clienteId,selSession,lead.waha_jid);if(ok)sChatText("");setSending(false);}}} style={{flex:1,padding:0,border:"none",background:"transparent",color:"#E9EDEF",fontSize:13,outline:"none"}}/></div>
{chatText.trim()?<button disabled={sending} onClick={async()=>{if(!chatText.trim()||sending)return;setSending(true);const ok=await sendMsg(lead.telefone,chatText.trim(),clienteId,selSession,lead.waha_jid);if(ok)sChatText("");setSending(false);}} style={{width:34,height:34,borderRadius:"50%",border:"none",background:"#00A884",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",flexShrink:0,transition:`all 150ms ${EASE}`}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg></button>
:<button onClick={startRec} style={{width:34,height:34,borderRadius:"50%",border:"none",background:"transparent",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",flexShrink:0}}><Mic size={18} style={{color:"rgba(255,255,255,0.55)"}}/></button>}</>}
</div></div>}

{tab==="respostas"&&<div style={{marginBottom:14}}>{lead.lead_score>0&&<div className="flex items-center gap-3" style={{padding:12,borderRadius:8,background:BG3,border:`1px solid ${BORDER}`,marginBottom:12}}><span style={{fontSize:10,color:TEXT3,textTransform:"uppercase"}}>Lead Score</span><span style={{fontSize:20,fontWeight:700,color:lead.lead_score>=10000?"#4ADE80":lead.lead_score>=5000?GOLD_HEX:TEXT2}}>{lead.lead_score?.toLocaleString("pt-BR")}</span></div>}{(()=>{let respostas={};try{respostas=typeof lead.respostas==="string"?JSON.parse(lead.respostas):lead.respostas||{};}catch{respostas={};}const entries=Object.entries(respostas);if(entries.length===0)return<div style={{fontSize:12,color:TEXT3,textAlign:"center",padding:16}}>Sem respostas do formulário</div>;return entries.map(([pergunta,resp],i)=><div key={i} style={{padding:10,borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:6,background:BG3}}><div style={{fontSize:9,color:TEXT3,textTransform:"uppercase",marginBottom:4}}>{pergunta}</div><div style={{fontSize:12,color:TEXT1,lineHeight:1.4}}>{resp}</div></div>);})()}</div>}

{tab==="bant"&&<div style={{marginBottom:14}}><div style={{fontSize:11,color:TEXT2,marginBottom:10}}>Marque os critérios:</div>{BANT_ITEMS.map((b,i)=>{const ck=[qb,qa,qn,qt],st=[sQb,sQa,sQn,sQt];return<div key={b.key} onClick={()=>st[i](!ck[i])} style={{display:"flex",alignItems:"center",gap:10,padding:10,borderRadius:8,border:`1px solid ${ck[i]?"var(--gold-border)":BORDER}`,background:ck[i]?GOLD_BG:"transparent",marginBottom:6,cursor:"pointer"}}><div style={{width:22,height:22,borderRadius:5,border:`2px solid ${ck[i]?GOLD:"rgba(255,255,255,0.15)"}`,display:"flex",alignItems:"center",justifyContent:"center",background:ck[i]?GOLD_BG2:"transparent"}}>{ck[i]&&<Check size={13} style={{color:GOLD}}/>}</div><div><div style={{fontSize:12,fontWeight:500,color:ck[i]?GOLD_LIGHT:TEXT1}}>{b.label}</div><div style={{fontSize:10,color:TEXT3,marginTop:1}}>{b.desc}</div></div></div>;})}
<div className="flex items-center gap-3" style={{marginTop:10,padding:10,borderRadius:8,background:BG3}}><span style={{fontSize:11,color:TEXT3}}>Score:</span><div className="flex gap-1">{[1,2,3,4].map(i=><div key={i} style={{width:22,height:5,borderRadius:2,background:i<=score?GOLD:"rgba(255,255,255,0.06)"}}/>)}</div><span className={`px-2 py-0.5 rounded text-xs font-bold ${bantBadge(score)}`}>{score}/4</span></div></div>}

{tab==="notas"&&<div style={{marginBottom:14}}><div className="flex gap-2" style={{marginBottom:10}}><input value={nota} onChange={e=>sNota(e.target.value)} placeholder="Adicionar nota..." style={{...SS,flex:1}} onKeyDown={e=>{if(e.key==="Enter")addNota();}}/><button onClick={addNota} style={{padding:"8px 14px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:11,fontWeight:500,cursor:"pointer"}}>Salvar</button></div>{atividades.length===0&&<div style={{fontSize:12,color:TEXT3,textAlign:"center",padding:16}}>Nenhuma atividade</div>}{atividades.map(a=><div key={a.id} style={{padding:8,borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:4}}><div className="flex items-center justify-between"><span style={{fontSize:9,color:a.tipo==="stage_change"?"#A78BFA":GOLD,fontWeight:600,textTransform:"uppercase"}}>{a.tipo.replace("_"," ")}</span><span style={{fontSize:8,color:TEXT3}}>{new Date(a.created_at).toLocaleString("pt-BR")}</span></div><div style={{fontSize:11,color:TEXT1,marginTop:3}}>{a.descricao}</div></div>)}</div>}

{tab==="msgs"&&<div style={{marginBottom:14}}>{templates.length===0&&<div style={{fontSize:12,color:TEXT3,textAlign:"center",padding:16}}>Nenhum template</div>}{templates.map(t=>{const msg=t.mensagem.replace(/\{\{nome\}\}/g,lead.nome?.split(" ")[0]||"");return<div key={t.id} style={{padding:10,borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:6,background:BG3}}><div className="flex items-center justify-between" style={{marginBottom:4}}><span style={{fontSize:11,fontWeight:500,color:GOLD}}>{t.titulo}</span><button onClick={()=>copyTpl(t)} style={{display:"flex",alignItems:"center",gap:3,padding:"3px 8px",borderRadius:5,border:"none",background:copied===t.id?"rgba(74,222,128,0.15)":GOLD_BG2,color:copied===t.id?"#4ADE80":GOLD,fontSize:9,fontWeight:500,cursor:"pointer"}}>{copied===t.id?<><Check size={9}/>Copiado</>:<><Copy size={9}/>Copiar</>}</button></div><div style={{fontSize:11,color:TEXT2,lineHeight:1.4}}>{msg}</div></div>;})}</div>}

<div className="flex gap-2"><button onClick={save} disabled={sav} style={{flex:1,padding:10,borderRadius:8,border:"none",background:"linear-gradient(135deg,#14B8A6,#0D9488)",color:"var(--btn-text)",fontSize:13,fontWeight:600,cursor:"pointer",opacity:sav?0.6:1}}>{sav?"Salvando...":"Salvar"}</button><button onClick={onClose} style={{padding:"10px 20px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:13,cursor:"pointer"}}>Cancelar</button></div></div></div>;}

// ===== PAGES =====


export { CrmDialog, Toast, LoginPage, Card, Spinner, Skeleton, Logo, MC, LeadCard, AddLeadModal, LeadModal };
