import { useState, useEffect, useMemo, useCallback } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, CartesianGrid, Area, AreaChart } from "recharts";
import { Users, UserCheck, Calendar, DollarSign, TrendingUp, Target, Phone, Filter, LayoutDashboard, Kanban, BarChart3, Radio, Settings, X, Check, AlertTriangle, Zap, Plus, Trash2, Eye, EyeOff, Award, Loader2, RefreshCw, Search, MessageSquare, Clock, Copy, ArrowRightLeft } from "lucide-react";
import { supabase } from "./lib/supabase";

const GOLD="#C9A84C",GOLD_LIGHT="#E2C97E",GOLD_DIM="#8B7535",GOLD_BG="rgba(201,168,76,0.08)",GOLD_BG2="rgba(201,168,76,0.15)";
const BG="#09090B",BG2="#0F0F12",BG3="#16161A",BORDER="rgba(201,168,76,0.08)",BORDER2="rgba(201,168,76,0.15)";
const TEXT1="#FAFAF9",TEXT2="rgba(250,250,249,0.55)",TEXT3="rgba(250,250,249,0.3)";
const TEAM_COLORS=["#C9A84C","#60A5FA","#34D399","#F472B6","#A78BFA","#FB923C","#22D3EE","#F87171","#84CC16","#E879F9"];

const BANT_ITEMS=[
  {key:"budget",label:"Budget",desc:"Tem condição financeira de investir?"},
  {key:"authority",label:"Authority",desc:"É o decisor da compra?"},
  {key:"need",label:"Need",desc:"Tem a dor/necessidade real?"},
  {key:"timeline",label:"Timeline",desc:"Tem urgência ou prazo definido?"}
];

const STAGES=[
  {key:"desqualificado",label:"Desqualificado",color:"#F87171"},
  {key:"novo",label:"Novo",color:GOLD},
  {key:"contato_iniciado",label:"Contato Iniciado",color:"#60A5FA"},
  {key:"conversando",label:"Conversando",color:"#38BDF8"},
  {key:"qualificado",label:"Qualificado",color:"#34D399"},
  {key:"reuniao_agendada",label:"Reunião Agendada",color:"#A78BFA"},
  {key:"reuniao_realizada",label:"Reunião Realizada",color:"#818CF8"},
  {key:"no_show",label:"No Show",color:"#FBBF24"},
  {key:"reagendamento",label:"Reagendamento",color:"#FB923C"},
  {key:"proposta_enviada",label:"Proposta Enviada",color:"#22D3EE"},
  {key:"manter_contato",label:"Manter Contato",color:"#94A3B8"},
  {key:"fechado",label:"Fechado",color:"#4ADE80"}
];

const KANBAN_STAGES=STAGES;
const CLOSED_STAGES=["fechado"];
const QUAL_STAGES=["qualificado","reuniao_agendada","reuniao_realizada","reagendamento","proposta_enviada","manter_contato","fechado"];
const AGEND_STAGES=["reuniao_agendada","reuniao_realizada","reagendamento","proposta_enviada","manter_contato","fechado"];

const NAV=[
  {key:"dashboard",label:"Dashboard",icon:LayoutDashboard},
  {key:"crm",label:"Pipeline",icon:Kanban},
  {key:"analytics",label:"Analytics",icon:BarChart3},
  {key:"tracking",label:"Tracking",icon:Radio},
  {key:"templates",label:"Templates",icon:MessageSquare},
  {key:"config",label:"Config",icon:Settings}
];

const fmt=v=>v!=null?v.toLocaleString("pt-BR",{style:"currency",currency:"BRL",minimumFractionDigits:0}):"R$ 0";
const pct=(a,b)=>b>0?Math.round((a/b)*100):0;
const timeAgo=d=>{if(!d)return"—";const ms=Date.now()-new Date(d).getTime(),h=Math.floor(ms/3600000),dy=Math.floor(h/24);return dy>0?`${dy}d`:h>0?`${h}h`:"agora";};
const isInactive=l=>l.stage==="novo"&&(Date.now()-new Date(l.created_at).getTime())/3600000>=2;
const bantBadge=s=>s>=4?"bg-amber-400/10 text-amber-400":s>=3?"bg-emerald-400/10 text-emerald-400":s>=2?"bg-yellow-400/10 text-yellow-400":"bg-red-400/10 text-red-400";
const WA=<svg width="12" height="12" viewBox="0 0 24 24" fill="#25D366"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/><path d="M12 0C5.373 0 0 5.373 0 12c0 2.625.846 5.059 2.284 7.034L.789 23.492l4.624-1.467A11.932 11.932 0 0012 24c6.627 0 12-5.373 12-12S18.627 0 12 0zm0 21.818c-2.168 0-4.19-.586-5.932-1.608l-.425-.253-2.742.87.888-2.664-.278-.442A9.78 9.78 0 012.182 12 9.818 9.818 0 0112 2.182 9.818 9.818 0 0121.818 12 9.818 9.818 0 0112 21.818z"/></svg>;

// ===== HOOKS =====
function useLeads(){const[ld,setLd]=useState([]);const[lo,setLo]=useState(true);const f=useCallback(async()=>{setLo(true);const{data}=await supabase.from("crm_leads").select("*").order("created_at",{ascending:false});if(data)setLd(data);setLo(false);},[]);useEffect(()=>{f();},[f]);
const up=async(id,u)=>{const{error}=await supabase.from("crm_leads").update(u).eq("id",id);if(!error)setLd(p=>p.map(l=>l.id===id?{...l,...u}:l));return!error;};
const add=async l=>{const{data,error}=await supabase.from("crm_leads").insert(l).select();if(!error&&data){setLd(p=>[data[0],...p]);return data[0];}return null;};
const del=async id=>{await supabase.from("crm_leads").delete().eq("id",id);setLd(p=>p.filter(l=>l.id!==id));};
return{leads:ld,loading:lo,refetch:f,updateLead:up,addLead:add,deleteLead:del};}

function useEventos(){const[e,se]=useState([]);const[l,sl]=useState(true);useEffect(()=>{(async()=>{const{data}=await supabase.from("crm_eventos").select("*").order("created_at",{ascending:false}).limit(50);if(data)se(data);sl(false);})();},[]);return{eventos:e,loading:l};}
function useEquipe(){const[eq,se]=useState([]);const[l,sl]=useState(true);const f=useCallback(async()=>{sl(true);const{data}=await supabase.from("crm_equipe").select("*").order("created_at");if(data)se(data);sl(false);},[]);useEffect(()=>{f();},[f]);const add=async m=>{const{data,error}=await supabase.from("crm_equipe").insert(m).select();if(!error&&data)se(p=>[...p,data[0]]);};const rm=async id=>{await supabase.from("crm_equipe").delete().eq("id",id);se(p=>p.filter(m=>m.id!==id));};const tog=async(id,a)=>{await supabase.from("crm_equipe").update({ativo:!a}).eq("id",id);se(p=>p.map(m=>m.id===id?{...m,ativo:!a}:m));};return{equipe:eq,loading:l,addMember:add,removeMember:rm,toggleActive:tog};}
function useConfig(){const[c,sc]=useState(null);useEffect(()=>{(async()=>{const{data}=await supabase.from("crm_config").select("*").eq("ativo",true).limit(1).single();if(data)sc(data);})();},[]);return c;}
function useTemplates(){const[t,st]=useState([]);const[l,sl]=useState(true);useEffect(()=>{(async()=>{const{data}=await supabase.from("crm_templates").select("*").eq("ativo",true).order("created_at");if(data)st(data);sl(false);})();},[]);const add=async m=>{const{data,error}=await supabase.from("crm_templates").insert(m).select();if(!error&&data)st(p=>[...p,data[0]]);};const rm=async id=>{await supabase.from("crm_templates").delete().eq("id",id);st(p=>p.filter(x=>x.id!==id));};return{templates:t,loading:l,addTemplate:add,removeTemplate:rm};}
function useAtividades(id){const[a,sa]=useState([]);useEffect(()=>{if(!id)return;(async()=>{const{data}=await supabase.from("crm_atividades").select("*").eq("lead_id",id).order("created_at",{ascending:false}).limit(20);if(data)sa(data);})();},[id]);const add=async(lid,tipo,desc)=>{const{data,error}=await supabase.from("crm_atividades").insert({lead_id:lid,tipo,descricao:desc}).select();if(!error&&data)sa(p=>[data[0],...p]);};return{atividades:a,addAtividade:add};}

// ===== UI =====
function Card({children,style={}}){return<div style={{background:BG2,border:`1px solid ${BORDER}`,borderRadius:12,...style}}>{children}</div>;}
function Spinner(){return<div className="flex items-center justify-center p-12"><Loader2 size={24} style={{color:GOLD,animation:"spin 1s linear infinite"}}/></div>;}
function Logo(){return<div style={{display:"flex",alignItems:"center",gap:2,userSelect:"none"}}><span style={{fontWeight:800,fontSize:22,color:TEXT1}}>HT</span><span style={{fontWeight:800,fontSize:22,background:`linear-gradient(135deg,${GOLD_LIGHT},${GOLD},${GOLD_DIM})`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>X</span></div>;}
function MC({icon:I,label,value,sub,accent}){return<Card style={{padding:14}}><div className="flex items-center gap-2" style={{marginBottom:6}}><div className="flex items-center justify-center" style={{width:30,height:30,borderRadius:8,background:accent?GOLD_BG2:"rgba(255,255,255,0.04)"}}><I size={14} style={{color:accent?GOLD:TEXT2}}/></div><span style={{fontSize:10,color:TEXT3,letterSpacing:"0.04em",textTransform:"uppercase"}}>{label}</span></div><div style={{fontSize:20,fontWeight:600,color:accent?GOLD_LIGHT:TEXT1}}>{value}</div>{sub&&<div style={{fontSize:10,color:TEXT3,marginTop:3}}>{sub}</div>}</Card>;}

function LeadCard({lead,onClick,equipe}){
const sdr=equipe.find(m=>m.nome===lead.sdr_nome);const closer=equipe.find(m=>m.nome===lead.closer_nome);const ina=isInactive(lead);
return<div draggable onDragStart={e=>e.dataTransfer.setData("leadId",lead.id)} onClick={()=>onClick?.(lead)} style={{background:BG3,border:`1px solid ${ina?"rgba(248,113,113,0.4)":BORDER}`,borderRadius:10,padding:10,marginBottom:6,cursor:"grab",animation:ina?"pulse 2s infinite":"none"}} onMouseEnter={e=>{if(!ina)e.currentTarget.style.borderColor=GOLD_DIM;}} onMouseLeave={e=>{e.currentTarget.style.borderColor=ina?"rgba(248,113,113,0.4)":BORDER;}}>
<div className="flex items-center justify-between" style={{marginBottom:4}}><span style={{fontSize:12,fontWeight:500,color:TEXT1}}>{lead.nome}</span>
<div className="flex items-center gap-1">{lead.utm_source==="meta"&&<div style={{width:14,height:14,borderRadius:3,background:"rgba(59,130,246,0.15)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:7,fontWeight:700,color:"#60A5FA"}}>M</div>}{lead.utm_source==="google"&&<div style={{width:14,height:14,borderRadius:3,background:"rgba(52,211,153,0.15)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:7,fontWeight:700,color:"#34D399"}}>G</div>}</div></div>
<div className="flex items-center justify-between" style={{marginBottom:3}}><div className="flex items-center gap-1" style={{fontSize:10,color:TEXT3}}><Phone size={9}/>{lead.telefone||"-"}</div><a href={`https://wa.me/${lead.telefone}`} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()} style={{width:22,height:22,borderRadius:5,background:"rgba(37,211,102,0.12)",display:"flex",alignItems:"center",justifyContent:"center",textDecoration:"none"}}>{WA}</a></div>
{lead.quali_score>0&&<div className="flex items-center gap-2" style={{marginTop:4}}><div className="flex gap-0.5">{[1,2,3,4].map(i=><div key={i} style={{height:2,width:14,borderRadius:1,background:i<=lead.quali_score?GOLD:"rgba(255,255,255,0.06)"}}/>)}</div><span className={`text-[9px] px-1 py-0.5 rounded font-semibold ${bantBadge(lead.quali_score)}`}>{lead.quali_score}/4</span></div>}
<div className="flex items-center gap-2" style={{marginTop:4}}>
{lead.valor_venda&&<span style={{fontSize:11,fontWeight:600,color:TEXT2}}>Venda: {fmt(lead.valor_venda)}</span>}
{lead.cash_collect&&<span style={{fontSize:11,fontWeight:700,color:"#4ADE80"}}>Cash: {fmt(lead.cash_collect)}</span>}
</div>
<div className="flex items-center justify-between" style={{marginTop:4}}>
<div className="flex items-center gap-1">{sdr&&<span style={{fontSize:8,padding:"1px 5px",borderRadius:8,background:`${sdr.cor||GOLD}18`,color:sdr.cor||GOLD,fontWeight:600}}>{sdr.nome.split(" ")[0]}</span>}{closer&&<span style={{fontSize:8,padding:"1px 5px",borderRadius:8,background:`${closer.cor||"#A78BFA"}18`,color:closer.cor||"#A78BFA",fontWeight:600}}>{closer.nome.split(" ")[0]}</span>}</div>
<span style={{fontSize:8,color:TEXT3}}>{timeAgo(lead.created_at)}</span></div>
{ina&&<div style={{marginTop:4,fontSize:8,color:"#F87171",fontWeight:600}}>⚠ Sem contato</div>}
</div>;}

function AddLeadModal({onClose,onAdd,equipe}){const[n,sn]=useState("");const[t,st]=useState("");const[e,se]=useState("");const[s,ss]=useState("");const[sav,sSav]=useState(false);const[err,sErr]=useState(null);const sdrs=equipe.filter(m=>m.papel==="sdr"&&m.ativo);
const save=async()=>{if(!n.trim()||!t.trim())return;sSav(true);sErr(null);let tel=t.replace(/\D/g,"");if(tel.length===11)tel="55"+tel;if(tel.length===10)tel="55"+tel;const{data:dup}=await supabase.from("crm_leads").select("id,nome,stage").eq("telefone",tel).limit(1);if(dup?.length){sErr(`Lead já existe: ${dup[0].nome} (${dup[0].stage})`);sSav(false);return;}
let asgn=s;if(!asgn&&sdrs.length>0){const ct={};sdrs.forEach(x=>{ct[x.nome]=0;});const{data:all}=await supabase.from("crm_leads").select("sdr_nome").not("sdr_nome","is",null);if(all)all.forEach(l=>{if(ct[l.sdr_nome]!==undefined)ct[l.sdr_nome]++;});let min=Infinity,pk=sdrs[0].nome;Object.entries(ct).forEach(([nm,c])=>{if(c<min){min=c;pk=nm;}});asgn=pk;}
await onAdd({nome:n.trim(),telefone:tel,email:e.trim()||null,stage:"novo",origem:"manual",sdr_nome:asgn||null});sSav(false);onClose();};
const IS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
return<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:16,background:"rgba(0,0,0,0.8)"}}><div style={{width:"100%",maxWidth:440,background:BG2,border:`1px solid ${BORDER2}`,borderRadius:16,padding:24}}>
<div className="flex items-center justify-between" style={{marginBottom:20}}><h3 style={{fontSize:16,fontWeight:600,color:TEXT1,margin:0}}>Novo lead</h3><button onClick={onClose} style={{padding:8,borderRadius:8,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:TEXT2}}><X size={16}/></button></div>
{err&&<div style={{padding:10,borderRadius:8,background:"rgba(248,113,113,0.1)",border:"1px solid rgba(248,113,113,0.2)",color:"#F87171",fontSize:12,marginBottom:12}}>{err}</div>}
<div style={{display:"flex",flexDirection:"column",gap:10}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Nome *</label><input value={n} onChange={ev=>sn(ev.target.value)} placeholder="Nome completo" style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>WhatsApp *</label><input value={t} onChange={ev=>st(ev.target.value)} placeholder="11999998888" style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Email</label><input value={e} onChange={ev=>se(ev.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>SDR (vazio = round-robin)</label><select value={s} onChange={ev=>ss(ev.target.value)} style={IS}><option value="">Automático</option>{sdrs.map(x=><option key={x.id} value={x.nome}>{x.nome}</option>)}</select></div></div>
<div className="flex gap-2" style={{marginTop:16}}><button onClick={save} disabled={sav} style={{flex:1,padding:10,borderRadius:8,border:"none",background:GOLD,color:BG,fontSize:13,fontWeight:600,cursor:"pointer",opacity:sav?.6:1}}>{sav?"Salvando...":"Adicionar"}</button><button onClick={onClose} style={{padding:"10px 20px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:13,cursor:"pointer"}}>Cancelar</button></div></div></div>;}

function LeadModal({lead,onClose,onUpdate,onDelete,equipe,templates}){
const[stage,setStage]=useState(lead.stage);const[qb,sQb]=useState(lead.quali_budget||false);const[qa,sQa]=useState(lead.quali_authority||false);const[qn,sQn]=useState(lead.quali_need||false);const[qt,sQt]=useState(lead.quali_timeline||false);const[val,sVal]=useState(lead.valor_venda||"");const[cash,sCash]=useState(lead.cash_collect||"");const[sdr,sSdr]=useState(lead.sdr_nome||"");const[closer,sCloser]=useState(lead.closer_nome||"");const[nota,sNota]=useState("");const[sav,sSav]=useState(false);const[tab,sTab]=useState("info");const[copied,sCopied]=useState(null);
const{atividades,addAtividade}=useAtividades(lead.id);const score=[qb,qa,qn,qt].filter(Boolean).length;
const sdrs=equipe.filter(m=>m.papel==="sdr"&&m.ativo);const closers=equipe.filter(m=>m.papel==="closer"&&m.ativo);
const save=async()=>{sSav(true);const u={stage,quali_score:score,quali_budget:qb,quali_authority:qa,quali_need:qn,quali_timeline:qt,valor_venda:val?parseFloat(val):null,cash_collect:cash?parseFloat(cash):null,sdr_nome:sdr||null,closer_nome:closer||null};if(stage!==lead.stage){await addAtividade(lead.id,"stage_change",`${lead.stage} → ${stage}`);if(stage==="contato_iniciado"&&!lead.contatado_at)u.contatado_at=new Date().toISOString();if(stage==="qualificado")u.qualificado_at=new Date().toISOString();if(stage==="reuniao_agendada")u.agendado_at=new Date().toISOString();if(stage==="fechado")u.venda_at=new Date().toISOString();}await onUpdate(lead.id,u);sSav(false);onClose();};
const addNota=async()=>{if(!nota.trim())return;await addAtividade(lead.id,"nota",nota.trim());sNota("");};
const copyTpl=t=>{const msg=t.mensagem.replace(/\{\{nome\}\}/g,lead.nome?.split(" ")[0]||"");navigator.clipboard.writeText(msg);sCopied(t.id);setTimeout(()=>sCopied(null),2000);};
const si=STAGES.find(x=>x.key===lead.stage);const SS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
return<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:16,background:"rgba(0,0,0,0.8)",backdropFilter:"blur(6px)"}}><div style={{width:"100%",maxWidth:600,background:BG2,border:`1px solid ${BORDER2}`,borderRadius:16,padding:24,maxHeight:"92vh",overflowY:"auto"}}>
<div className="flex items-center justify-between" style={{marginBottom:16}}><div><h3 style={{fontSize:18,fontWeight:600,color:TEXT1,margin:0}}>{lead.nome}</h3><div className="flex items-center gap-2" style={{marginTop:6}}><span style={{fontSize:11,padding:"3px 10px",borderRadius:20,background:`${si?.color}18`,color:si?.color,fontWeight:500}}>{si?.label}</span><span style={{fontSize:10,color:TEXT3}}>{timeAgo(lead.created_at)}</span></div></div>
<div className="flex items-center gap-2"><button onClick={()=>{if(confirm("Excluir?")){onDelete(lead.id);onClose();}}} style={{padding:8,borderRadius:8,border:"none",background:"rgba(248,113,113,0.1)",cursor:"pointer",color:"#F87171"}}><Trash2 size={14}/></button><a href={`https://wa.me/${lead.telefone}`} target="_blank" rel="noreferrer" style={{padding:8,borderRadius:8,background:"rgba(37,211,102,0.12)",display:"flex",alignItems:"center",justifyContent:"center"}}>{WA}</a><button onClick={onClose} style={{padding:8,borderRadius:8,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:TEXT2}}><X size={16}/></button></div></div>

<div className="flex gap-1" style={{marginBottom:16,background:"rgba(255,255,255,0.03)",borderRadius:8,padding:3}}>{[{k:"info",l:"Dados"},{k:"bant",l:"BANT"},{k:"notas",l:"Notas"},{k:"msgs",l:"Templates"}].map(t=><button key={t.k} onClick={()=>sTab(t.k)} style={{flex:1,padding:"7px 0",borderRadius:6,border:"none",fontSize:11,fontWeight:500,cursor:"pointer",background:tab===t.k?GOLD_BG2:"transparent",color:tab===t.k?GOLD:TEXT3}}>{t.l}</button>)}</div>

{tab==="info"&&<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:14}}>{[{l:"Email",v:lead.email||"—"},{l:"Telefone",v:lead.telefone||"—"},{l:"Campanha",v:lead.utm_campaign||"—"},{l:"Conjunto",v:lead.utm_term||"—"},{l:"Criativo",v:lead.utm_content||"—"},{l:"Fonte",v:lead.utm_source||"—"}].map(f=><div key={f.l} style={{background:BG3,border:`1px solid ${BORDER}`,borderRadius:8,padding:8}}><div style={{fontSize:9,color:TEXT3,textTransform:"uppercase",marginBottom:3}}>{f.l}</div><div style={{fontSize:12,color:TEXT1}}>{f.v}</div></div>)}</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:14}}>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Etapa</label><select value={stage} onChange={e=>setStage(e.target.value)} style={SS}>{STAGES.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></div>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>SDR</label><select value={sdr} onChange={e=>sSdr(e.target.value)} style={SS}><option value="">—</option>{sdrs.map(s=><option key={s.id} value={s.nome}>{s.nome}</option>)}</select></div>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Closer</label><select value={closer} onChange={e=>sCloser(e.target.value)} style={SS}><option value="">—</option>{closers.map(c=><option key={c.id} value={c.nome}>{c.nome}</option>)}</select></div>
<div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Valor da Venda (R$)</label><input type="number" value={val} onChange={e=>sVal(e.target.value)} placeholder="50000" style={SS}/></div>
<div style={{gridColumn:"1/-1"}}><label style={{fontSize:9,color:GOLD,textTransform:"uppercase",display:"block",marginBottom:3,fontWeight:600}}>Cash Collect (R$) — enviado ao Meta</label><input type="number" value={cash} onChange={e=>sCash(e.target.value)} placeholder="10000" style={{...SS,borderColor:`${GOLD}44`}}/></div>
</div></>}

{tab==="bant"&&<div style={{marginBottom:14}}><div style={{fontSize:11,color:TEXT2,marginBottom:10}}>Marque os critérios:</div>{BANT_ITEMS.map((b,i)=>{const ck=[qb,qa,qn,qt],st=[sQb,sQa,sQn,sQt];return<div key={b.key} onClick={()=>st[i](!ck[i])} style={{display:"flex",alignItems:"center",gap:10,padding:10,borderRadius:8,border:`1px solid ${ck[i]?`${GOLD}44`:BORDER}`,background:ck[i]?GOLD_BG:"transparent",marginBottom:6,cursor:"pointer"}}><div style={{width:22,height:22,borderRadius:5,border:`2px solid ${ck[i]?GOLD:"rgba(255,255,255,0.15)"}`,display:"flex",alignItems:"center",justifyContent:"center",background:ck[i]?GOLD_BG2:"transparent"}}>{ck[i]&&<Check size={13} style={{color:GOLD}}/>}</div><div><div style={{fontSize:12,fontWeight:500,color:ck[i]?GOLD_LIGHT:TEXT1}}>{b.label}</div><div style={{fontSize:10,color:TEXT3,marginTop:1}}>{b.desc}</div></div></div>;})}
<div className="flex items-center gap-3" style={{marginTop:10,padding:10,borderRadius:8,background:BG3}}><span style={{fontSize:11,color:TEXT3}}>Score:</span><div className="flex gap-1">{[1,2,3,4].map(i=><div key={i} style={{width:22,height:5,borderRadius:2,background:i<=score?GOLD:"rgba(255,255,255,0.06)"}}/>)}</div><span className={`px-2 py-0.5 rounded text-xs font-bold ${bantBadge(score)}`}>{score}/4</span></div></div>}

{tab==="notas"&&<div style={{marginBottom:14}}><div className="flex gap-2" style={{marginBottom:10}}><input value={nota} onChange={e=>sNota(e.target.value)} placeholder="Adicionar nota..." style={{...SS,flex:1}} onKeyDown={e=>{if(e.key==="Enter")addNota();}}/><button onClick={addNota} style={{padding:"8px 14px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:11,fontWeight:500,cursor:"pointer"}}>Salvar</button></div>{atividades.length===0&&<div style={{fontSize:12,color:TEXT3,textAlign:"center",padding:16}}>Nenhuma atividade</div>}{atividades.map(a=><div key={a.id} style={{padding:8,borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:4}}><div className="flex items-center justify-between"><span style={{fontSize:9,color:a.tipo==="stage_change"?"#A78BFA":GOLD,fontWeight:600,textTransform:"uppercase"}}>{a.tipo.replace("_"," ")}</span><span style={{fontSize:8,color:TEXT3}}>{new Date(a.created_at).toLocaleString("pt-BR")}</span></div><div style={{fontSize:11,color:TEXT1,marginTop:3}}>{a.descricao}</div></div>)}</div>}

{tab==="msgs"&&<div style={{marginBottom:14}}>{templates.length===0&&<div style={{fontSize:12,color:TEXT3,textAlign:"center",padding:16}}>Nenhum template</div>}{templates.map(t=>{const msg=t.mensagem.replace(/\{\{nome\}\}/g,lead.nome?.split(" ")[0]||"");return<div key={t.id} style={{padding:10,borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:6,background:BG3}}><div className="flex items-center justify-between" style={{marginBottom:4}}><span style={{fontSize:11,fontWeight:500,color:GOLD}}>{t.titulo}</span><button onClick={()=>copyTpl(t)} style={{display:"flex",alignItems:"center",gap:3,padding:"3px 8px",borderRadius:5,border:"none",background:copied===t.id?"rgba(74,222,128,0.15)":GOLD_BG2,color:copied===t.id?"#4ADE80":GOLD,fontSize:9,fontWeight:500,cursor:"pointer"}}>{copied===t.id?<><Check size={9}/>Copiado</>:<><Copy size={9}/>Copiar</>}</button></div><div style={{fontSize:11,color:TEXT2,lineHeight:1.4}}>{msg}</div></div>;})}</div>}

<div className="flex gap-2"><button onClick={save} disabled={sav} style={{flex:1,padding:10,borderRadius:8,border:"none",background:GOLD,color:BG,fontSize:13,fontWeight:600,cursor:"pointer",opacity:sav?.6:1}}>{sav?"Salvando...":"Salvar"}</button><button onClick={onClose} style={{padding:"10px 20px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:13,cursor:"pointer"}}>Cancelar</button></div></div></div>;}

// ===== PAGES =====
function DashboardPage({leads,config}){
const total=leads.length;const qual=leads.filter(l=>QUAL_STAGES.includes(l.stage)).length;const agend=leads.filter(l=>AGEND_STAGES.includes(l.stage)).length;const vendas=leads.filter(l=>l.stage==="fechado");const rec=vendas.reduce((s,l)=>s+(l.valor_venda||0),0);const cc=vendas.reduce((s,l)=>s+(l.cash_collect||0),0);const tm=vendas.length>0?Math.round(rec/vendas.length):0;const gasto=config?.gasto_ads_mensal||0;const meta=config?.meta_mensal||0;
const forecast=useMemo(()=>{const tQ=total>0?qual/total:0,tA=qual>0?agend/qual:0,tV=agend>0?vendas.length/agend:0;const eA=leads.filter(l=>["reuniao_agendada","reuniao_realizada","proposta_enviada"].includes(l.stage)).length;const eQ=leads.filter(l=>l.stage==="qualificado").length;return Math.round((eA*tV*tm)+(eQ*tA*tV*tm));},[leads]);
const funnel=[{label:"Leads",value:total,color:GOLD,rate:100},{label:"Qualificados",value:qual,color:"#34D399",rate:pct(qual,total)},{label:"Agendados",value:agend,color:"#A78BFA",rate:pct(agend,total)},{label:"Fechados",value:vendas.length,color:"#4ADE80",rate:pct(vendas.length,total)}];
const daily=useMemo(()=>{const m={};leads.forEach(l=>{const d=new Date(l.created_at).toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"});if(!m[d])m[d]={dia:d,leads:0};m[d].leads++;});return Object.values(m).slice(-14);},[leads]);
const FB=({label,value,maxVal,color,rate})=>{const w=maxVal>0?(value/maxVal)*100:0;return<div className="flex items-center gap-3" style={{padding:"4px 0"}}><div style={{width:90,textAlign:"right",flexShrink:0,fontSize:11,color:TEXT2}}>{label}</div><div className="flex-1 overflow-hidden" style={{height:24,borderRadius:5,background:"rgba(255,255,255,0.03)"}}><div className="flex items-center" style={{height:"100%",width:`${Math.max(w,4)}%`,borderRadius:5,background:color,opacity:.85,paddingLeft:6}}><span style={{fontSize:10,fontWeight:600,color:"#fff"}}>{value}</span></div></div><div style={{width:36,textAlign:"right",flexShrink:0,fontSize:10,color:TEXT3}}>{rate}%</div></div>;};
return<div style={{display:"flex",flexDirection:"column",gap:14}}>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10}}><MC icon={Users} label="Leads" value={total} accent/><MC icon={UserCheck} label="Qualificados" value={qual} sub={`${pct(qual,total)}%`}/><MC icon={Calendar} label="Agendados" value={agend}/><MC icon={DollarSign} label="Fechados" value={vendas.length} sub={`${pct(vendas.length,total)}%`}/></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10}}><MC icon={DollarSign} label="Receita" value={fmt(rec)} accent/><MC icon={DollarSign} label="Cash Collect" value={fmt(cc)} sub="recebido"/><MC icon={Zap} label="Forecast" value={fmt(forecast)} sub="pipeline"/><MC icon={TrendingUp} label="Leads/venda" value={vendas.length>0?Math.round(total/vendas.length):"—"}/></div>
{gasto>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10}}><MC icon={DollarSign} label="CPL" value={total>0?fmt(Math.round(gasto/total)):"—"}/><MC icon={Target} label="CPL Qualif." value={qual>0?fmt(Math.round(gasto/qual)):"—"}/><MC icon={Calendar} label="Custo/Agend." value={agend>0?fmt(Math.round(gasto/agend)):"—"}/><MC icon={DollarSign} label="CAC" value={vendas.length>0?fmt(Math.round(gasto/vendas.length)):"—"}/></div>}
{meta>0&&<Card style={{padding:14}}><div className="flex items-center justify-between" style={{marginBottom:6}}><span style={{fontSize:10,color:TEXT3,textTransform:"uppercase"}}>Meta mensal</span><span style={{fontSize:10,color:TEXT2}}>{fmt(cc)} / {fmt(meta)}</span></div><div style={{height:7,borderRadius:3,background:"rgba(255,255,255,0.04)",overflow:"hidden"}}><div style={{height:"100%",borderRadius:3,background:cc>=meta?"linear-gradient(90deg,#4ADE80,#22c55e)":`linear-gradient(90deg,${GOLD},${GOLD_LIGHT})`,width:`${Math.min((cc/meta)*100,100)}%`}}/></div><div style={{fontSize:18,fontWeight:600,color:cc>=meta?"#4ADE80":GOLD_LIGHT,marginTop:6}}>{meta>0?Math.round((cc/meta)*100):0}%</div></Card>}
<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:10}}>Funil</h3>{funnel.map(f=><FB key={f.label} {...f} maxVal={total}/>)}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6,marginTop:12,paddingTop:12,borderTop:`1px solid ${BORDER}`}}>{[{v:vendas.length>0?Math.round(total/vendas.length):"—",l:"Leads/venda"},{v:vendas.length>0?Math.round(qual/vendas.length):"—",l:"Qualif./venda"},{v:vendas.length>0?Math.round(agend/vendas.length):"—",l:"Agend./venda"}].map(m=><div key={m.l} style={{textAlign:"center"}}><div style={{fontSize:18,fontWeight:600,color:GOLD_LIGHT}}>{m.v}</div><div style={{fontSize:8,color:TEXT3,marginTop:2}}>{m.l}</div></div>)}</div></Card>
{daily.length>0&&<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:10}}>Leads/dia</h3><ResponsiveContainer width="100%" height={180}><AreaChart data={daily}><defs><linearGradient id="gL" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={GOLD} stopOpacity={.25}/><stop offset="95%" stopColor={GOLD} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)"/><XAxis dataKey="dia" tick={{fill:TEXT3,fontSize:9}} axisLine={false} tickLine={false}/><YAxis tick={{fill:TEXT3,fontSize:9}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:8,color:TEXT1,fontSize:10}}/><Area type="monotone" dataKey="leads" stroke={GOLD} fill="url(#gL)" strokeWidth={2}/></AreaChart></ResponsiveContainer></Card>}
</div>;}

function CRMPage({leads,onLeadClick,onUpdate,equipe,onAdd}){const[search,sSearch]=useState("");const[filterSdr,sFilter]=useState("");const[showAdd,sShowAdd]=useState(false);const[dragOver,sDragOver]=useState(null);
const filtered=useMemo(()=>{let f=leads;if(search){const s=search.toLowerCase();f=f.filter(l=>(l.nome||"").toLowerCase().includes(s)||(l.telefone||"").includes(s)||(l.utm_campaign||"").toLowerCase().includes(s));}if(filterSdr)f=f.filter(l=>l.sdr_nome===filterSdr);return f;},[leads,search,filterSdr]);
const grouped=useMemo(()=>{const g={};KANBAN_STAGES.forEach(s=>{g[s.key]=[];});filtered.forEach(l=>{if(g[l.stage])g[l.stage].push(l);});return g;},[filtered]);
const sdrs=[...new Set(leads.map(l=>l.sdr_nome).filter(Boolean))];
const handleDrop=async(sk,e)=>{e.preventDefault();sDragOver(null);const id=e.dataTransfer.getData("leadId");if(!id)return;const u={stage:sk};if(sk==="contato_iniciado")u.contatado_at=new Date().toISOString();if(sk==="qualificado")u.qualificado_at=new Date().toISOString();if(sk==="reuniao_agendada")u.agendado_at=new Date().toISOString();if(sk==="fechado")u.venda_at=new Date().toISOString();await onUpdate(id,u);};
return<div><div className="flex flex-wrap items-center gap-2" style={{marginBottom:14}}><div style={{position:"relative",flex:"1 1 180px"}}><Search size={13} style={{position:"absolute",left:9,top:"50%",transform:"translateY(-50%)",color:TEXT3}}/><input value={search} onChange={e=>sSearch(e.target.value)} placeholder="Buscar..." style={{width:"100%",padding:"7px 7px 7px 30px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:11,outline:"none"}}/></div><select value={filterSdr} onChange={e=>sFilter(e.target.value)} style={{padding:"7px 10px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:11,outline:"none"}}><option value="">Todos SDRs</option>{sdrs.map(s=><option key={s} value={s}>{s}</option>)}</select><button onClick={()=>sShowAdd(true)} style={{display:"flex",alignItems:"center",gap:5,padding:"7px 14px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:11,fontWeight:500,cursor:"pointer"}}><Plus size={13}/>Novo lead</button></div>
<div className="flex gap-2 overflow-x-auto pb-4" style={{minHeight:500}}>{KANBAN_STAGES.map(stage=>{const sl=grouped[stage.key]||[];const sv=sl.reduce((s,l)=>s+(l.cash_collect||0),0);const vv=sl.reduce((s,l)=>s+(l.valor_venda||0),0);return<div key={stage.key} onDragOver={e=>{e.preventDefault();sDragOver(stage.key);}} onDragLeave={()=>sDragOver(null)} onDrop={e=>handleDrop(stage.key,e)} style={{width:210,minWidth:210,flexShrink:0,background:dragOver===stage.key?"rgba(201,168,76,0.04)":BG2,border:`1px solid ${dragOver===stage.key?GOLD_DIM:BORDER}`,borderRadius:10,padding:10,transition:"all 0.2s"}}><div className="flex items-center justify-between" style={{marginBottom:6,padding:"0 2px"}}><div className="flex items-center gap-1.5"><div style={{width:7,height:7,borderRadius:"50%",background:stage.color}}/><span style={{fontSize:10,fontWeight:500,color:TEXT2}}>{stage.label}</span></div><span style={{fontSize:10,padding:"1px 6px",borderRadius:5,background:"rgba(255,255,255,0.04)",color:TEXT3}}>{sl.length}</span></div>{(vv>0||sv>0)&&<div style={{fontSize:9,color:TEXT3,marginBottom:6,paddingLeft:3}}>{vv>0&&<span>Venda: {fmt(vv)} </span>}{sv>0&&<span style={{color:GOLD_DIM}}>Cash: {fmt(sv)}</span>}</div>}{sl.map(lead=><LeadCard key={lead.id} lead={lead} onClick={onLeadClick} equipe={equipe}/>)}</div>;})}
</div>{showAdd&&<AddLeadModal onClose={()=>sShowAdd(false)} onAdd={onAdd} equipe={equipe}/>}</div>;}

function AnalyticsPage({leads,config}){const[tab,sTab]=useState("campanha");const[compare,sCompare]=useState(false);const gasto=config?.gasto_ads_mensal||0;
function agg(data,field){const m={};data.forEach(l=>{const k=l[field]||"—";if(!m[k])m[k]={name:k,leads:0,qualificados:0,agendados:0,vendas:0,receita:0,cash:0};m[k].leads++;if(QUAL_STAGES.includes(l.stage))m[k].qualificados++;if(AGEND_STAGES.includes(l.stage))m[k].agendados++;if(l.stage==="fechado"){m[k].vendas++;m[k].receita+=l.valor_venda||0;m[k].cash+=l.cash_collect||0;}});return Object.values(m).sort((a,b)=>b.cash-a.cash);}
const fm={campanha:"utm_campaign",conjunto:"utm_term",criativo:"utm_content"};const ad=useMemo(()=>agg(leads,fm[tab]),[leads,tab]);
const sdrs=useMemo(()=>{const m={};leads.filter(l=>l.sdr_nome).forEach(l=>{if(!m[l.sdr_nome])m[l.sdr_nome]={name:l.sdr_nome,leads:0,qualificados:0,agendados:0};m[l.sdr_nome].leads++;if(QUAL_STAGES.includes(l.stage))m[l.sdr_nome].qualificados++;if(AGEND_STAGES.includes(l.stage))m[l.sdr_nome].agendados++;});return Object.values(m);},[leads]);
const closers=useMemo(()=>{const m={};leads.filter(l=>l.closer_nome).forEach(l=>{if(!m[l.closer_nome])m[l.closer_nome]={name:l.closer_nome,reunioes:0,vendas:0,receita:0,cash:0};if(["reuniao_realizada","proposta_enviada","fechado","manter_contato"].includes(l.stage))m[l.closer_nome].reunioes++;if(l.stage==="fechado"){m[l.closer_nome].vendas++;m[l.closer_nome].receita+=l.valor_venda||0;m[l.closer_nome].cash+=l.cash_collect||0;}});return Object.values(m).sort((a,b)=>b.cash-a.cash);},[leads]);
const now=new Date();const thisM=leads.filter(l=>{const d=new Date(l.created_at);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();});const lastM=leads.filter(l=>{const d=new Date(l.created_at);const lm=new Date(now.getFullYear(),now.getMonth()-1);return d.getMonth()===lm.getMonth()&&d.getFullYear()===lm.getFullYear();});
const tmV=thisM.filter(l=>l.stage==="fechado"),lmV=lastM.filter(l=>l.stage==="fechado");

return<div style={{display:"flex",flexDirection:"column",gap:14}}>
{compare&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Card style={{padding:14}}><div style={{fontSize:9,color:TEXT3,textTransform:"uppercase",marginBottom:6}}>Este mês</div><div style={{fontSize:18,fontWeight:600,color:GOLD_LIGHT}}>{fmt(tmV.reduce((s,l)=>s+(l.cash_collect||0),0))}</div><div style={{fontSize:10,color:TEXT2,marginTop:3}}>{thisM.length} leads • {tmV.length} vendas</div></Card><Card style={{padding:14}}><div style={{fontSize:9,color:TEXT3,textTransform:"uppercase",marginBottom:6}}>Mês passado</div><div style={{fontSize:18,fontWeight:600,color:TEXT2}}>{fmt(lmV.reduce((s,l)=>s+(l.cash_collect||0),0))}</div><div style={{fontSize:10,color:TEXT3,marginTop:3}}>{lastM.length} leads • {lmV.length} vendas</div></Card></div>}

<Card style={{padding:18}}>
<div className="flex items-center justify-between" style={{marginBottom:14}}><div className="flex items-center gap-3"><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,margin:0}}>Ads</h3><button onClick={()=>sCompare(!compare)} style={{display:"flex",alignItems:"center",gap:3,padding:"3px 8px",borderRadius:5,border:"none",background:compare?GOLD_BG2:"rgba(255,255,255,0.03)",color:compare?GOLD:TEXT3,fontSize:9,cursor:"pointer"}}><ArrowRightLeft size={9}/>Comparar</button></div><div className="flex gap-1" style={{background:"rgba(255,255,255,0.03)",borderRadius:8,padding:3}}>{["campanha","conjunto","criativo"].map(t=><button key={t} onClick={()=>sTab(t)} style={{padding:"5px 12px",borderRadius:5,border:"none",fontSize:10,fontWeight:500,cursor:"pointer",background:tab===t?GOLD_BG2:"transparent",color:tab===t?GOLD:TEXT3}}>{t.charAt(0).toUpperCase()+t.slice(1)}</button>)}</div></div>
<div style={{overflowX:"auto"}}><table style={{width:"100%",fontSize:11,borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${BORDER}`}}>{[tab.charAt(0).toUpperCase()+tab.slice(1),"Leads","Qualif.","Vendas","Receita","Cash Collect","ROAS","% Qual.","% Venda"].map(h=><th key={h} style={{textAlign:"left",padding:"6px 6px",fontWeight:500,color:TEXT3,fontSize:9,textTransform:"uppercase"}}>{h}</th>)}</tr></thead>
<tbody>{ad.map((r,i)=>{const roas=gasto>0&&r.cash>0?(r.cash/(gasto*(r.leads/leads.length))).toFixed(1):"—";return<tr key={i} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"8px 6px",color:TEXT1,fontWeight:500,maxWidth:120,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{r.name}</td><td style={{padding:"8px 6px",color:TEXT2}}>{r.leads}</td><td style={{padding:"8px 6px",color:TEXT2}}>{r.qualificados}</td><td style={{padding:"8px 6px",color:"#4ADE80",fontWeight:500}}>{r.vendas}</td><td style={{padding:"8px 6px",color:TEXT2}}>{fmt(r.receita)}</td><td style={{padding:"8px 6px",color:"#4ADE80",fontWeight:600}}>{fmt(r.cash)}</td><td style={{padding:"8px 6px"}}><span style={{padding:"2px 6px",borderRadius:4,fontSize:9,fontWeight:600,background:roas!=="—"&&parseFloat(roas)>=2?"rgba(74,222,128,0.1)":GOLD_BG,color:roas!=="—"&&parseFloat(roas)>=2?"#4ADE80":GOLD}}>{roas}x</span></td><td style={{padding:"8px 6px",color:TEXT2}}>{pct(r.qualificados,r.leads)}%</td><td style={{padding:"8px 6px",color:TEXT2}}>{pct(r.vendas,r.leads)}%</td></tr>})}</tbody></table></div></Card>

<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:14}}>Cash Collect/{tab}</h3><ResponsiveContainer width="100%" height={Math.max(ad.length*36+40,120)}><BarChart data={ad} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)"/><XAxis type="number" tick={{fill:TEXT3,fontSize:9}} axisLine={false} tickLine={false} tickFormatter={v=>`R$${Math.round(v/1000)}k`}/><YAxis type="category" dataKey="name" tick={{fill:TEXT2,fontSize:9}} axisLine={false} tickLine={false} width={120}/><Tooltip contentStyle={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:8,color:TEXT1,fontSize:10}} formatter={v=>fmt(v)}/><Bar dataKey="cash" fill={GOLD} radius={[0,4,4,0]} barSize={16} name="Cash Collect"/></BarChart></ResponsiveContainer></Card>

<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:14}}>SDRs</h3><table style={{width:"100%",fontSize:11,borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${BORDER}`}}>{["SDR","Leads","Qualif.","% Qual."].map(h=><th key={h} style={{textAlign:"left",padding:"6px",fontWeight:500,color:TEXT3,fontSize:9,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{sdrs.map(s=><tr key={s.name} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"8px 6px",color:TEXT1,fontWeight:500}}>{s.name}</td><td style={{padding:"8px 6px",color:TEXT2}}>{s.leads}</td><td style={{padding:"8px 6px",color:TEXT2}}>{s.qualificados}</td><td style={{padding:"8px 6px"}}><span style={{padding:"2px 6px",borderRadius:4,fontSize:9,fontWeight:600,background:pct(s.qualificados,s.leads)>=35?"rgba(74,222,128,0.1)":GOLD_BG,color:pct(s.qualificados,s.leads)>=35?"#4ADE80":GOLD}}>{pct(s.qualificados,s.leads)}%</span></td></tr>)}</tbody></table></Card>
<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:14}}>Closers</h3><table style={{width:"100%",fontSize:11,borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${BORDER}`}}>{["Closer","Reuniões","Vendas","Cash","Fech."].map(h=><th key={h} style={{textAlign:"left",padding:"6px",fontWeight:500,color:TEXT3,fontSize:9,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{closers.map(c=><tr key={c.name} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"8px 6px",color:TEXT1,fontWeight:500}}>{c.name}</td><td style={{padding:"8px 6px",color:TEXT2}}>{c.reunioes}</td><td style={{padding:"8px 6px",color:"#4ADE80",fontWeight:500}}>{c.vendas}</td><td style={{padding:"8px 6px",color:"#4ADE80"}}>{fmt(c.cash)}</td><td style={{padding:"8px 6px"}}><span style={{padding:"2px 6px",borderRadius:4,fontSize:9,fontWeight:600,background:pct(c.vendas,c.reunioes)>=30?"rgba(74,222,128,0.1)":GOLD_BG,color:pct(c.vendas,c.reunioes)>=30?"#4ADE80":GOLD}}>{pct(c.vendas,c.reunioes)}%</span></td></tr>)}</tbody></table></Card>
</div></div>;}

function TrackingPage({eventos}){const t=eventos.length,s=eventos.filter(e=>e.sucesso).length,er=eventos.filter(e=>!e.sucesso).length;const bt=useMemo(()=>{const m={};eventos.forEach(e=>{m[e.evento]=(m[e.evento]||0)+1;});return Object.entries(m).map(([k,v])=>({name:k,value:v}));},[eventos]);const cl={Lead:GOLD,QualifiedLead:"#34D399",Schedule:"#A78BFA",Purchase:"#4ADE80"};
return<div style={{display:"flex",flexDirection:"column",gap:14}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10}}><MC icon={Zap} label="Eventos" value={t} accent/><MC icon={Check} label="Sucesso" value={`${pct(s,t)}%`}/><MC icon={AlertTriangle} label="Erros" value={er}/></div>
<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:14}}>Por tipo</h3><ResponsiveContainer width="100%" height={150}><BarChart data={bt}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)"/><XAxis dataKey="name" tick={{fill:TEXT2,fontSize:9}} axisLine={false} tickLine={false}/><YAxis tick={{fill:TEXT3,fontSize:9}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:8,color:TEXT1,fontSize:10}}/><Bar dataKey="value" radius={[4,4,0,0]} barSize={32}>{bt.map((e,i)=><Cell key={i} fill={cl[e.name]||GOLD}/>)}</Bar></BarChart></ResponsiveContainer></Card>
<Card style={{padding:18}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:14}}>Log</h3><table style={{width:"100%",fontSize:11,borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${BORDER}`}}>{["Evento","Plataforma","Status","Data"].map(h=><th key={h} style={{textAlign:"left",padding:"6px",fontWeight:500,color:TEXT3,fontSize:9,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{eventos.map(e=><tr key={e.id} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"8px 6px"}}><span style={{padding:"2px 8px",borderRadius:16,fontSize:9,fontWeight:500,background:`${cl[e.evento]||GOLD}15`,color:cl[e.evento]||GOLD}}>{e.evento}</span></td><td style={{padding:"8px 6px",color:TEXT2,textTransform:"capitalize"}}>{e.plataforma}</td><td style={{padding:"8px 6px"}}>{e.sucesso?<span className="flex items-center gap-1" style={{color:"#4ADE80"}}><Check size={11}/>OK</span>:<span className="flex items-center gap-1" style={{color:"#F87171"}}><X size={11}/>{e.erro}</span>}</td><td style={{padding:"8px 6px",color:TEXT3}}>{new Date(e.created_at).toLocaleString("pt-BR")}</td></tr>)}</tbody></table></Card></div>;}

function TemplatesPage({templates,loading,addTemplate,removeTemplate}){const[show,sShow]=useState(false);const[ti,sTi]=useState("");const[ms,sMs]=useState("");const[ca,sCa]=useState("outro");const cats={primeira_abordagem:"1ª abordagem",followup:"Follow-up",agendamento:"Agendamento",recontato:"Recontato",no_show:"No-show",outro:"Outro"};const IS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
const add=async()=>{if(!ti.trim()||!ms.trim())return;await addTemplate({titulo:ti,mensagem:ms,categoria:ca,ativo:true});sTi("");sMs("");sShow(false);};
return<div style={{display:"flex",flexDirection:"column",gap:14}}><div className="flex items-center justify-between"><h3 style={{fontSize:12,fontWeight:500,color:TEXT2}}>Use <code style={{color:GOLD}}>{"{{nome}}"}</code> pra nome do lead</h3><button onClick={()=>sShow(!show)} style={{display:"flex",alignItems:"center",gap:5,padding:"7px 14px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:11,fontWeight:500,cursor:"pointer"}}><Plus size={13}/>Novo</button></div>
{show&&<Card style={{padding:14}}><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:8,marginBottom:8}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Título</label><input value={ti} onChange={e=>sTi(e.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Categoria</label><select value={ca} onChange={e=>sCa(e.target.value)} style={IS}>{Object.entries(cats).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div></div><div style={{marginBottom:8}}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Mensagem</label><textarea value={ms} onChange={e=>sMs(e.target.value)} rows={3} style={{...IS,resize:"vertical"}}/></div><div className="flex gap-2"><button onClick={add} style={{padding:"8px 16px",borderRadius:8,border:"none",background:GOLD,color:BG,fontSize:12,fontWeight:600,cursor:"pointer"}}>Salvar</button><button onClick={()=>sShow(false)} style={{padding:"8px 16px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:12,cursor:"pointer"}}>Cancelar</button></div></Card>}
{loading?<Spinner/>:templates.map(t=><Card key={t.id} style={{padding:14}}><div className="flex items-center justify-between" style={{marginBottom:6}}><div className="flex items-center gap-2"><span style={{fontSize:12,fontWeight:500,color:GOLD}}>{t.titulo}</span><span style={{fontSize:8,padding:"2px 6px",borderRadius:8,background:"rgba(255,255,255,0.04)",color:TEXT3}}>{cats[t.categoria]||t.categoria}</span></div><button onClick={()=>removeTemplate(t.id)} style={{padding:5,borderRadius:5,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:"#F87171"}}><Trash2 size={11}/></button></div><div style={{fontSize:11,color:TEXT2,lineHeight:1.5}}>{t.mensagem}</div></Card>)}</div>;}

function ConfigPage({equipe,eqLoading,addMember,removeMember,toggleActive,config}){const[show,sShow]=useState(false);const[fn,sFn]=useState("");const[fp,sFp]=useState("sdr");const[ft,sFt]=useState("");const[fe,sFe]=useState("");const[fc,sFc]=useState(TEAM_COLORS[0]);const IS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
const add=async()=>{if(!fn.trim())return;await addMember({nome:fn,papel:fp,telefone:ft,email:fe,cor:fc,ativo:true});sFn("");sFt("");sFe("");sShow(false);};
return<div style={{display:"flex",flexDirection:"column",gap:14}}>
<Card style={{padding:20}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,marginBottom:16}}>Pixel & Meta</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,maxWidth:560}}>{[{l:"Pixel ID",v:config?.meta_pixel_id||"—"},{l:"Token",v:config?.meta_access_token?"••••••••":"—"},{l:"Test Code",v:config?.meta_test_event_code||"Produção"},{l:"Domínio",v:config?.dominio||"—"},{l:"Meta Mensal",v:config?.meta_mensal?fmt(config.meta_mensal):"—"},{l:"Gasto Ads",v:config?.gasto_ads_mensal?fmt(config.gasto_ads_mensal):"—"}].map(f=><div key={f.l}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>{f.l}</label><div style={{padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,fontSize:12,color:TEXT2}}>{f.v}</div></div>)}</div></Card>
<Card style={{padding:20}}><div className="flex items-center justify-between" style={{marginBottom:16}}><h3 style={{fontSize:12,fontWeight:500,color:TEXT2,margin:0}}>Equipe</h3><button onClick={()=>sShow(!show)} style={{display:"flex",alignItems:"center",gap:5,padding:"7px 14px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:11,fontWeight:500,cursor:"pointer"}}><Plus size={13}/>Adicionar</button></div>
{show&&<div style={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:10,padding:14,marginBottom:14}}><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:8,marginBottom:8}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Nome</label><input value={fn} onChange={e=>sFn(e.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Papel</label><select value={fp} onChange={e=>sFp(e.target.value)} style={IS}><option value="sdr">SDR</option><option value="closer">Closer</option></select></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:8}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Telefone</label><input value={ft} onChange={e=>sFt(e.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Email</label><input value={fe} onChange={e=>sFe(e.target.value)} style={IS}/></div></div><div style={{marginBottom:10}}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:3}}>Cor</label><div className="flex gap-2">{TEAM_COLORS.map(c=><div key={c} onClick={()=>sFc(c)} style={{width:24,height:24,borderRadius:5,background:c,cursor:"pointer",border:fc===c?`2px solid ${TEXT1}`:"2px solid transparent"}}/>)}</div></div><div className="flex gap-2"><button onClick={add} style={{padding:"7px 16px",borderRadius:8,border:"none",background:GOLD,color:BG,fontSize:12,fontWeight:600,cursor:"pointer"}}>Salvar</button><button onClick={()=>sShow(false)} style={{padding:"7px 16px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:12,cursor:"pointer"}}>Cancelar</button></div></div>}
{eqLoading?<Spinner/>:["sdr","closer"].map(papel=>{const members=equipe.filter(m=>m.papel===papel);return<div key={papel} style={{marginBottom:16}}><div className="flex items-center gap-2" style={{marginBottom:8}}>{papel==="sdr"?<Phone size={13} style={{color:GOLD}}/>:<Award size={13} style={{color:GOLD}}/>}<span style={{fontSize:11,fontWeight:600,color:GOLD,textTransform:"uppercase"}}>{papel==="sdr"?"SDRs":"Closers"}</span><span style={{fontSize:9,color:TEXT3}}>({members.length})</span></div>{members.length===0&&<div style={{fontSize:11,color:TEXT3,padding:"8px 0"}}>Nenhum</div>}{members.map(m=><div key={m.id} className="flex items-center justify-between" style={{padding:"8px 10px",borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:5,opacity:m.ativo?1:.5}}><div className="flex items-center gap-3"><div style={{width:30,height:30,borderRadius:"50%",background:`${m.cor||GOLD}22`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:600,color:m.cor||GOLD,border:`2px solid ${m.cor||GOLD}`}}>{m.nome.split(" ").map(n=>n[0]).join("").slice(0,2)}</div><div><div style={{fontSize:12,fontWeight:500,color:TEXT1}}>{m.nome}</div><div style={{fontSize:9,color:TEXT3}}>{m.telefone||""}{m.email?` • ${m.email}`:""}</div></div></div><div className="flex items-center gap-1"><button onClick={()=>toggleActive(m.id,m.ativo)} style={{padding:5,borderRadius:5,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:m.ativo?"#4ADE80":TEXT3}}>{m.ativo?<Eye size={13}/>:<EyeOff size={13}/>}</button><button onClick={()=>removeMember(m.id)} style={{padding:5,borderRadius:5,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:"#F87171"}}><Trash2 size={13}/></button></div></div>)}</div>;})}
</Card></div>;}

// ===== APP =====
export default function App(){const[page,sPage]=useState("dashboard");const[sel,sSel]=useState(null);const{leads,loading:ll,refetch,updateLead,addLead,deleteLead}=useLeads();const{eventos,loading:el}=useEventos();const{equipe,loading:eql,addMember,removeMember,toggleActive}=useEquipe();const{templates,loading:tl,addTemplate,removeTemplate}=useTemplates();const config=useConfig();const vendas=leads.filter(l=>l.stage==="fechado");
return<div className="flex" style={{minHeight:"100vh",background:BG,fontFamily:"'DM Sans',system-ui,sans-serif",color:TEXT1}}><style>{`@keyframes spin{to{transform:rotate(360deg)}}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.6}}`}</style>
<aside className="hidden md:flex" style={{width:200,flexShrink:0,borderRight:`1px solid ${BORDER}`,padding:14,flexDirection:"column",background:BG2}}><div style={{marginBottom:28,paddingLeft:6}}><Logo/><p style={{fontSize:8,color:TEXT3,letterSpacing:"0.12em",textTransform:"uppercase",marginTop:3}}>CRM High Ticket</p></div><nav style={{flex:1,display:"flex",flexDirection:"column",gap:2}}>{NAV.map(n=><button key={n.key} onClick={()=>sPage(n.key)} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 10px",borderRadius:7,border:"none",fontSize:12,fontWeight:500,cursor:"pointer",textAlign:"left",width:"100%",background:page===n.key?GOLD_BG2:"transparent",color:page===n.key?GOLD:TEXT3}}><n.icon size={15}/>{n.label}</button>)}</nav><div style={{paddingTop:14,borderTop:`1px solid ${BORDER}`,marginTop:"auto"}}><div style={{fontSize:9,color:GOLD_DIM}}>{config?.nome_negocio||"CRM"}</div><div style={{fontSize:8,color:TEXT3,marginTop:2}}>{leads.length} leads • {vendas.length} vendas</div></div></aside>
<main style={{flex:1,padding:"14px 18px",overflowY:"auto",maxHeight:"100vh"}}><div className="flex md:hidden flex-wrap gap-1" style={{marginBottom:10,background:BG2,borderRadius:8,padding:3}}>{NAV.map(n=><button key={n.key} onClick={()=>sPage(n.key)} style={{padding:"5px 8px",borderRadius:5,border:"none",fontSize:9,cursor:"pointer",background:page===n.key?GOLD_BG2:"transparent",color:page===n.key?GOLD:TEXT3}}><n.icon size={11}/></button>)}</div>
<div className="flex items-center justify-between" style={{marginBottom:18}}><div><h2 style={{fontSize:16,fontWeight:600,color:TEXT1,margin:0}}>{NAV.find(n=>n.key===page)?.label}</h2><p style={{fontSize:10,color:TEXT3,margin:"3px 0 0"}}>{leads.length} leads</p></div><button onClick={refetch} style={{display:"flex",alignItems:"center",gap:5,padding:"6px 12px",borderRadius:7,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:10,cursor:"pointer"}}><RefreshCw size={11}/>Atualizar</button></div>
{page==="dashboard"&&(ll?<Spinner/>:<DashboardPage leads={leads} config={config}/>)}
{page==="crm"&&(ll?<Spinner/>:<CRMPage leads={leads} onLeadClick={sSel} onUpdate={updateLead} equipe={equipe} onAdd={addLead}/>)}
{page==="analytics"&&(ll?<Spinner/>:<AnalyticsPage leads={leads} config={config}/>)}
{page==="tracking"&&(el?<Spinner/>:<TrackingPage eventos={eventos}/>)}
{page==="templates"&&<TemplatesPage templates={templates} loading={tl} addTemplate={addTemplate} removeTemplate={removeTemplate}/>}
{page==="config"&&<ConfigPage equipe={equipe} eqLoading={eql} addMember={addMember} removeMember={removeMember} toggleActive={toggleActive} config={config}/>}
</main>
{sel&&<LeadModal lead={sel} onClose={()=>{sSel(null);refetch();}} onUpdate={updateLead} onDelete={deleteLead} equipe={equipe} templates={templates}/>}
</div>;}
