import { useState, useEffect, useMemo, useCallback } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, CartesianGrid, Area, AreaChart } from "recharts";
import { Users, UserCheck, Calendar, DollarSign, TrendingUp, Target, Phone, Filter, LayoutDashboard, Kanban, BarChart3, Radio, Settings, X, Check, AlertTriangle, Zap, Plus, Trash2, Eye, EyeOff, Award, Loader2, RefreshCw, Search, MessageSquare, Clock, Copy, ArrowRightLeft } from "lucide-react";
import { supabase } from "./lib/supabase";

const GOLD="#C9A84C",GOLD_LIGHT="#E2C97E",GOLD_DIM="#8B7535",GOLD_BG="rgba(201,168,76,0.08)",GOLD_BG2="rgba(201,168,76,0.15)";
const BG="#09090B",BG2="#0F0F12",BG3="#16161A",BORDER="rgba(201,168,76,0.08)",BORDER2="rgba(201,168,76,0.15)";
const TEXT1="#FAFAF9",TEXT2="rgba(250,250,249,0.55)",TEXT3="rgba(250,250,249,0.3)";
const TEAM_COLORS=["#C9A84C","#60A5FA","#34D399","#F472B6","#A78BFA","#FB923C","#22D3EE","#F87171","#84CC16","#E879F9"];
const BANT_ITEMS=[{key:"budget",label:"Budget",desc:"Tem condição financeira de investir?"},{key:"authority",label:"Authority",desc:"É o decisor da compra?"},{key:"need",label:"Need",desc:"Tem a dor/necessidade real?"},{key:"timeline",label:"Timeline",desc:"Tem urgência ou prazo definido?"}];
const STAGES=[{key:"novo",label:"Novo",color:GOLD},{key:"em_contato",label:"Em Contato",color:"#60A5FA"},{key:"qualificado",label:"Qualificado",color:"#34D399"},{key:"desqualificado",label:"Desqualificado",color:"#F87171"},{key:"agendado",label:"Agendado",color:"#A78BFA"},{key:"no_show",label:"No Show",color:"#FBBF24"},{key:"em_negociacao",label:"Em Negociação",color:"#22D3EE"},{key:"venda",label:"Venda",color:"#4ADE80"},{key:"perdido",label:"Perdido",color:"#6B7280"}];
const KANBAN_STAGES=STAGES.filter(s=>!["desqualificado","no_show","perdido"].includes(s.key));
const NAV=[{key:"dashboard",label:"Dashboard",icon:LayoutDashboard},{key:"crm",label:"Pipeline",icon:Kanban},{key:"analytics",label:"Analytics",icon:BarChart3},{key:"tracking",label:"Tracking",icon:Radio},{key:"templates",label:"Templates",icon:MessageSquare},{key:"config",label:"Config",icon:Settings}];
const fmt=v=>v!=null?v.toLocaleString("pt-BR",{style:"currency",currency:"BRL",minimumFractionDigits:0}):"R$ 0";
const pct=(a,b)=>b>0?Math.round((a/b)*100):0;
const timeAgo=d=>{if(!d)return"—";const ms=Date.now()-new Date(d).getTime(),h=Math.floor(ms/3600000),dy=Math.floor(h/24);return dy>0?`${dy}d`:h>0?`${h}h`:"agora";};
const isInactive=l=>l.stage==="novo"&&(Date.now()-new Date(l.created_at).getTime())/3600000>=2;
const bantBadge=s=>s>=4?"bg-amber-400/10 text-amber-400":s>=3?"bg-emerald-400/10 text-emerald-400":s>=2?"bg-yellow-400/10 text-yellow-400":"bg-red-400/10 text-red-400";
const WA_ICON=<svg width="12" height="12" viewBox="0 0 24 24" fill="#25D366"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/><path d="M12 0C5.373 0 0 5.373 0 12c0 2.625.846 5.059 2.284 7.034L.789 23.492l4.624-1.467A11.932 11.932 0 0012 24c6.627 0 12-5.373 12-12S18.627 0 12 0zm0 21.818c-2.168 0-4.19-.586-5.932-1.608l-.425-.253-2.742.87.888-2.664-.278-.442A9.78 9.78 0 012.182 12 9.818 9.818 0 0112 2.182 9.818 9.818 0 0121.818 12 9.818 9.818 0 0112 21.818z"/></svg>;

function useLeads(){const[leads,setLeads]=useState([]);const[loading,setLoading]=useState(true);const fetch=useCallback(async()=>{setLoading(true);const{data}=await supabase.from("crm_leads").select("*").order("created_at",{ascending:false});if(data)setLeads(data);setLoading(false);},[]);useEffect(()=>{fetch();},[fetch]);const update=async(id,u)=>{const{error}=await supabase.from("crm_leads").update(u).eq("id",id);if(!error)setLeads(p=>p.map(l=>l.id===id?{...l,...u}:l));return!error;};const add=async l=>{const{data,error}=await supabase.from("crm_leads").insert(l).select();if(!error&&data){setLeads(p=>[data[0],...p]);return data[0];}return null;};const del=async id=>{const{error}=await supabase.from("crm_leads").delete().eq("id",id);if(!error)setLeads(p=>p.filter(l=>l.id!==id));return!error;};return{leads,loading,refetch:fetch,updateLead:update,addLead:add,deleteLead:del};}
function useEventos(){const[e,setE]=useState([]);const[l,setL]=useState(true);useEffect(()=>{(async()=>{const{data}=await supabase.from("crm_eventos").select("*").order("created_at",{ascending:false}).limit(50);if(data)setE(data);setL(false);})();},[]);return{eventos:e,loading:l};}
function useEquipe(){const[eq,setEq]=useState([]);const[l,setL]=useState(true);const fetch=useCallback(async()=>{setL(true);const{data}=await supabase.from("crm_equipe").select("*").order("created_at");if(data)setEq(data);setL(false);},[]);useEffect(()=>{fetch();},[fetch]);const add=async m=>{const{data,error}=await supabase.from("crm_equipe").insert(m).select();if(!error&&data)setEq(p=>[...p,data[0]]);return!error;};const remove=async id=>{await supabase.from("crm_equipe").delete().eq("id",id);setEq(p=>p.filter(m=>m.id!==id));};const toggle=async(id,a)=>{await supabase.from("crm_equipe").update({ativo:!a}).eq("id",id);setEq(p=>p.map(m=>m.id===id?{...m,ativo:!a}:m));};return{equipe:eq,loading:l,addMember:add,removeMember:remove,toggleActive:toggle};}
function useConfig(){const[c,setC]=useState(null);useEffect(()=>{(async()=>{const{data}=await supabase.from("crm_config").select("*").eq("ativo",true).limit(1).single();if(data)setC(data);})();},[]);return c;}
function useTemplates(){const[t,setT]=useState([]);const[l,setL]=useState(true);useEffect(()=>{(async()=>{const{data}=await supabase.from("crm_templates").select("*").eq("ativo",true).order("created_at");if(data)setT(data);setL(false);})();},[]);const add=async m=>{const{data,error}=await supabase.from("crm_templates").insert(m).select();if(!error&&data)setT(p=>[...p,data[0]]);return!error;};const remove=async id=>{await supabase.from("crm_templates").delete().eq("id",id);setT(p=>p.filter(x=>x.id!==id));};return{templates:t,loading:l,addTemplate:add,removeTemplate:remove};}
function useAtividades(id){const[a,setA]=useState([]);useEffect(()=>{if(!id)return;(async()=>{const{data}=await supabase.from("crm_atividades").select("*").eq("lead_id",id).order("created_at",{ascending:false}).limit(20);if(data)setA(data);})();},[id]);const add=async(lid,tipo,desc,dados)=>{const{data,error}=await supabase.from("crm_atividades").insert({lead_id:lid,tipo,descricao:desc,dados}).select();if(!error&&data)setA(p=>[data[0],...p]);};return{atividades:a,addAtividade:add};}

function Card({children,style={}}){return<div style={{background:BG2,border:`1px solid ${BORDER}`,borderRadius:12,...style}}>{children}</div>;}
function Spinner(){return<div className="flex items-center justify-center p-12"><Loader2 size={24} style={{color:GOLD,animation:"spin 1s linear infinite"}}/></div>;}
function Logo(){return<div style={{display:"flex",alignItems:"center",gap:2,userSelect:"none"}}><span style={{fontWeight:800,fontSize:22,color:TEXT1}}>HT</span><span style={{fontWeight:800,fontSize:22,background:`linear-gradient(135deg,${GOLD_LIGHT},${GOLD},${GOLD_DIM})`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>X</span></div>;}
function MetricCard({icon:Icon,label,value,sub,accent}){return<Card style={{padding:16}}><div className="flex items-center gap-2" style={{marginBottom:8}}><div className="flex items-center justify-center" style={{width:32,height:32,borderRadius:8,background:accent?GOLD_BG2:"rgba(255,255,255,0.04)"}}><Icon size={15} style={{color:accent?GOLD:TEXT2}}/></div><span style={{fontSize:11,color:TEXT3,letterSpacing:"0.04em",textTransform:"uppercase"}}>{label}</span></div><div style={{fontSize:22,fontWeight:600,color:accent?GOLD_LIGHT:TEXT1}}>{value}</div>{sub&&<div style={{fontSize:11,color:TEXT3,marginTop:4}}>{sub}</div>}</Card>;}

function LeadCard({lead,onClick,equipe}){const sdr=equipe.find(m=>m.nome===lead.sdr_nome);const closer=equipe.find(m=>m.nome===lead.closer_nome);const inactive=isInactive(lead);
return<div draggable onDragStart={e=>e.dataTransfer.setData("leadId",lead.id)} onClick={()=>onClick?.(lead)} style={{background:BG3,border:`1px solid ${inactive?"rgba(248,113,113,0.4)":BORDER}`,borderRadius:10,padding:12,marginBottom:8,cursor:"grab",animation:inactive?"pulse 2s infinite":"none"}} onMouseEnter={e=>{if(!inactive)e.currentTarget.style.borderColor=GOLD_DIM;}} onMouseLeave={e=>{if(!inactive)e.currentTarget.style.borderColor=inactive?"rgba(248,113,113,0.4)":BORDER;}}>
<div className="flex items-center justify-between" style={{marginBottom:6}}><span style={{fontSize:13,fontWeight:500,color:TEXT1}}>{lead.nome}</span>
<div className="flex items-center gap-1">{lead.utm_source==="meta"&&<div title="Meta" style={{width:16,height:16,borderRadius:4,background:"rgba(59,130,246,0.15)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:8,fontWeight:700,color:"#60A5FA"}}>M</div>}{lead.utm_source==="google"&&<div title="Google" style={{width:16,height:16,borderRadius:4,background:"rgba(52,211,153,0.15)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:8,fontWeight:700,color:"#34D399"}}>G</div>}{lead.tags?.includes("vip")&&<span style={{fontSize:9,padding:"2px 6px",borderRadius:20,background:GOLD_BG2,color:GOLD,fontWeight:600}}>VIP</span>}</div></div>
<div className="flex items-center justify-between" style={{marginBottom:4}}><div className="flex items-center gap-1" style={{fontSize:11,color:TEXT3}}><Phone size={10}/>{lead.telefone||"-"}</div><a href={`https://wa.me/${lead.telefone}`} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()} title="WhatsApp" style={{width:24,height:24,borderRadius:6,background:"rgba(37,211,102,0.12)",display:"flex",alignItems:"center",justifyContent:"center",textDecoration:"none"}}>{WA_ICON}</a></div>
{lead.quali_score>0&&<div className="flex items-center gap-2" style={{marginTop:6}}><div className="flex gap-1">{[1,2,3,4].map(i=><div key={i} style={{height:3,width:16,borderRadius:2,background:i<=lead.quali_score?GOLD:"rgba(255,255,255,0.06)"}}/>)}</div><span className={`text-[10px] px-1.5 py-0.5 rounded font-semibold ${bantBadge(lead.quali_score)}`}>{lead.quali_score}/4</span></div>}
{lead.valor_venda&&<div style={{marginTop:6,fontSize:13,fontWeight:700,color:"#4ADE80"}}>{fmt(lead.valor_venda)}</div>}
<div className="flex items-center justify-between" style={{marginTop:6}}>
<div className="flex items-center gap-1">{sdr&&<span style={{fontSize:9,padding:"2px 6px",borderRadius:10,background:`${sdr.cor||GOLD}18`,color:sdr.cor||GOLD,fontWeight:600}}>{sdr.nome.split(" ")[0]}</span>}{closer&&<span style={{fontSize:9,padding:"2px 6px",borderRadius:10,background:`${closer.cor||"#A78BFA"}18`,color:closer.cor||"#A78BFA",fontWeight:600}}>{closer.nome.split(" ")[0]}</span>}</div>
<span style={{fontSize:9,color:TEXT3}}>{timeAgo(lead.created_at)}</span></div>
{inactive&&<div style={{marginTop:6,fontSize:9,color:"#F87171",fontWeight:600}}>⚠ Sem contato</div>}
</div>;}

function AddLeadModal({onClose,onAdd,equipe}){const[nome,setNome]=useState("");const[tel,setTel]=useState("");const[email,setEmail]=useState("");const[sdr,setSdr]=useState("");const[saving,setSaving]=useState(false);const[err,setErr]=useState(null);const sdrs=equipe.filter(m=>m.papel==="sdr"&&m.ativo);
const save=async()=>{if(!nome.trim()||!tel.trim())return;setSaving(true);setErr(null);let t=tel.replace(/\D/g,"");if(t.length===11)t="55"+t;if(t.length===10)t="55"+t;const{data:dup}=await supabase.from("crm_leads").select("id,nome,stage").eq("telefone",t).limit(1);if(dup?.length){setErr(`Lead já existe: ${dup[0].nome} (${dup[0].stage})`);setSaving(false);return;}
let assigned=sdr;if(!assigned&&sdrs.length>0){const counts={};sdrs.forEach(s=>{counts[s.nome]=0;});const{data:all}=await supabase.from("crm_leads").select("sdr_nome").not("sdr_nome","is",null);if(all)all.forEach(l=>{if(counts[l.sdr_nome]!==undefined)counts[l.sdr_nome]++;});let min=Infinity,pick=sdrs[0].nome;Object.entries(counts).forEach(([n,c])=>{if(c<min){min=c;pick=n;}});assigned=pick;}
await onAdd({nome:nome.trim(),telefone:t,email:email.trim()||null,stage:"novo",origem:"manual",sdr_nome:assigned||null});setSaving(false);onClose();};
const IS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
return<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:16,background:"rgba(0,0,0,0.8)"}}><div style={{width:"100%",maxWidth:440,background:BG2,border:`1px solid ${BORDER2}`,borderRadius:16,padding:24}}>
<div className="flex items-center justify-between" style={{marginBottom:20}}><h3 style={{fontSize:16,fontWeight:600,color:TEXT1,margin:0}}>Novo lead</h3><button onClick={onClose} style={{padding:8,borderRadius:8,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:TEXT2}}><X size={16}/></button></div>
{err&&<div style={{padding:10,borderRadius:8,background:"rgba(248,113,113,0.1)",border:"1px solid rgba(248,113,113,0.2)",color:"#F87171",fontSize:12,marginBottom:12}}>{err}</div>}
<div style={{display:"flex",flexDirection:"column",gap:10}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Nome *</label><input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Nome completo" style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>WhatsApp *</label><input value={tel} onChange={e=>setTel(e.target.value)} placeholder="11999998888" style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>SDR (vazio = round-robin)</label><select value={sdr} onChange={e=>setSdr(e.target.value)} style={IS}><option value="">Automático</option>{sdrs.map(s=><option key={s.id} value={s.nome}>{s.nome}</option>)}</select></div></div>
<div className="flex gap-2" style={{marginTop:16}}><button onClick={save} disabled={saving} style={{flex:1,padding:"10px",borderRadius:8,border:"none",background:GOLD,color:BG,fontSize:13,fontWeight:600,cursor:"pointer",opacity:saving?.6:1}}>{saving?"Salvando...":"Adicionar"}</button><button onClick={onClose} style={{padding:"10px 20px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:13,cursor:"pointer"}}>Cancelar</button></div></div></div>;}

function LeadModal({lead,onClose,onUpdate,onDelete,equipe,templates}){const[stage,setStage]=useState(lead.stage);const[qb,setQb]=useState(lead.quali_budget||false);const[qa,setQa]=useState(lead.quali_authority||false);const[qn,setQn]=useState(lead.quali_need||false);const[qt,setQt]=useState(lead.quali_timeline||false);const[val,setVal]=useState(lead.valor_venda||"");const[sdr,setSdr]=useState(lead.sdr_nome||"");const[closer,setCloser]=useState(lead.closer_nome||"");const[nota,setNota]=useState("");const[saving,setSaving]=useState(false);const[tab,setTab]=useState("info");const[copied,setCopied]=useState(null);const{atividades,addAtividade}=useAtividades(lead.id);const score=[qb,qa,qn,qt].filter(Boolean).length;
const save=async()=>{setSaving(true);const u={stage,quali_score:score,quali_budget:qb,quali_authority:qa,quali_need:qn,quali_timeline:qt,valor_venda:val?parseFloat(val):null,sdr_nome:sdr||null,closer_nome:closer||null};if(stage==="em_contato"&&!lead.contatado_at)u.contatado_at=new Date().toISOString();if(stage==="qualificado"&&lead.stage!=="qualificado")u.qualificado_at=new Date().toISOString();if(stage==="agendado"&&lead.stage!=="agendado")u.agendado_at=new Date().toISOString();if(stage==="venda"&&lead.stage!=="venda")u.venda_at=new Date().toISOString();if(stage!==lead.stage)await addAtividade(lead.id,"stage_change",`${lead.stage} → ${stage}`);await onUpdate(lead.id,u);setSaving(false);onClose();};
const addNota=async()=>{if(!nota.trim())return;await addAtividade(lead.id,"nota",nota.trim());setNota("");};
const copyTpl=t=>{const msg=t.mensagem.replace(/\{\{nome\}\}/g,lead.nome?.split(" ")[0]||"");navigator.clipboard.writeText(msg);setCopied(t.id);setTimeout(()=>setCopied(null),2000);};
const stageInfo=STAGES.find(s=>s.key===lead.stage);const SS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};const sdrs=equipe.filter(m=>m.papel==="sdr"&&m.ativo);const closers=equipe.filter(m=>m.papel==="closer"&&m.ativo);
return<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:16,background:"rgba(0,0,0,0.8)",backdropFilter:"blur(6px)"}}><div style={{width:"100%",maxWidth:600,background:BG2,border:`1px solid ${BORDER2}`,borderRadius:16,padding:24,maxHeight:"92vh",overflowY:"auto"}}>
<div className="flex items-center justify-between" style={{marginBottom:16}}><div><h3 style={{fontSize:18,fontWeight:600,color:TEXT1,margin:0}}>{lead.nome}</h3><div className="flex items-center gap-2" style={{marginTop:6}}><span style={{fontSize:11,padding:"3px 10px",borderRadius:20,background:`${stageInfo?.color}18`,color:stageInfo?.color,fontWeight:500}}>{stageInfo?.label}</span><span style={{fontSize:10,color:TEXT3}}>{timeAgo(lead.created_at)}</span></div></div>
<div className="flex items-center gap-2"><button onClick={()=>{if(confirm("Excluir permanentemente?")){onDelete(lead.id);onClose();}}} style={{padding:8,borderRadius:8,border:"none",background:"rgba(248,113,113,0.1)",cursor:"pointer",color:"#F87171"}}><Trash2 size={14}/></button><a href={`https://wa.me/${lead.telefone}`} target="_blank" rel="noreferrer" style={{padding:8,borderRadius:8,background:"rgba(37,211,102,0.12)",display:"flex",alignItems:"center",justifyContent:"center"}}>{WA_ICON}</a><button onClick={onClose} style={{padding:8,borderRadius:8,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:TEXT2}}><X size={16}/></button></div></div>
<div className="flex gap-1" style={{marginBottom:16,background:"rgba(255,255,255,0.03)",borderRadius:8,padding:3}}>{[{k:"info",l:"Dados"},{k:"bant",l:"BANT"},{k:"notas",l:"Notas"},{k:"msgs",l:"Templates"}].map(t=><button key={t.k} onClick={()=>setTab(t.k)} style={{flex:1,padding:"7px 0",borderRadius:6,border:"none",fontSize:11,fontWeight:500,cursor:"pointer",background:tab===t.k?GOLD_BG2:"transparent",color:tab===t.k?GOLD:TEXT3}}>{t.l}</button>)}</div>
{tab==="info"&&<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:16}}>{[{l:"Email",v:lead.email||"—"},{l:"Telefone",v:lead.telefone||"—"},{l:"Campanha",v:lead.utm_campaign||"—"},{l:"Conjunto",v:lead.utm_term||"—"},{l:"Criativo",v:lead.utm_content||"—"},{l:"Fonte",v:lead.utm_source||"—"}].map(f=><div key={f.l} style={{background:BG3,border:`1px solid ${BORDER}`,borderRadius:8,padding:10}}><div style={{fontSize:9,color:TEXT3,textTransform:"uppercase",marginBottom:4}}>{f.l}</div><div style={{fontSize:13,color:TEXT1}}>{f.v}</div></div>)}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:16}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Estágio</label><select value={stage} onChange={e=>setStage(e.target.value)} style={SS}>{STAGES.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Valor (R$)</label><input type="number" value={val} onChange={e=>setVal(e.target.value)} placeholder="50000" style={SS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>SDR</label><select value={sdr} onChange={e=>setSdr(e.target.value)} style={SS}><option value="">—</option>{sdrs.map(s=><option key={s.id} value={s.nome}>{s.nome}</option>)}</select></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Closer</label><select value={closer} onChange={e=>setCloser(e.target.value)} style={SS}><option value="">—</option>{closers.map(c=><option key={c.id} value={c.nome}>{c.nome}</option>)}</select></div></div></>}
{tab==="bant"&&<div style={{marginBottom:16}}><div style={{fontSize:11,color:TEXT2,marginBottom:12}}>Marque os critérios atendidos:</div>{BANT_ITEMS.map((b,i)=>{const checks=[qb,qa,qn,qt],sets=[setQb,setQa,setQn,setQt];return<div key={b.key} onClick={()=>sets[i](!checks[i])} style={{display:"flex",alignItems:"center",gap:12,padding:12,borderRadius:8,border:`1px solid ${checks[i]?`${GOLD}44`:BORDER}`,background:checks[i]?GOLD_BG:"transparent",marginBottom:8,cursor:"pointer"}}><div style={{width:24,height:24,borderRadius:6,border:`2px solid ${checks[i]?GOLD:"rgba(255,255,255,0.15)"}`,display:"flex",alignItems:"center",justifyContent:"center",background:checks[i]?GOLD_BG2:"transparent"}}>{checks[i]&&<Check size={14} style={{color:GOLD}}/>}</div><div><div style={{fontSize:13,fontWeight:500,color:checks[i]?GOLD_LIGHT:TEXT1}}>{b.label}</div><div style={{fontSize:11,color:TEXT3,marginTop:2}}>{b.desc}</div></div></div>;})}
<div className="flex items-center gap-3" style={{marginTop:12,padding:12,borderRadius:8,background:BG3}}><span style={{fontSize:11,color:TEXT3}}>Score:</span><div className="flex gap-1">{[1,2,3,4].map(i=><div key={i} style={{width:24,height:6,borderRadius:3,background:i<=score?GOLD:"rgba(255,255,255,0.06)"}}/>)}</div><span className={`px-2 py-0.5 rounded text-xs font-bold ${bantBadge(score)}`}>{score}/4</span></div></div>}
{tab==="notas"&&<div style={{marginBottom:16}}><div className="flex gap-2" style={{marginBottom:12}}><input value={nota} onChange={e=>setNota(e.target.value)} placeholder="Adicionar nota..." style={{...SS,flex:1}} onKeyDown={e=>{if(e.key==="Enter")addNota();}}/><button onClick={addNota} style={{padding:"8px 16px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:12,fontWeight:500,cursor:"pointer"}}>Salvar</button></div>{atividades.length===0&&<div style={{fontSize:12,color:TEXT3,textAlign:"center",padding:20}}>Nenhuma atividade</div>}{atividades.map(a=><div key={a.id} style={{padding:10,borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:6}}><div className="flex items-center justify-between"><span style={{fontSize:10,color:a.tipo==="stage_change"?"#A78BFA":GOLD,fontWeight:600,textTransform:"uppercase"}}>{a.tipo.replace("_"," ")}</span><span style={{fontSize:9,color:TEXT3}}>{new Date(a.created_at).toLocaleString("pt-BR")}</span></div><div style={{fontSize:12,color:TEXT1,marginTop:4}}>{a.descricao}</div></div>)}</div>}
{tab==="msgs"&&<div style={{marginBottom:16}}>{templates.length===0&&<div style={{fontSize:12,color:TEXT3,textAlign:"center",padding:20}}>Nenhum template</div>}{templates.map(t=>{const msg=t.mensagem.replace(/\{\{nome\}\}/g,lead.nome?.split(" ")[0]||"");return<div key={t.id} style={{padding:12,borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:8,background:BG3}}><div className="flex items-center justify-between" style={{marginBottom:6}}><span style={{fontSize:12,fontWeight:500,color:GOLD}}>{t.titulo}</span><button onClick={()=>copyTpl(t)} style={{display:"flex",alignItems:"center",gap:4,padding:"4px 10px",borderRadius:6,border:"none",background:copied===t.id?"rgba(74,222,128,0.15)":GOLD_BG2,color:copied===t.id?"#4ADE80":GOLD,fontSize:10,fontWeight:500,cursor:"pointer"}}>{copied===t.id?<><Check size={10}/>Copiado</>:<><Copy size={10}/>Copiar</>}</button></div><div style={{fontSize:12,color:TEXT2,lineHeight:1.5}}>{msg}</div></div>;})}</div>}
<div className="flex gap-2"><button onClick={save} disabled={saving} style={{flex:1,padding:"10px",borderRadius:8,border:"none",background:GOLD,color:BG,fontSize:13,fontWeight:600,cursor:"pointer",opacity:saving?.6:1}}>{saving?"Salvando...":"Salvar"}</button><button onClick={onClose} style={{padding:"10px 20px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:13,cursor:"pointer"}}>Cancelar</button></div></div></div>;}

function DashboardPage({leads,config}){const total=leads.length;const qual=leads.filter(l=>["qualificado","agendado","no_show","em_negociacao","venda"].includes(l.stage)).length;const agend=leads.filter(l=>["agendado","no_show","em_negociacao","venda"].includes(l.stage)).length;const comp=leads.filter(l=>["em_negociacao","venda"].includes(l.stage)).length;const vendas=leads.filter(l=>l.stage==="venda");const rec=vendas.reduce((s,l)=>s+(l.valor_venda||0),0);const tm=vendas.length>0?Math.round(rec/vendas.length):0;const mv=vendas.length>0?Math.max(...vendas.map(l=>l.valor_venda||0)):0;const gasto=config?.gasto_ads_mensal||0;const meta=config?.meta_mensal||0;
const forecast=useMemo(()=>{const tQ=total>0?qual/total:0,tA=qual>0?agend/qual:0,tV=agend>0?vendas.length/agend:0;const eA=leads.filter(l=>["agendado","em_negociacao"].includes(l.stage)).length;const eQ=leads.filter(l=>l.stage==="qualificado").length;return Math.round((eA*tV*tm)+(eQ*tA*tV*tm));},[leads]);
const funnel=[{label:"Leads",value:total,color:GOLD,rate:100},{label:"Qualificados",value:qual,color:"#34D399",rate:pct(qual,total)},{label:"Agendados",value:agend,color:"#A78BFA",rate:pct(agend,total)},{label:"Compareceram",value:comp,color:"#22D3EE",rate:pct(comp,total)},{label:"Vendas",value:vendas.length,color:"#4ADE80",rate:pct(vendas.length,total)}];
const daily=useMemo(()=>{const m={};leads.forEach(l=>{const d=new Date(l.created_at).toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"});if(!m[d])m[d]={dia:d,leads:0};m[d].leads++;});return Object.values(m).slice(-14);},[leads]);
const loss=useMemo(()=>{const m={};leads.filter(l=>l.motivo_perda_categoria).forEach(l=>{m[l.motivo_perda_categoria]=(m[l.motivo_perda_categoria]||0)+1;});const c={sem_budget:"#F87171",nao_respondeu:"#6B7280",sem_interesse:"#FBBF24",escolheu_concorrente:"#A78BFA",timing_ruim:"#22D3EE",nao_qualificado:"#FB923C",outro:"#94A3B8"};const lb={sem_budget:"Sem budget",nao_respondeu:"Não respondeu",sem_interesse:"Sem interesse",escolheu_concorrente:"Concorrente",timing_ruim:"Timing",nao_qualificado:"Não qualificado",outro:"Outro"};return Object.entries(m).map(([k,v])=>({name:lb[k]||k,value:v,color:c[k]||"#6B7280"}));},[leads]);
const FunnelBar=({label,value,maxVal,color,rate})=>{const w=maxVal>0?(value/maxVal)*100:0;return<div className="flex items-center gap-3" style={{padding:"5px 0"}}><div style={{width:100,textAlign:"right",flexShrink:0,fontSize:12,color:TEXT2}}>{label}</div><div className="flex-1 overflow-hidden" style={{height:26,borderRadius:6,background:"rgba(255,255,255,0.03)"}}><div className="flex items-center" style={{height:"100%",width:`${Math.max(w,4)}%`,borderRadius:6,background:color,opacity:.85,paddingLeft:8,transition:"width 0.8s"}}><span style={{fontSize:11,fontWeight:600,color:"#fff"}}>{value}</span></div></div><div style={{width:42,textAlign:"right",flexShrink:0,fontSize:11,color:TEXT3}}>{rate}%</div></div>;};
return<div style={{display:"flex",flexDirection:"column",gap:16}}>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12}}><MetricCard icon={Users} label="Leads" value={total} accent/><MetricCard icon={UserCheck} label="Qualificados" value={qual} sub={`${pct(qual,total)}%`}/><MetricCard icon={Calendar} label="Agendados" value={agend}/><MetricCard icon={DollarSign} label="Vendas" value={vendas.length} sub={`${pct(vendas.length,total)}%`}/></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12}}><MetricCard icon={DollarSign} label="Receita" value={fmt(rec)} accent/><MetricCard icon={Target} label="Ticket médio" value={fmt(tm)}/><MetricCard icon={Zap} label="Forecast" value={fmt(forecast)} sub="pipeline estimado"/><MetricCard icon={TrendingUp} label="Leads/venda" value={vendas.length>0?Math.round(total/vendas.length):"—"}/></div>
{gasto>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12}}><MetricCard icon={DollarSign} label="CPL" value={total>0?fmt(Math.round(gasto/total)):"—"}/><MetricCard icon={Target} label="CPL Qualif." value={qual>0?fmt(Math.round(gasto/qual)):"—"}/><MetricCard icon={Calendar} label="Custo/Agend." value={agend>0?fmt(Math.round(gasto/agend)):"—"}/><MetricCard icon={DollarSign} label="CAC" value={vendas.length>0?fmt(Math.round(gasto/vendas.length)):"—"}/></div>}
{meta>0&&<Card style={{padding:16}}><div className="flex items-center justify-between" style={{marginBottom:8}}><span style={{fontSize:11,color:TEXT3,textTransform:"uppercase"}}>Meta mensal</span><span style={{fontSize:11,color:TEXT2}}>{fmt(rec)} / {fmt(meta)}</span></div><div style={{height:8,borderRadius:4,background:"rgba(255,255,255,0.04)",overflow:"hidden"}}><div style={{height:"100%",borderRadius:4,background:rec>=meta?"linear-gradient(90deg,#4ADE80,#22c55e)":`linear-gradient(90deg,${GOLD},${GOLD_LIGHT})`,width:`${Math.min((rec/meta)*100,100)}%`,transition:"width 1s"}}/></div><div style={{fontSize:20,fontWeight:600,color:rec>=meta?"#4ADE80":GOLD_LIGHT,marginTop:8}}>{meta>0?Math.round((rec/meta)*100):0}%</div></Card>}
<div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:12}}>
<Card style={{padding:20}}><h3 style={{fontSize:13,fontWeight:500,color:TEXT2,marginBottom:12}}>Funil</h3>{funnel.map(f=><FunnelBar key={f.label} {...f} maxVal={total}/>)}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,marginTop:16,paddingTop:16,borderTop:`1px solid ${BORDER}`}}>{[{v:vendas.length>0?Math.round(total/vendas.length):"—",l:"Leads/venda"},{v:vendas.length>0?Math.round(qual/vendas.length):"—",l:"Qualif./venda"},{v:vendas.length>0?Math.round(agend/vendas.length):"—",l:"Agend./venda"}].map(m=><div key={m.l} style={{textAlign:"center"}}><div style={{fontSize:20,fontWeight:600,color:GOLD_LIGHT}}>{m.v}</div><div style={{fontSize:9,color:TEXT3,marginTop:2}}>{m.l}</div></div>)}</div></Card>
<Card style={{padding:20}}><h3 style={{fontSize:13,fontWeight:500,color:TEXT2,marginBottom:12}}>Perdas</h3>{loss.length>0?<>{<div style={{display:"flex",justifyContent:"center",marginBottom:12}}><PieChart width={160} height={160}><Pie data={loss} cx={80} cy={80} innerRadius={45} outerRadius={70} dataKey="value" stroke="none">{loss.map((e,i)=><Cell key={i} fill={e.color}/>)}</Pie></PieChart></div>}{loss.map(r=><div key={r.name} className="flex items-center justify-between" style={{padding:"4px 0"}}><div className="flex items-center gap-2"><div style={{width:8,height:8,borderRadius:"50%",background:r.color}}/><span style={{fontSize:11,color:TEXT2}}>{r.name}</span></div><span style={{fontSize:12,fontWeight:500,color:TEXT1}}>{r.value}</span></div>)}</>:<div style={{fontSize:12,color:TEXT3,textAlign:"center",padding:40}}>Sem dados</div>}</Card></div>
{daily.length>0&&<Card style={{padding:20}}><h3 style={{fontSize:13,fontWeight:500,color:TEXT2,marginBottom:12}}>Leads/dia</h3><ResponsiveContainer width="100%" height={200}><AreaChart data={daily}><defs><linearGradient id="gL" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={GOLD} stopOpacity={.25}/><stop offset="95%" stopColor={GOLD} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)"/><XAxis dataKey="dia" tick={{fill:TEXT3,fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fill:TEXT3,fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:8,color:TEXT1,fontSize:11}}/><Area type="monotone" dataKey="leads" stroke={GOLD} fill="url(#gL)" strokeWidth={2}/></AreaChart></ResponsiveContainer></Card>}
</div>;}

function CRMPage({leads,onLeadClick,onUpdate,equipe,onAdd}){const[search,setSearch]=useState("");const[filterSdr,setFilterSdr]=useState("");const[showAdd,setShowAdd]=useState(false);const[dragOver,setDragOver]=useState(null);
const filtered=useMemo(()=>{let f=leads;if(search){const s=search.toLowerCase();f=f.filter(l=>(l.nome||"").toLowerCase().includes(s)||(l.telefone||"").includes(s)||(l.utm_campaign||"").toLowerCase().includes(s));}if(filterSdr)f=f.filter(l=>l.sdr_nome===filterSdr);return f;},[leads,search,filterSdr]);
const grouped=useMemo(()=>{const g={};KANBAN_STAGES.forEach(s=>{g[s.key]=[];});filtered.forEach(l=>{if(g[l.stage])g[l.stage].push(l);});return g;},[filtered]);
const sdrs=[...new Set(leads.map(l=>l.sdr_nome).filter(Boolean))];
const handleDrop=async(sk,e)=>{e.preventDefault();setDragOver(null);const id=e.dataTransfer.getData("leadId");if(!id)return;const u={stage:sk};if(sk==="em_contato")u.contatado_at=new Date().toISOString();if(sk==="qualificado")u.qualificado_at=new Date().toISOString();if(sk==="agendado")u.agendado_at=new Date().toISOString();if(sk==="venda")u.venda_at=new Date().toISOString();await onUpdate(id,u);};
return<div><div className="flex flex-wrap items-center gap-3" style={{marginBottom:16}}><div style={{position:"relative",flex:"1 1 200px"}}><Search size={14} style={{position:"absolute",left:10,top:"50%",transform:"translateY(-50%)",color:TEXT3}}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar..." style={{width:"100%",padding:"8px 8px 8px 32px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:12,outline:"none"}}/></div><select value={filterSdr} onChange={e=>setFilterSdr(e.target.value)} style={{padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:12,outline:"none"}}><option value="">Todos SDRs</option>{sdrs.map(s=><option key={s} value={s}>{s}</option>)}</select><button onClick={()=>setShowAdd(true)} style={{display:"flex",alignItems:"center",gap:6,padding:"8px 16px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:12,fontWeight:500,cursor:"pointer"}}><Plus size={14}/>Novo lead</button></div>
<div className="flex gap-3 overflow-x-auto pb-4" style={{minHeight:520}}>{KANBAN_STAGES.map(stage=>{const sl=grouped[stage.key]||[];const sv=sl.reduce((s,l)=>s+(l.valor_venda||0),0);return<div key={stage.key} onDragOver={e=>{e.preventDefault();setDragOver(stage.key);}} onDragLeave={()=>setDragOver(null)} onDrop={e=>handleDrop(stage.key,e)} style={{width:240,flexShrink:0,background:dragOver===stage.key?"rgba(201,168,76,0.04)":BG2,border:`1px solid ${dragOver===stage.key?GOLD_DIM:BORDER}`,borderRadius:12,padding:12,transition:"all 0.2s"}}><div className="flex items-center justify-between" style={{marginBottom:8,padding:"0 4px"}}><div className="flex items-center gap-2"><div style={{width:8,height:8,borderRadius:"50%",background:stage.color}}/><span style={{fontSize:12,fontWeight:500,color:TEXT2}}>{stage.label}</span></div><span style={{fontSize:11,padding:"2px 8px",borderRadius:6,background:"rgba(255,255,255,0.04)",color:TEXT3}}>{sl.length}</span></div>{sv>0&&<div style={{fontSize:10,color:GOLD_DIM,marginBottom:8,paddingLeft:4}}>{fmt(sv)}</div>}{sl.map(lead=><LeadCard key={lead.id} lead={lead} onClick={onLeadClick} equipe={equipe}/>)}</div>;})}</div>
{showAdd&&<AddLeadModal onClose={()=>setShowAdd(false)} onAdd={onAdd} equipe={equipe}/>}</div>;}

function AnalyticsPage({leads}){const[tab,setTab]=useState("campanha");const[compare,setCompare]=useState(false);const now=new Date();const thisM=leads.filter(l=>{const d=new Date(l.created_at);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();});const lastM=leads.filter(l=>{const d=new Date(l.created_at);const lm=new Date(now.getFullYear(),now.getMonth()-1);return d.getMonth()===lm.getMonth()&&d.getFullYear()===lm.getFullYear();});
function agg(data,field){const m={};data.forEach(l=>{const k=l[field]||"—";if(!m[k])m[k]={name:k,leads:0,qualificados:0,agendados:0,vendas:0,receita:0};m[k].leads++;if(["qualificado","agendado","no_show","em_negociacao","venda"].includes(l.stage))m[k].qualificados++;if(["agendado","no_show","em_negociacao","venda"].includes(l.stage))m[k].agendados++;if(l.stage==="venda"){m[k].vendas++;m[k].receita+=l.valor_venda||0;}});return Object.values(m).sort((a,b)=>b.receita-a.receita);}
const fm={campanha:"utm_campaign",conjunto:"utm_term",criativo:"utm_content"};const ad=useMemo(()=>agg(leads,fm[tab]),[leads,tab]);
const sdrs=useMemo(()=>{const m={};leads.filter(l=>l.sdr_nome).forEach(l=>{if(!m[l.sdr_nome])m[l.sdr_nome]={name:l.sdr_nome,leads:0,qualificados:0,agendados:0};m[l.sdr_nome].leads++;if(["qualificado","agendado","no_show","em_negociacao","venda"].includes(l.stage))m[l.sdr_nome].qualificados++;if(["agendado","no_show","em_negociacao","venda"].includes(l.stage))m[l.sdr_nome].agendados++;});return Object.values(m);},[leads]);
const closers=useMemo(()=>{const m={};leads.filter(l=>l.closer_nome).forEach(l=>{if(!m[l.closer_nome])m[l.closer_nome]={name:l.closer_nome,reunioes:0,vendas:0,receita:0};if(["em_negociacao","venda","perdido"].includes(l.stage))m[l.closer_nome].reunioes++;if(l.stage==="venda"){m[l.closer_nome].vendas++;m[l.closer_nome].receita+=l.valor_venda||0;}});return Object.values(m).sort((a,b)=>b.receita-a.receita);},[leads]);
const tmV=thisM.filter(l=>l.stage==="venda"),lmV=lastM.filter(l=>l.stage==="venda");
return<div style={{display:"flex",flexDirection:"column",gap:16}}>
{compare&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><Card style={{padding:16}}><div style={{fontSize:10,color:TEXT3,textTransform:"uppercase",marginBottom:8}}>Este mês</div><div style={{fontSize:20,fontWeight:600,color:GOLD_LIGHT}}>{fmt(tmV.reduce((s,l)=>s+(l.valor_venda||0),0))}</div><div style={{fontSize:11,color:TEXT2,marginTop:4}}>{thisM.length} leads • {tmV.length} vendas</div></Card><Card style={{padding:16}}><div style={{fontSize:10,color:TEXT3,textTransform:"uppercase",marginBottom:8}}>Mês passado</div><div style={{fontSize:20,fontWeight:600,color:TEXT2}}>{fmt(lmV.reduce((s,l)=>s+(l.valor_venda||0),0))}</div><div style={{fontSize:11,color:TEXT3,marginTop:4}}>{lastM.length} leads • {lmV.length} vendas</div></Card></div>}
<Card style={{padding:20}}><div className="flex items-center justify-between" style={{marginBottom:16}}><div className="flex items-center gap-3"><h3 style={{fontSize:13,fontWeight:500,color:TEXT2,margin:0}}>Ads</h3><button onClick={()=>setCompare(!compare)} style={{display:"flex",alignItems:"center",gap:4,padding:"4px 10px",borderRadius:6,border:"none",background:compare?GOLD_BG2:"rgba(255,255,255,0.03)",color:compare?GOLD:TEXT3,fontSize:10,cursor:"pointer"}}><ArrowRightLeft size={10}/>Comparar</button></div><div className="flex gap-1" style={{background:"rgba(255,255,255,0.03)",borderRadius:8,padding:3}}>{["campanha","conjunto","criativo"].map(t=><button key={t} onClick={()=>setTab(t)} style={{padding:"6px 14px",borderRadius:6,border:"none",fontSize:11,fontWeight:500,cursor:"pointer",background:tab===t?GOLD_BG2:"transparent",color:tab===t?GOLD:TEXT3}}>{t.charAt(0).toUpperCase()+t.slice(1)}</button>)}</div></div>
<div style={{overflowX:"auto"}}><table style={{width:"100%",fontSize:12,borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${BORDER}`}}>{[tab.charAt(0).toUpperCase()+tab.slice(1),"Leads","Qualif.","Agend.","Vendas","Receita","% Qual.","% Venda","L/V"].map(h=><th key={h} style={{textAlign:"left",padding:8,fontWeight:500,color:TEXT3,fontSize:10,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{ad.map((r,i)=><tr key={i} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"10px 8px",color:TEXT1,fontWeight:500}}>{r.name}</td><td style={{padding:"10px 8px",color:TEXT2}}>{r.leads}</td><td style={{padding:"10px 8px",color:TEXT2}}>{r.qualificados}</td><td style={{padding:"10px 8px",color:TEXT2}}>{r.agendados}</td><td style={{padding:"10px 8px",color:"#4ADE80",fontWeight:500}}>{r.vendas}</td><td style={{padding:"10px 8px",color:"#4ADE80"}}>{fmt(r.receita)}</td><td style={{padding:"10px 8px",color:TEXT2}}>{pct(r.qualificados,r.leads)}%</td><td style={{padding:"10px 8px",color:TEXT2}}>{pct(r.vendas,r.leads)}%</td><td style={{padding:"10px 8px",color:TEXT2}}>{r.vendas>0?Math.round(r.leads/r.vendas):"—"}</td></tr>)}</tbody></table></div></Card>
<Card style={{padding:20}}><h3 style={{fontSize:13,fontWeight:500,color:TEXT2,marginBottom:16}}>Receita/{tab}</h3><ResponsiveContainer width="100%" height={Math.max(ad.length*40+40,140)}><BarChart data={ad} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)"/><XAxis type="number" tick={{fill:TEXT3,fontSize:10}} axisLine={false} tickLine={false} tickFormatter={v=>`R$${Math.round(v/1000)}k`}/><YAxis type="category" dataKey="name" tick={{fill:TEXT2,fontSize:10}} axisLine={false} tickLine={false} width={140}/><Tooltip contentStyle={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:8,color:TEXT1,fontSize:11}} formatter={v=>fmt(v)}/><Bar dataKey="receita" fill={GOLD} radius={[0,4,4,0]} barSize={18}/></BarChart></ResponsiveContainer></Card>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><Card style={{padding:20}}><h3 style={{fontSize:13,fontWeight:500,color:TEXT2,marginBottom:16}}>SDRs</h3><table style={{width:"100%",fontSize:12,borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${BORDER}`}}>{["SDR","Leads","Qualif.","% Qual."].map(h=><th key={h} style={{textAlign:"left",padding:8,fontWeight:500,color:TEXT3,fontSize:10,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{sdrs.map(s=><tr key={s.name} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"10px 8px",color:TEXT1,fontWeight:500}}>{s.name}</td><td style={{padding:"10px 8px",color:TEXT2}}>{s.leads}</td><td style={{padding:"10px 8px",color:TEXT2}}>{s.qualificados}</td><td style={{padding:"10px 8px"}}><span style={{padding:"2px 8px",borderRadius:4,fontSize:10,fontWeight:600,background:pct(s.qualificados,s.leads)>=35?"rgba(74,222,128,0.1)":GOLD_BG,color:pct(s.qualificados,s.leads)>=35?"#4ADE80":GOLD}}>{pct(s.qualificados,s.leads)}%</span></td></tr>)}</tbody></table></Card>
<Card style={{padding:20}}><h3 style={{fontSize:13,fontWeight:500,color:TEXT2,marginBottom:16}}>Closers</h3><table style={{width:"100%",fontSize:12,borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${BORDER}`}}>{["Closer","Reuniões","Vendas","Receita","Fech."].map(h=><th key={h} style={{textAlign:"left",padding:8,fontWeight:500,color:TEXT3,fontSize:10,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{closers.map(c=><tr key={c.name} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"10px 8px",color:TEXT1,fontWeight:500}}>{c.name}</td><td style={{padding:"10px 8px",color:TEXT2}}>{c.reunioes}</td><td style={{padding:"10px 8px",color:"#4ADE80",fontWeight:500}}>{c.vendas}</td><td style={{padding:"10px 8px",color:"#4ADE80"}}>{fmt(c.receita)}</td><td style={{padding:"10px 8px"}}><span style={{padding:"2px 8px",borderRadius:4,fontSize:10,fontWeight:600,background:pct(c.vendas,c.reunioes)>=30?"rgba(74,222,128,0.1)":GOLD_BG,color:pct(c.vendas,c.reunioes)>=30?"#4ADE80":GOLD}}>{pct(c.vendas,c.reunioes)}%</span></td></tr>)}</tbody></table></Card></div></div>;}

function TrackingPage({eventos}){const t=eventos.length,s=eventos.filter(e=>e.sucesso).length,er=eventos.filter(e=>!e.sucesso).length;const bt=useMemo(()=>{const m={};eventos.forEach(e=>{m[e.evento]=(m[e.evento]||0)+1;});return Object.entries(m).map(([k,v])=>({name:k,value:v}));},[eventos]);const cl={Lead:GOLD,QualifiedLead:"#34D399",Schedule:"#A78BFA",Purchase:"#4ADE80"};
return<div style={{display:"flex",flexDirection:"column",gap:16}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:12}}><MetricCard icon={Zap} label="Eventos" value={t} accent/><MetricCard icon={Check} label="Sucesso" value={`${pct(s,t)}%`}/><MetricCard icon={AlertTriangle} label="Erros" value={er}/></div>
<Card style={{padding:20}}><h3 style={{fontSize:13,fontWeight:500,color:TEXT2,marginBottom:16}}>Por tipo</h3><ResponsiveContainer width="100%" height={160}><BarChart data={bt}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)"/><XAxis dataKey="name" tick={{fill:TEXT2,fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fill:TEXT3,fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:8,color:TEXT1,fontSize:11}}/><Bar dataKey="value" radius={[4,4,0,0]} barSize={36}>{bt.map((e,i)=><Cell key={i} fill={cl[e.name]||GOLD}/>)}</Bar></BarChart></ResponsiveContainer></Card>
<Card style={{padding:20}}><h3 style={{fontSize:13,fontWeight:500,color:TEXT2,marginBottom:16}}>Log</h3><table style={{width:"100%",fontSize:12,borderCollapse:"collapse"}}><thead><tr style={{borderBottom:`1px solid ${BORDER}`}}>{["Evento","Plataforma","Status","Data"].map(h=><th key={h} style={{textAlign:"left",padding:8,fontWeight:500,color:TEXT3,fontSize:10,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{eventos.map(e=><tr key={e.id} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"10px 8px"}}><span style={{padding:"3px 10px",borderRadius:20,fontSize:10,fontWeight:500,background:`${cl[e.evento]||GOLD}15`,color:cl[e.evento]||GOLD}}>{e.evento}</span></td><td style={{padding:"10px 8px",color:TEXT2,textTransform:"capitalize"}}>{e.plataforma}</td><td style={{padding:"10px 8px"}}>{e.sucesso?<span className="flex items-center gap-1" style={{color:"#4ADE80"}}><Check size={12}/>OK</span>:<span className="flex items-center gap-1" style={{color:"#F87171"}}><X size={12}/>{e.erro}</span>}</td><td style={{padding:"10px 8px",color:TEXT3}}>{new Date(e.created_at).toLocaleString("pt-BR")}</td></tr>)}</tbody></table></Card></div>;}

function TemplatesPage({templates,loading,addTemplate,removeTemplate}){const[show,setShow]=useState(false);const[ti,setTi]=useState("");const[ms,setMs]=useState("");const[ca,setCa]=useState("outro");const cats={primeira_abordagem:"Primeira abordagem",followup:"Follow-up",agendamento:"Agendamento",recontato:"Recontato",no_show:"No-show",outro:"Outro"};
const add=async()=>{if(!ti.trim()||!ms.trim())return;await addTemplate({titulo:ti,mensagem:ms,categoria:ca,ativo:true});setTi("");setMs("");setShow(false);};const IS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
return<div style={{display:"flex",flexDirection:"column",gap:16}}><div className="flex items-center justify-between"><h3 style={{fontSize:13,fontWeight:500,color:TEXT2}}>Use <code style={{color:GOLD}}>{"{{nome}}"}</code> para nome do lead</h3><button onClick={()=>setShow(!show)} style={{display:"flex",alignItems:"center",gap:6,padding:"8px 16px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:12,fontWeight:500,cursor:"pointer"}}><Plus size={14}/>Novo</button></div>
{show&&<Card style={{padding:16}}><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:10,marginBottom:10}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Título</label><input value={ti} onChange={e=>setTi(e.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Categoria</label><select value={ca} onChange={e=>setCa(e.target.value)} style={IS}>{Object.entries(cats).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div></div><div style={{marginBottom:10}}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Mensagem</label><textarea value={ms} onChange={e=>setMs(e.target.value)} rows={3} style={{...IS,resize:"vertical"}}/></div><div className="flex gap-2"><button onClick={add} style={{padding:"8px 20px",borderRadius:8,border:"none",background:GOLD,color:BG,fontSize:12,fontWeight:600,cursor:"pointer"}}>Salvar</button><button onClick={()=>setShow(false)} style={{padding:"8px 20px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:12,cursor:"pointer"}}>Cancelar</button></div></Card>}
{loading?<Spinner/>:templates.map(t=><Card key={t.id} style={{padding:16}}><div className="flex items-center justify-between" style={{marginBottom:8}}><div className="flex items-center gap-2"><span style={{fontSize:13,fontWeight:500,color:GOLD}}>{t.titulo}</span><span style={{fontSize:9,padding:"2px 8px",borderRadius:10,background:"rgba(255,255,255,0.04)",color:TEXT3}}>{cats[t.categoria]||t.categoria}</span></div><button onClick={()=>removeTemplate(t.id)} style={{padding:6,borderRadius:6,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:"#F87171"}}><Trash2 size={12}/></button></div><div style={{fontSize:12,color:TEXT2,lineHeight:1.6}}>{t.mensagem}</div></Card>)}</div>;}

function ConfigPage({equipe,eqLoading,addMember,removeMember,toggleActive,config}){const[show,setShow]=useState(false);const[fn,setFn]=useState("");const[fp,setFp]=useState("sdr");const[ft,setFt]=useState("");const[fe,setFe]=useState("");const[fc,setFc]=useState(TEAM_COLORS[0]);const IS={width:"100%",padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,color:TEXT1,fontSize:13,outline:"none"};
const add=async()=>{if(!fn.trim())return;await addMember({nome:fn,papel:fp,telefone:ft,email:fe,cor:fc,ativo:true});setFn("");setFt("");setFe("");setShow(false);};
return<div style={{display:"flex",flexDirection:"column",gap:16}}>
<Card style={{padding:24}}><h3 style={{fontSize:13,fontWeight:500,color:TEXT2,marginBottom:20}}>Pixel</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,maxWidth:600}}>{[{l:"Pixel ID",v:config?.meta_pixel_id||"—"},{l:"Token",v:config?.meta_access_token?"••••••••":"—"},{l:"Test Code",v:config?.meta_test_event_code||"Produção"},{l:"Domínio",v:config?.dominio||"—"},{l:"Meta Mensal",v:config?.meta_mensal?fmt(config.meta_mensal):"—"},{l:"Gasto Ads",v:config?.gasto_ads_mensal?fmt(config.gasto_ads_mensal):"—"}].map(f=><div key={f.l}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>{f.l}</label><div style={{padding:"8px 12px",borderRadius:8,border:`1px solid ${BORDER}`,background:BG3,fontSize:12,color:TEXT2}}>{f.v}</div></div>)}</div></Card>
<Card style={{padding:24}}><div className="flex items-center justify-between" style={{marginBottom:20}}><div><h3 style={{fontSize:13,fontWeight:500,color:TEXT2,margin:0}}>Equipe</h3></div><button onClick={()=>setShow(!show)} style={{display:"flex",alignItems:"center",gap:6,padding:"8px 16px",borderRadius:8,border:"none",background:GOLD_BG2,color:GOLD,fontSize:12,fontWeight:500,cursor:"pointer"}}><Plus size={14}/>Adicionar</button></div>
{show&&<div style={{background:BG3,border:`1px solid ${BORDER2}`,borderRadius:12,padding:16,marginBottom:16}}><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:10,marginBottom:10}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Nome</label><input value={fn} onChange={e=>setFn(e.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Papel</label><select value={fp} onChange={e=>setFp(e.target.value)} style={IS}><option value="sdr">SDR</option><option value="closer">Closer</option></select></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:10}}><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Telefone</label><input value={ft} onChange={e=>setFt(e.target.value)} style={IS}/></div><div><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Email</label><input value={fe} onChange={e=>setFe(e.target.value)} style={IS}/></div></div><div style={{marginBottom:12}}><label style={{fontSize:9,color:TEXT3,textTransform:"uppercase",display:"block",marginBottom:4}}>Cor</label><div className="flex gap-2">{TEAM_COLORS.map(c=><div key={c} onClick={()=>setFc(c)} style={{width:28,height:28,borderRadius:6,background:c,cursor:"pointer",border:fc===c?`2px solid ${TEXT1}`:"2px solid transparent"}}/>)}</div></div><div className="flex gap-2"><button onClick={add} style={{padding:"8px 20px",borderRadius:8,border:"none",background:GOLD,color:BG,fontSize:12,fontWeight:600,cursor:"pointer"}}>Salvar</button><button onClick={()=>setShow(false)} style={{padding:"8px 20px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:12,cursor:"pointer"}}>Cancelar</button></div></div>}
{eqLoading?<Spinner/>:["sdr","closer"].map(papel=>{const members=equipe.filter(m=>m.papel===papel);return<div key={papel} style={{marginBottom:20}}><div className="flex items-center gap-2" style={{marginBottom:10}}>{papel==="sdr"?<Phone size={14} style={{color:GOLD}}/>:<Award size={14} style={{color:GOLD}}/>}<span style={{fontSize:12,fontWeight:600,color:GOLD,textTransform:"uppercase"}}>{papel==="sdr"?"SDRs":"Closers"}</span><span style={{fontSize:10,color:TEXT3}}>({members.length})</span></div>{members.length===0&&<div style={{fontSize:12,color:TEXT3,padding:"10px 0"}}>Nenhum</div>}{members.map(m=><div key={m.id} className="flex items-center justify-between" style={{padding:"10px 12px",borderRadius:8,border:`1px solid ${BORDER}`,marginBottom:6,opacity:m.ativo?1:.5}}><div className="flex items-center gap-3"><div style={{width:34,height:34,borderRadius:"50%",background:`${m.cor||GOLD}22`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:600,color:m.cor||GOLD,border:`2px solid ${m.cor||GOLD}`}}>{m.nome.split(" ").map(n=>n[0]).join("").slice(0,2)}</div><div><div style={{fontSize:13,fontWeight:500,color:TEXT1}}>{m.nome}</div><div style={{fontSize:10,color:TEXT3}}>{m.telefone||""}{m.email?` • ${m.email}`:""}</div></div></div><div className="flex items-center gap-2"><button onClick={()=>toggleActive(m.id,m.ativo)} style={{padding:6,borderRadius:6,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:m.ativo?"#4ADE80":TEXT3}}>{m.ativo?<Eye size={14}/>:<EyeOff size={14}/>}</button><button onClick={()=>removeMember(m.id)} style={{padding:6,borderRadius:6,border:"none",background:"rgba(255,255,255,0.04)",cursor:"pointer",color:"#F87171"}}><Trash2 size={14}/></button></div></div>)}</div>;})}
</Card></div>;}

export default function App(){const[page,setPage]=useState("dashboard");const[sel,setSel]=useState(null);const{leads,loading:ll,refetch,updateLead,addLead,deleteLead}=useLeads();const{eventos,loading:el}=useEventos();const{equipe,loading:eql,addMember,removeMember,toggleActive}=useEquipe();const{templates,loading:tl,addTemplate,removeTemplate}=useTemplates();const config=useConfig();const vendas=leads.filter(l=>l.stage==="venda");
return<div className="flex" style={{minHeight:"100vh",background:BG,fontFamily:"'DM Sans',system-ui,sans-serif",color:TEXT1}}><style>{`@keyframes spin{to{transform:rotate(360deg)}}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.6}}`}</style>
<aside className="hidden md:flex" style={{width:210,flexShrink:0,borderRight:`1px solid ${BORDER}`,padding:16,flexDirection:"column",background:BG2}}><div style={{marginBottom:32,paddingLeft:8}}><Logo/><p style={{fontSize:9,color:TEXT3,letterSpacing:"0.12em",textTransform:"uppercase",marginTop:4}}>CRM High Ticket</p></div><nav style={{flex:1,display:"flex",flexDirection:"column",gap:2}}>{NAV.map(n=><button key={n.key} onClick={()=>setPage(n.key)} style={{display:"flex",alignItems:"center",gap:10,padding:"9px 12px",borderRadius:8,border:"none",fontSize:13,fontWeight:500,cursor:"pointer",textAlign:"left",width:"100%",background:page===n.key?GOLD_BG2:"transparent",color:page===n.key?GOLD:TEXT3}}><n.icon size={16}/>{n.label}</button>)}</nav><div style={{paddingTop:16,borderTop:`1px solid ${BORDER}`,marginTop:"auto"}}><div style={{fontSize:10,color:GOLD_DIM}}>{config?.nome_negocio||"CRM"}</div><div style={{fontSize:9,color:TEXT3,marginTop:2}}>{leads.length} leads • {vendas.length} vendas</div></div></aside>
<main style={{flex:1,padding:"16px 20px",overflowY:"auto",maxHeight:"100vh"}}><div className="flex md:hidden flex-wrap gap-1" style={{marginBottom:12,background:BG2,borderRadius:8,padding:3}}>{NAV.map(n=><button key={n.key} onClick={()=>setPage(n.key)} style={{padding:"6px 10px",borderRadius:6,border:"none",fontSize:10,cursor:"pointer",background:page===n.key?GOLD_BG2:"transparent",color:page===n.key?GOLD:TEXT3}}><n.icon size={12}/></button>)}</div>
<div className="flex items-center justify-between" style={{marginBottom:20}}><div><h2 style={{fontSize:18,fontWeight:600,color:TEXT1,margin:0}}>{NAV.find(n=>n.key===page)?.label}</h2><p style={{fontSize:11,color:TEXT3,margin:"4px 0 0"}}>{leads.length} leads</p></div><button onClick={refetch} style={{display:"flex",alignItems:"center",gap:6,padding:"7px 14px",borderRadius:8,border:`1px solid ${BORDER}`,background:"transparent",color:TEXT3,fontSize:11,cursor:"pointer"}}><RefreshCw size={12}/>Atualizar</button></div>
{page==="dashboard"&&(ll?<Spinner/>:<DashboardPage leads={leads} config={config}/>)}
{page==="crm"&&(ll?<Spinner/>:<CRMPage leads={leads} onLeadClick={setSel} onUpdate={updateLead} equipe={equipe} onAdd={addLead}/>)}
{page==="analytics"&&(ll?<Spinner/>:<AnalyticsPage leads={leads}/>)}
{page==="tracking"&&(el?<Spinner/>:<TrackingPage eventos={eventos}/>)}
{page==="templates"&&<TemplatesPage templates={templates} loading={tl} addTemplate={addTemplate} removeTemplate={removeTemplate}/>}
{page==="config"&&<ConfigPage equipe={equipe} eqLoading={eql} addMember={addMember} removeMember={removeMember} toggleActive={toggleActive} config={config}/>}
</main>
{sel&&<LeadModal lead={sel} onClose={()=>{setSel(null);refetch();}} onUpdate={updateLead} onDelete={deleteLead} equipe={equipe} templates={templates}/>}
</div>;}
